### ISSUE TITLE
Mame4ios 11

### ISSUE THREAD

**Issue by nsotiriou** [yoshisuga/MAME4iOS#10]
Hello,
How difficult is to build a 64bit version of MAME4iOS for the rest of us.....
Thank you in advance,
Nicholas

**Comment by yoshisuga** [comment]
Hi! The build should be 64-bit ready as I have it running on my phone in iOS 11. 

What issues are you have in building it?

**Comment by nsotiriou** [comment]
Hi frown Athens , Greece
Thank you very very match for your reply,
I am a fan of MAME and after the upgrade to ios 11 I lost the opportunity for side loading using Impactor with Mame4ios 1.6.
Please help me to make my own Mame with code. To be honest I am Newby with xcode so the mistake i am repeating maybe is silly.
Here is the error during the process of build.
16 errors

Showing All Errors Only
  "std::string::reserve(unsigned long)", referenced from:


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(inst.o)


  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()", referenced from:


      DSP56K::Mac_3::Mac_3(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Macr_2::Macr_2(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Mpy_2::Mpy_2(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Mpyr_2::Mpyr_2(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Add_2::Add_2(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Mpy_3::Mpy_3(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Mpy::Mpy(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      ...


  "std::string::append(char const*)", referenced from:


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(opcode.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(inst.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(pmove.o)


  "std::string::compare(char const*) const", referenced from:


      bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(inst.o)


      bool std::operator!=<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(inst.o)


      bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(pmove.o)


      bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(tables.o)


  "std::string::compare(std::string const&) const", referenced from:


      bool std::operator!=<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(inst.o)


      bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(inst.o)


      bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(tables.o)


  "std::string::operator=(char const*)", referenced from:


      DSP56K::Tfr_2::decode(unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Move_2::decode(unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Mac_3::Mac_3(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Mac_3::decode(unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Macr_2::Macr_2(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Macr_2::decode(unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Mpy_2::Mpy_2(DSP56K::Opcode const*, unsigned short, unsigned short) in libmamearm64.a(inst.o)


      ...


  "std::string::size() const", referenced from:


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(inst.o)


  "std::string::operator=(std::string const&)", referenced from:


      DSP56K::Tfr_2::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Move_2::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Mac_3::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Macr_2::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Mpy_2::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Mpyr_2::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Add_2::disassemble(std::string&) const in libmamearm64.a(inst.o)


      ...


  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)", referenced from:


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(opcode.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(opcode.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(inst.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(inst.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(pmove.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(pmove.o)


  "std::string::append(char const*, unsigned long)", referenced from:


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(inst.o)


  "std::string::operator+=(std::string const&)", referenced from:


      DSP56K::Tcc::disassemble(std::string&) const in libmamearm64.a(inst.o)


  "std::string::append(std::string const&)", referenced from:


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(opcode.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(inst.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(inst.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(pmove.o)


  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:


      DSP56K::Opcode::disassemble() const in libmamearm64.a(opcode.o)


      DSP56K::Opcode::dcString() const in libmamearm64.a(opcode.o)


      DSP56K::Instruction::Instruction(DSP56K::Opcode const*) in libmamearm64.a(inst.o)


      DSP56K::Andi::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Bcc::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Bcc_2::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Bra::disassemble(std::string&) const in libmamearm64.a(inst.o)


      ...


  "std::string::c_str() const", referenced from:


      cpu_disassemble_dsp56k(legacy_cpu_device*, char*, unsigned int, unsigned char const*, unsigned char const*, int) in libmamearm64.a(dsp56dsm.o)


      DSP56K::Andi::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::Movec_4::decode(unsigned short, unsigned short) in libmamearm64.a(inst.o)


      DSP56K::Rep::disassemble(std::string&) const in libmamearm64.a(inst.o)


      DSP56K::DualXMemoryDataRead::decode(unsigned short, unsigned short) in libmamearm64.a(pmove.o)


      DSP56K::XMemoryDataWriteAndRegisterDataMove::decode(unsigned short, unsigned short) in libmamearm64.a(pmove.o)


      DSP56K::assemble_D_from_P_table(unsigned short, unsigned short, std::string&) in libmamearm64.a(tables.o)


      ...


  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()", referenced from:


      cpu_disassemble_dsp56k(legacy_cpu_device*, char*, unsigned int, unsigned char const*, unsigned char const*, int) in libmamearm64.a(dsp56dsm.o)


      DSP56K::Opcode::disassemble() const in libmamearm64.a(opcode.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in libmamearm64.a(opcode.o)


      std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) in libmamearm64.a(opcode.o)


      DSP56K::Instruction::Instruction(DSP56K::Opcode const*) in libmamearm64.a(inst.o)


      DSP56K::Instruction::~Instruction() in libmamearm64.a(inst.o)


      DSP56K::Tfr_2::disassemble(std::string&) const in libmamearm64.a(inst.o)


      ...


ld: symbol(s) not found for architecture arm64


clang: error: linker command failed with exit code 1 (use -v to see invocation)


Maybe there is a way to send the errors with different way but i thing that is clear to you where is the problem.
Please help me if it is possible.

Thank you in advance.
Sorry for my English.
Nicholas

> 5 Νοε 2017, 2:07 πμ, ο χρήστης «yoshisuga <notifications@github.com>» έγραψε:
> 
> Hi! The build should be 64-bit ready as I have it running on my phone in iOS 11. 
> 
> What issues are you have in building it?
> 
> Sent from my iPhone
>

**Comment by nsotiriou** [comment]
Hello from Athens,
Here is the error i take from the project, I dont know what to send or what to see in order to help. Thank you in advance.
Nicholas

clang: error: linker command failed with exit code 1 (use -v to see invocation)



Ld /Users/nicholassotiriou/Library/Developer/Xcode/DerivedData/MAME4iOS-fiwpgfolmsdoqlepetfcnnypbowa/Build/Products/Debug-iphoneos/MAME4iOS\ 64-bit.app/MAME4iOS\ 64-bit normal arm64
    cd /Users/nicholassotiriou/Desktop/MAME4iOS-master/xcode/MAME4iOS
    export IPHONEOS_DEPLOYMENT_TARGET=5.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk -L/Users/nicholassotiriou/Library/Developer/Xcode/DerivedData/MAME4iOS-fiwpgfolmsdoqlepetfcnnypbowa/Build/Products/Debug-iphoneos -L/Users/nicholassotiriou/Desktop/MAME4iOS-master/xcode/MAME4iOS/../.. -L/Users/nicholassotiriou/Desktop/MAME4iOS-master/xcode/MAME4iOS/MAME4iOS -L/Users/nicholassotiriou/Desktop/MAME4iOS-master/xcode/MAME4iOS -F/Users/nicholassotiriou/Library/Developer/Xcode/DerivedData/MAME4iOS-fiwpgfolmsdoqlepetfcnnypbowa/Build/Products/Debug-iphoneos -filelist /Users/nicholassotiriou/Library/Developer/Xcode/DerivedData/MAME4iOS-fiwpgfolmsdoqlepetfcnnypbowa/Build/Intermediates.noindex/MAME4iOS.build/Debug-iphoneos/MAME4iOS\ 64-bit.build/Objects-normal/arm64/MAME4iOS\ 64-bit.LinkFileList -miphoneos-version-min=5.1 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/nicholassotiriou/Library/Developer/Xcode/DerivedData/MAME4iOS-fiwpgfolmsdoqlepetfcnnypbowa/Build/Intermediates.noindex/MAME4iOS.build/Debug-iphoneos/MAME4iOS\ 64-bit.build/Objects-normal/arm64/MAME4iOS\ 64-bit_lto.o -Xlinker -no_deduplicate -fobjc-link-runtime -lstdc++ -lmamearm64 -framework GameController -framework CoreBluetooth -framework CoreFoundation -framework AudioToolbox -framework QuartzCore -framework UIKit -lmamearmv7 -framework Foundation -framework CoreGraphics -framework GameKit -lz -lstdc++ -Xlinker -dependency_info -Xlinker /Users/nicholassotiriou/Library/Developer/Xcode/DerivedData/MAME4iOS-fiwpgfolmsdoqlepetfcnnypbowa/Build/Intermediates.noindex/MAME4iOS.build/Debug-iphoneos/MAME4iOS\ 64-bit.build/Objects-normal/arm64/MAME4iOS\ 64-bit_dependency_info.dat -o /Users/nicholassotiriou/Library/Developer/Xcode/DerivedData/MAME4iOS-fiwpgfolmsdoqlepetfcnnypbowa/Build/Products/Debug-iphoneos/MAME4iOS\ 64-bit.app/MAME4iOS\ 64-bit


> 5 Νοε 2017, 2:07 πμ, ο χρήστης «yoshisuga <notifications@github.com>» έγραψε:
> 
> Hi! The build should be 64-bit ready as I have it running on my phone in iOS 11. 
> 
> What issues are you have in building it?
> 
> Sent from my iPhone
>

**Comment by yoshisuga** [comment]
Closing, building with libc++ so not relevant anymore
