### ISSUE TITLE
Import ROMs via UIDocumentViewController

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#101]
It would be easy to import ROMS/ZIP via the standard iOS document browser.  The hard part would be adding UI to the UITableView of hell that is the Settings.

Currently you can send ZIP files to MAME4iOS, but MAME4iOS cant go get them, so adding a button in settings called “import...” might be a good idea.

**Comment by mrjschulte** [comment]
Yup, like it.

**Comment by ToddLa** [comment]
PR #115 does this.
