### ISSUE TITLE
tvOS Top Shelf

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#103]
Add a Top Shelf to MAME4tvOS

The Top Shelp would show Recent Games, followed by Favotie Games.  If you select a game it would launch MAME4tvOS and start game.

**Comment by mrjschulte** [comment]
This would be great to have, and would really help make this app a more full fledged member of the tvOS UI experience, but I don't feel that this is currently too high up in the priority list. Thoughts?
