### ISSUE TITLE
Game Filter...

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#106]
Now that we have a native UICollectionView based UI, should be remove or hide the filter options in Settings?

**Comment by mrjschulte** [comment]
Had a quick look at the filter options in the old droidios menu and the "hide non working" and "hide clones" filter options are great to get into the Native UI. Adding in the "Driver source" in the new Native UI would also help filter just the CPS-1/2/3 or NeoGeo relevant games as well.

**Comment by ToddLa** [comment]
PR #115 has this change.
NOTE currently the "driver source" does not "get sent up from the dungeon" from the UI layer, would need to look at how easy that is...
