### ISSUE TITLE
Move Start Server to the Settings dialog.

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#107]
Move Start Server from the top level menu into the Settings dialog, possibly next to Import and Export options....

**Comment by mrjschulte** [comment]
Yes, feels like a  much better place for it. Good suggestion!

**Comment by ToddLa** [comment]
Start Server, Import ROMs (and soon Export ROMs) are at the bottom of the Settings in PR #115 
![IMG_D326295E11D3-1](https://user-images.githubusercontent.com/4494698/75615306-e8a7ff00-5af6-11ea-8011-e8413690c03d.jpeg)
