### ISSUE TITLE
Minimum iOS version.

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#108]
The iPhone 5s is the oldest 64bit device, it runs iOS 12
So setting min version of iOS 12.2 would not be crazy, min version of iOS 11 would be ok too.

Are there any Jailbreak concerns? With CheckRa1n out that should up the min version.

**Comment by yoshisuga** [comment]
Yep iOS 12 as min version sounds totally fine to me.

**Comment by ToddLa** [comment]
No advantage to iOS 12 vs iOS 11 so 11 would be ok too

**Comment by mrjschulte** [comment]
Yes, let's aim for a minimum version of 11.0 and just leave it at that for now.

**Comment by mrjschulte** [comment]
We're now locked into a minimum version of iOS 11 for the libmame builds. 

Xcode project changes are next.

**Comment by yoshisuga** [comment]
Changed to iOS 11.0 for deploy target
