### ISSUE TITLE
Investigate adding in support for ProMotion displays for exact Refresh rate matching.

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#112]
We should investigate what it would take if we wanted to add in support for the "preferredFramesPerSecond" parameter on the CADisplaylink controller to see if we can get actual 1:1 refresh rate matching on the Apple iOS devices that support ProMotion.

**Comment by ToddLa** [comment]
What range of Hz do the games have? I would think almost all would be 59.97Hz maybe some PAL games?

**Comment by mrjschulte** [comment]
Looks like this only takes ints so game over...
