### ISSUE TITLE
Add support for doing Integer scaling

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#113]
Currently the "view" scaling of the games fills out the entire screen view, at whatever orientation is set. Investigate what adding in an "Integer Scaling" option would do and looks like.

**Comment by ToddLa** [comment]
I dont think in the era of GPU scaling that integer scaling is even an issue anymore.

**Comment by mrjschulte** [comment]
I think the interest here is to see if we can scale the screen view to the iOS display buffer with "clean" mults that preserve the original intent (which I will grant is a tough sell conceptually when this stuff was designed on CRT's with all kinds of Electro Optical subtleties).

**Comment by mrjschulte** [comment]
(Having a Mtl backend would allow for this kind of experimentation without affecting mainline.)

**Comment by mrjschulte** [comment]
IF we ever move to MTL we can take care of this there. Closing.

**Comment by mrjschulte** [comment]
Added in new PR.
