### ISSUE TITLE
tvOS launch icon missing

### ISSUE THREAD

**Issue by vinomarkus** [yoshisuga/MAME4iOS#116]
Hi,

Loving the recent update for tvOS - much easier to navigate and launch roms.

The only negative since I've built a version mid last year is that now there is no longer any launch icon in the tvOS interface - its just a blank icon without even any text. The only reason I knew to launch it was that it was the only new icon in the interface! I'm sure it's just remapping some resource pointers, but I'm not familiar enough about xcode to figure it out myself sorry

Mark

**Comment by mrjschulte** [comment]
Thanks for reporting. We'll take a look and make the needed changes.

**Comment by ToddLa** [comment]
I see a launch icon on my TV might be a thing with side loading ipa? or did you build it

**Comment by vinomarkus** [comment]
I built it using the sh script, then loaded onto device with Xcode per instructions.... or at least my interpretation of them!

**Comment by vinomarkus** [comment]
FYI - I tried what was suggested by user Ely in the below link

https://stackoverflow.com/questions/37263516/tvos-icon-not-showing

But couldn’t figure out where the project settings was

**Comment by mrjschulte** [comment]
The app icon shows up fine for me on tvOS.

**Comment by vinomarkus** [comment]
What version Xcode are you using?

**Comment by mrjschulte** [comment]
I'm on 10.3 myself.

**Comment by vinomarkus** [comment]
I wonder if the problem is only apparent with the later XCode builds?

According to a StackOverflow post;
https://stackoverflow.com/questions/37263516/tvos-icon-not-showing

Ely writes;
"In Xcode 11, there is a bug with tvOS app icons. To solve it, rename App
Icon & Top Shelf Image or Brand Assets in the Assets to AppIcon. In the
project settings make sure this is also selected as app icon."

**Comment by vinomarkus** [comment]
I'm on 11.3.1 myself btw....

**Comment by mrjschulte** [comment]
Not seeing this. Can you repull from the latest and confirm?

**Comment by ToddLa** [comment]
iOS does some cacheing of launch images, icons, snapshots, and top shelf images, and it gets confused. For example on my dev phone I have had the wrong launch image for a month. 

Best thing to do is go to the device, enter “jiggle mode” and delete the app, then build/run/push.

**Comment by mrjschulte** [comment]
I've done tens of rebuilds and redists the last few days and haven't run into this so going to close. If it comes up again, and has repro steps, please don't hesitate to file again!
