### ISSUE TITLE
tvOS - Unable to upload additional ROMS after initial upload

### ISSUE THREAD

**Issue by vinomarkus** [yoshisuga/MAME4iOS#119]
Hi,

I've found that there is no apparent way to put tvOS back into web server mode to upload additional roms once roms have previoulsy been loaded and the origianl web server dialog has been dismissed

This would be a nice to have feature (or if available already, perhaps making clearer where/how) so that we dont have to rebuild / sideload to get additional roms on

Thanks,

Mark

**Comment by ToddLa** [comment]
Start Server has moved to Settings.

hit MENU
choose Settings from the list.
choose "Start Server" (it is at the bottom)

we are gonna move it to the top to make it easier to find (sorry) we did it on iPhone but forgot tvOS

**Comment by mrjschulte** [comment]
Done and closed.
