### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by guybarke** [yoshisuga/MAME4iOS#12]
Please please help
ipad iOS 11.2.1
macOs 10.13.3
xcode 9.2 

i have followed the instruction and keep getting build failed 

133 errors ? lots like this one

/Users/Guy B/Desktop/MAME4iOS/iOS/EmulatorController.h:81:3: 'UIActionSheet' is deprecated: first deprecated in iOS 8.3 - UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead

i also have libmamearm64.a in the root but the project is not seeing it and only displaying libmamearmv7.a in red ?

please can anybody advise me its driving me nuts

many thanks

Guy

**Comment by ChrisHoooo** [comment]
In Build Settings:
1. C++ Language Dialect -> Compiler Default
2. C++ Standard Library -> Compiler Default
In Build Phases:
Add "libstdc++.6.tbd" to the "Link Binary With Libraries" List

**Comment by guybarke** [comment]
Hi Chris, thank you so much for your message...

i have done as you advised and it has had no effect ...i am still getting all the same errors 

i also have libmamearm64.a in the root but the project is not seeing it and only displaying libmamearmv7.a in red ?

please can you offer any further advice

many  thanks

Guy

**Comment by guybarke** [comment]
does anybody have the built ipa file they could just upload please ?

i can then sign it and install with my ipastore app no problem

**Comment by ChrisHoooo** [comment]
HI, 
In  Build Settings:
Set "Valid Architectures " to arm64, not armV7a

**Comment by guybarke** [comment]
sorry tried that and still not building ? can you upload a prebuilt ipa 64bit version

**Comment by ChrisHoooo** [comment]
no, forget the prebuilt lib, if you have libmamearm64.a, then it may be OK.
Have you selected the right built target ?
I mean you should select "MAME4iOS 64-bit" target. not "MAME4iOS 32-bit", nether "Gridlee"

hope it helps : >

**Comment by guybarke** [comment]
hi..yes build target is set as you advise but the build keeps failing with multiple dependency errors?
please could you just build it and upload for me its very frustrating as i have followed the developers instructions to the letter and build just keeps failing ?
Thanks

**Comment by yoshisuga** [comment]
Hi there, I put a link to the latest IPA in the readme, and it's here:

https://mega.nz/#!XII3UTxb!LsCOZIPDwwk35SfPYlMg8I9WQZMFLU_y9VjchGSObCg

**Comment by yoshisuga** [comment]
It should just build as long as you're able to build the libmamearm64.a - if you can show actual compile errors (the error you listed was a warning about UIAlertController and it should still just work), that would help.

**Comment by guybarke** [comment]
Thank you the ipa is working great

**Comment by yoshisuga** [comment]
Your welcome!
