### ISSUE TITLE
Need some non-programer artwork.

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#122]
default_game_icon.png - used if we have no TITLE artwork
loading_game_icon.png - used while we are looking for TITLE artwork.

the currently are 4:3 but might be better as 1:1 or 3:4

**Comment by ToddLa** [comment]
They should look almost the same, maybe the loading version just has a red dot in the corner or something..

OR the loading version is totally transparent, and the default is a generic game

**Comment by mrjschulte** [comment]
Should we use the default Mame logo image for this?

**Comment by mrjschulte** [comment]
@ToddLa , I'm fine with using the MAME Logo in a 4x3 aspect for this.
