### ISSUE TITLE
ABYX on Dual Shock

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#123]
There are some places MAME4iOS talks about Controller buttons (in README.md and help.md, and some dialogs)

Do we care about calling them Circle, Cross, etc when a Dual Shock is connected??

**Comment by yoshisuga** [comment]
I was thinking we can adopt the icons showing the button position, like the
Nintendo switch does with the detached joycons. I think this is what apple
recommends too.

**Comment by ToddLa** [comment]
We only show A and B in two dialogs, and they are for standard stuff. So I don’t think it is worth it. At least for now

**Comment by mrjschulte** [comment]
Yeah, this feels like nice to have.
