### ISSUE TITLE
I made keyboard layout support for Mahjong games.  Should I share it ?

### ISSUE THREAD

**Issue by ChrisHoooo** [yoshisuga/MAME4iOS#13]
Hi, yoshisuga

Thank you very much for all of this. I downloaded, built, installed, and had a lot of fun with it.

I found that there is no keyboard support for the mahjong games, especially for the hot gimmick series made by Psikyo.(Wow, there is quite a lot of mature content, but beautiful and funny.) Mahjong games need a different keyboard layout, with A-N buttons, with a few extra function buttons, and without joystick.

So I downloaded the repo, and modified it. Now I can play the Mahjong games normally now. : >
I hope I can upload my little work for anyone who wants to play mahjong games. 
Or, better, I can zip my project and send it to you.

Thank you again.

Chris

**Comment by yoshisuga** [comment]
Hi! I'd be glad to add your changes - you can either send me the zip or
make a pull request if you know how to do that. If you can let me know what
you changed too that'd be great.

With the mahjong games, you can usually map the A-N keys to a controller
button, but there aren't enough buttons usually. I usually end up just
mapping the N or 'Ron' button and enable cheats :)

**Comment by yoshisuga** [comment]
Can you upload the file using mega.nz or any other file sharing service and paste the link here? Sounds like a great change :)

**Comment by ChrisHoooo** [comment]
OK, please download it from here： https://pan.baidu.com/s/1jJjvEAy
If you have problem with downloading , let me know and I'll try another file sharing service.

My Modification may not be compliant with your code structure or guidelines, so just take a look and do it in you way. : )

**Comment by mrjschulte** [comment]
Took a look at getting the files @ChrisHoooo but I couldn't read the website to know what to click :(. Can you make a git repo with your changes or provide the files needed through another means?

**Comment by mrjschulte** [comment]
Hi @ChrisHoooo, is there still an interest to add support for this to MAME4iOS? If we don't hear back we'll close this issue out accordingly.
