### ISSUE TITLE
random lose all roms

### ISSUE THREAD

**Issue by italoc** [yoshisuga/MAME4iOS#135]
i'm using mame4ios on my apple TV 4 and works great, but randomically lose all rom and i need to reupload...

there is a solution?

**Comment by ToddLa** [comment]
As far as I know tvOS will periodically purge files to free up space.  As far as I know there is nothing we can do about that....

To make restoring ROMs easier, you can zip them all up into a single meta-zip and only copy over a single file. Select multiple zip files in Finder ctrl-click and select Compress Files....

**Comment by italoc** [comment]
> As far as I know tvOS will periodically purge files to free up space. As far as I know there is nothing we can do about that....
> 
> To make restoring ROMs easier, you can zip them all up into a single meta-zip and only copy over a single file. Select multiple zip files in Finder ctrl-click and select Compress Files....

There I a way to implement samba client and read roms from samba share?

**Comment by ToddLa** [comment]
There are many paths/options to a ROM syncing solution. (SMB being one of the last) bit nothing in this area is planned, at least for now. 

Try the zip-of-zips option, and maybe delete any large apps on TV so your ROMs don’t get purged as much

**Comment by ToddLa** [comment]
If we remove CHEAT.ZIP from the tvOS bundle, that will save 25MB.  We can explain in the help file how to import it, if you really want it.

**Comment by mrjschulte** [comment]
Nothing we can do besides the things we've already discussed and offered up as part of new ZIP functionality.
