### ISSUE TITLE
Latest build results in Apple Mach-O Linker Error?

### ISSUE THREAD

**Issue by beyondthetech** [yoshisuga/MAME4iOS#14]
I've been building all previous commits properly except for the latest one. Anyone know what changes could be causing this error?

> Undefined symbols for architecture x86_64:
  "_myosd_array_categories", referenced from:
      -[FilterOptionController init] in FilterOptionController.o
  "_netplay_read_data", referenced from:
      -[NetplayGameKit receiveData:fromPeer:inSession:context:] in NetplayGameKit.o
  "_netplay_warn_hangup", referenced from:
      -[NetplayGameKit teardownConnectionWithWarn] in NetplayGameKit.o
  "_netplay_init_handle", referenced from:
      -[NetplayGameKit connect:] in NetplayGameKit.o
  "_skt_netplay_init", referenced from:
      -[NetplayController startSocket] in NetplayController.o
      -[NetplayController joinSocket] in NetplayController.o
  "_netplay_get_handle", referenced from:
      -[NetplayController tableView:cellForRowAtIndexPath:] in NetplayController.o
      -[NetplayController tableView:didSelectRowAtIndexPath:] in NetplayController.o
      -[NetplayController setNetplayOptions] in NetplayController.o
      -[NetplayController startSocket] in NetplayController.o
      -[NetplayController joinSocket] in NetplayController.o
      -[NetplayController startGamekit] in NetplayController.o
      -[NetplayController joinGamekit] in NetplayController.o
      ...

**Comment by yoshisuga** [comment]
Hmm have you tried to rebuild the MAME library using `make`? I just tried rebuilding and it did build ok.

**Comment by beyondthetech** [comment]
I did it both with make and using the one prebuilt, same error.

**Comment by yoshisuga** [comment]
Oh! It looks like you're trying to build for the simulator since the
architecture is x86_64. If you set your target to be "Generic iOS Device"
or your device it should build. I haven't paid any attention to getting it
to work on the simulator but it involves building the MAME library for the
simulator as well. I'm sure its possible, but I haven't tried :)

**Comment by ck16** [comment]
Howdy!

I've just tried compiling the latest version from git and I'm receiving the following link errors:

Undefined symbols for architecture arm64:
  "_lightgun_y", referenced from:
      -[EmulatorController handleLightgunTouchesBegan:] in EmulatorController.o
  "_lightgun_x", referenced from:
      -[EmulatorController handleLightgunTouchesBegan:] in EmulatorController.o
  "_myosd_light_gun", referenced from:
      -[EmulatorController changeUI] in EmulatorController.o
      -[EmulatorController buildLandscape] in EmulatorController.o
      -[EmulatorController touchesBegan:withEvent:] in EmulatorController.o
      -[EmulatorController touchesController:withEvent:] in EmulatorController.o
      -[EmulatorController touchesEnded:withEvent:] in EmulatorController.o
     (maybe you meant: _prev_myosd_light_gun)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yoshisuga** [comment]
Hi @ck16 - it looks like you're building with an older MAME binary. I updated the link to the libmamearm64.a file in the README with the latest one:

https://mega.nz/#!GJZH3ShT!XVK53FgH5E8WuuSBD57rSwfidtQ2afxWQq9iaPXR4QE

Try downloading that one and then building.

**Comment by ck16** [comment]
Hi @yoshisuga, that worked thanks!

I also just compiled the libmamearm64.a file from source about an hour ago and that also worked too!

Thanks heaps!

**Comment by beyondthetech** [comment]
Yes, it looks like that was the issue that was causing my build to fail as well. Thank you for this update, I can finally play with this latest build.
