### ISSUE TITLE
version 2020.1 always black screen TVos

### ISSUE THREAD

**Issue by italoc** [yoshisuga/MAME4iOS#141]
i try to use new version 2020.1 and i can't see ROMS, always black screen i can enter in SETTING end start web server, upload roms like older version but i cant see roms

any ideas?

**Comment by mrjschulte** [comment]
Not seeing this here. Perhaps grab the latest 2020.2 release and do a new build and dist it to your appleTV?

**Comment by italoc** [comment]
same thing with latest 2020.2 black screen, but the game are present, if i press same random key some game start

**Comment by ToddLa** [comment]
What version of tvOS? 
Are you building or side loading IPA?
What ROMs are you installing? 
Copying to root, or directly into roms folder?

**Comment by italoc** [comment]
tvOS 13.4
Build from source
0.139u1 Roms version
Directly into roms forlder (via web interface)

**Comment by ToddLa** [comment]
You might have something weird in a settings file...

Try this...
Go to Xcode / Window / Devices and Simulators
Select MAME4tvOS in the Installed Applications list.
Click on gear icon and select Download Container...
Then delete the app from TV and start over fresh.

If you dont have the problem fresh, then we should look at the container and see what is causing issue.

If you do still have the problem, let me know.

**Comment by ToddLa** [comment]
I just deleted app and did a fresh run, copied a few ROMs directly into roms folder (not the root) and am running fine.

What do you mean when you said, if you hit a key....

**Comment by italoc** [comment]
> You might have something weird in a settings file...
> 
> Try this...
> Go to Xcode / Window / Devices and Simulators
> Select MAME4tvOS in the Installed Applications list.
> Click on gear icon and select Download Container...
> Then delete the app from TV and start over fresh.
> 
> If you dont have the problem fresh, then we should look at the container and see what is causing issue.
> 
> If you do still have the problem, let me know.

do it but nothing change always black screen
the container is aobut 500MB where i can send?

p.s:old version with old graphics works correctly

**Comment by italoc** [comment]
> What do you mean when you said, if you hit a key....

when i see black screen i press some key random, and the game start correctly, but i can choose, it is always black

**Comment by rslkr** [comment]
I had the same issue before for iOS. Uploaded the roms into the roms folder, black screen! 
No MAME menu or game list only joystick and buttons. Press randomly any button and a game starts. 
I don't know what was it causing the problem. I use virtual machine(Hackintosh) 
I just decided start over, upgrade the Catalina OS, Xcode and a new MAME binary.
Thank you ToddLa, I really like the front end (Preview of the games) feature, you also kept the MAME menu. thumbs up 👍

**Comment by ToddLa** [comment]
> > You might have something weird in a settings file...
> 
> > 
> 
> > Try this...
> 
> > Go to Xcode / Window / Devices and Simulators
> 
> > Select MAME4tvOS in the Installed Applications list.
> 
> > Click on gear icon and select Download Container...
> 
> > Then delete the app from TV and start over fresh.
> 
> > 
> 
> > If you dont have the problem fresh, then we should look at the container and see what is causing issue.
> 
> > 
> 
> > If you do still have the problem, let me know.
> 
> 
> 
> do it but nothing change always black screen
> 
> the container is aobut 500MB where i can send?
> 
> 
> 
> p.s:old version with old graphics works correctly

If running fresh also has problem, then we don’t need to see container.

**Comment by belltechdave** [comment]
> Not seeing this here. Perhaps grab the latest 2020.2 release and do a new build and dist it to your appleTV?

Where is the 2020.2 copy of the ipa file available to download from as I’m not seeing it anywhere in the GitHub repo?

**Comment by ToddLa** [comment]
What are the exact ROMs you are copying to the roms folder??
Can you zip them up and send them to me?

**Comment by italoc** [comment]
> What are the exact ROMs you are copying to the roms folder??
> Can you zip them up and send them to me?

0.139u1 Roms version

where can i send you? email?

**Comment by Tomasz-Kluczkowski** [comment]
I have the same problem on iphone11.
Roms were put in using the built in webserver into roms folder.

Will try rebuilding and anything else in this thread and report back see if it helped...

**Comment by rslkr** [comment]
**Tomasz-Kluczkowski**
First, I'm not an expert but this might be helpful. It solved my problem.
Downloaded the latest Mame4ios
'Terminal' requires permission by Catalina while it creates the MAME binary properly.
I gave permission to ''Developer Tools, Full Disk Access and Files and Folders'' 
''libmamearm64.a'' must be in the MAME4iOS-master root folder.
I didn't have any problem with Xcode it built just fine.
![Xcode](https://user-images.githubusercontent.com/46307397/78356585-8c576400-75fb-11ea-90e0-cc23d682619a.PNG)

**Comment by ToddLa** [comment]
> 0.139u1 Roms version
> where can i send you? email?

How many ROMs do you copy over? 

If it is just a few, zip them up, put on Dropbox and put share link in this issue.

It is important to send the exact roms when you get the blacksceen, my theory is mame is throwing a hissy fit on startup for some reason....

Also you only put files in the roms folder?

**Comment by italoc** [comment]
5, 10, 100 Rom always same problem, rom is loaded in roms folder via web interface

**Comment by ToddLa** [comment]
Good, send me the 5 roms that cause the problem.
And exact repro steps.

-Todd

On Apr 3, 2020, at 10:21 AM, italoc <notifications@github.com> wrote:

﻿

5, 10, 100 Rom always same problem, rom is loaded in roms folder via web interface

**Comment by italoc** [comment]
> **Tomasz-Kluczkowski**
> First, I'm not an expert but this might be helpful. It solved my problem.
> Downloaded the latest Mame4ios
> 'Terminal' requires permission by Catalina while it creates the MAME binary properly.
> I gave permission to ''Developer Tools, Full Disk Access and Files and Folders''
> ''libmamearm64.a'' must be in the MAME4iOS-master root folder.
> I didn't have any problem with Xcode it built just fine.
> ![Xcode](https://user-images.githubusercontent.com/46307397/78356585-8c576400-75fb-11ea-90e0-cc23d682619a.PNG)

Thank you, now owrks great, after athorize terminal works perfectly.

great works, thank you for support
