### ISSUE TITLE
Does multiscreen support exist (e.g.: Darius II)?

### ISSUE THREAD

**Issue by cjchand** [yoshisuga/MAME4iOS#142]
Looking to see if there is support for multiscreen/monitor games like Darius II, 6-player X-Men, etc.

Darius II works as expected on the iOS8-era Gridlee that was in the App Store, so presuming there's a config or something that can light this up?

Thanks in advance!

**Comment by yoshisuga** [comment]
Yes, multi screen games like Darius, Ninja Warriors work, you need to go to the MAME menu while in-game and choose the "Triple Side-by-Side" option to see the entire screen:

![IMG_D503A01200D6-1](https://user-images.githubusercontent.com/564774/77857176-b641fe00-7197-11ea-87ae-1332fb3d219d.jpeg)

**Comment by cjchand** [comment]
I swore I tried pulling up the MAME menu and it didn't work. Did this time though. Will chalk that up to user error.

After making this change - and selecting "Keep Aspect Ratio" from the global settings - it worked perfectly.

Many thanks again!
