### ISSUE TITLE
Turbo Mode Toggle Issue

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#146]
Hi ToddLa, Turbo mode toggle for buttons doesn't work instead they affect on joystick (iPhone)
I try remap the buttons by MAME Input but doesn't help!

Also while I try to add the game to ''Favorite'' I accidentally deleted some games!(On Frontend Mode) I think it'd be better if it asks permission before deleting.Another idea select/deselect option like iphone photo gallery.

Speaking about the Favorite, when I add the games to Favorite, I think it would be nice if the color of game's name turns into ''yellow'' instead of white or ''a little red heart'' on the corner of game's image. So we'd know that we already added that game while scrolling down/up.

Last one: The Netplay allows to connect and play up to 2 people only but some other games in MAME have up to 4 players. Cadillac and Dinosaurs 3 players, Sunset Riders 2 and 4 players.

By the way tapping on MAME Logo and it scrolls up that's nice touch.
Thank you for your hard work.

**Comment by ToddLa** [comment]
As far a I can tell turbo mode only works for a game controller, not the on-screen controller.

Yes we should probably confirm before we delete!

I have no experience with the netplay code, I just try not to break it. I don’t know if it is designed to handle more than two players or not.

Yes thought about some way to distinguish a fav game, but not critical.

PS this should have been multiple issues. (Don’t do it now, just next time)

**Comment by rslkr** [comment]
Thanks for reply.

> As far a I can tell turbo mode only works for a game controller, not the on-screen controller.

Well It was working before properly on the screen controller (A few months back).
Maybe some additional codes in ''OptionsController.h or Options.h'' cause a problem.
Anyway that was a good feature. I hope that Yoshisuga can fix it.

> I have no experience with the netplay code, I just try not to break it. I don’t know if it is designed to handle more than two players or not.

I understand.

Those are my review not the real issues. The App. still the best for me. But everytime you guys add something I became more obsessed with it and I believe that every minor detail makes it perfect.

**Comment by ToddLa** [comment]
yup you are right, turbo was totally broken, luckily it was just a cut-paste error. totally fixed now.

**Comment by rslkr** [comment]
ToddLa, You are really good at codding I mean it.
I wish that I could be as you are and help this project but I can't.

Thank you for fixing the 'Turbo' and added the 'confirm to Delete'


> add a "Reset Game" option to delete all "state" files (key remappings…

You read my mind I was about to ask something like this long time ago and you did it (Reset Game).Thanks.

Don't you think, adding this option on  'A Game Mode' as well and it would be more benefit.
So no need to exit the game.

There's a 'Soft Reset' in Config Menu(which is good to have it) but this one is the next level.
I'm just saying you're the expert here. Maybe there is a reason you didn't want it.

BTW I downloaded your repo and 'Settings' on the Dark Mode

**Comment by mrjschulte** [comment]
This is a wip and we're going through some last minute contextual updates to tweak the experience. Hope to push this PR soon and merge it in. Stay tuned!

**Comment by rslkr** [comment]
@mrjschulte 
Ok. I understand thanks.
I've got few more things to mention.
Should I write it here or don't even bother to ask?
'coz I think asking too much already!

**Comment by mrjschulte** [comment]
Please ask away!

**Comment by rslkr** [comment]
Okay then let's start with silly one.

1. This is NOT a request it's just an idea. While I was struggling with black screen issue I thought the Artworks were missing. It turned out nothing to do with it! If I'm wrong correct me the only way to get that from the 'roms' (somehow ToddLa managed that and made it possible) 
If so, how about to play the game's intro?  (This feature available on Pandora Box Console)
I mean not all of them same time on the screen. Only, the one selected. It appears ''blue'' now.
I know it won't be easy to make possible and probably causes a lots of problem.

2- This is a tiny issue. 
The blue gear icon for settings is too small, for fingers (iPhone). And the icon itself.
 Sometimes I'm struggling tap on it and touching on the search bar!

3-This is my personal request. I don't think no one else concern it except me.
It's about the joystick. I think it is outdated and needs to upgrade, only for the movements animation. I used to play this game (https://www.youtube.com/watch?v=adoV5YKKXKU](url)
Not working anymore 32 bit app.
it has a pretty good smooth animation with full circle movements. The current one still ok it moves 8 ways but in my opinion this one much better especially for fighting.
I'm ok with the buttons.
I know I should buy a real joystick but the reason I love this app. it's easy to carry everywhere.

Sorry for the long comment.Thanks.

**Comment by ToddLa** [comment]
Have you tried, selecting AnalogStick from Settings > Game Input?

Yes we know the settings icon is too small, hard to select, hard to discover, and if you look close it is ugly too. Throwing around a few ideas to fix.

**Comment by rslkr** [comment]
@ToddLa Yes, That one similar to Analog Stick.
I wish you could have the experience of playing the game to see it yourself what I meant.
Of course they are video game company and probably, they have a very special driver and script for it.
Anyway it's not a big deal. Maybe you're right ''Not to break it!''
I don't want to be a trouble maker here and give you headaches.
It's just the way I want this app. Like I said minor detail.
OK There, I said it.
Thank you so much for everything.
