### ISSUE TITLE
UI improvement request: allow cancelling “Load/Save State”

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [yoshisuga/MAME4iOS#150]
Hi,

Love this project :). Thank you so much. 
My request is to treat the “Save State” and “Load State” popups as a modal and allow tapping the screen on the outside of its box to cancel the option.

Currently if “Save/Load State” is used by accident one has to quit the entire app to prevent overriding the state that one cares no to override.

Best would be to create a new behaviour of the popup component to cancel on tapping outside of it by default I guess?

Cheers,

Tom

**Comment by ToddLa** [comment]
Things are slightly tricky here. Adding a cancel button would be trivial, and would work great for the on-screen controlls.

But for a game controller we use the fact that Ⓐ is mapped to the alert default and Ⓑ is mapped to alert cancel.

So
MENU+Ⓐ Ⓐ will save state 1
MENU+Ⓐ Ⓑ will save state 2

MENU+Ⓨ Ⓐ will restore state 1
MENU+Ⓨ Ⓑ will restore state 2

**Comment by ToddLa** [comment]
We could have a third button “Nevermind, don’t save/restore” that is not mapped to a controller button...

**Comment by Tomasz-Kluczkowski** [comment]
To me it makes sense to have a button for cancelling these actions. The initial implementation could indeed be just for touch-screen use as you suggest.

If it is trivial to stick in, pretty please consider it for the next release :).

If I only had any skill in c/c++ I would love to help but currently no time to study low level language unfortunately.

**Comment by ToddLa** [comment]
PR #149 has a fix for this....

**Comment by ToddLa** [comment]
MENU+Ⓐ Ⓧ will save state 1 MENU+Ⓐ Ⓨ will save state 2

MENU+Ⓨ Ⓧ will restore state 1 MENU+Ⓨ Ⓨ will restore state 2

**Comment by ToddLa** [comment]
Turn out....

MENU+Ⓐ Ⓐ will also save state 1
MENU+Ⓨ Ⓐ will also restore state 1 
 Because Ⓐ will select the default button (first one)

**Comment by mrjschulte** [comment]
This has now been merged, take it for a spin and let us know. We'll close this Issue in the near future but will leave it open for your feedback. 

Thanks!

**Comment by Tomasz-Kluczkowski** [comment]
I am going to rebuild with this change this evening. Many thx for such a rapid fix!

**Comment by Tomasz-Kluczkowski** [comment]
Excellent improvement ! All working as intended.
Tried multiple load/cancel and save/cancel events as well as load/save - all ok.

Many thx!

**Comment by mrjschulte** [comment]
Closing, thanks all!
