### ISSUE TITLE
SELECT+START should open MAME4iOS menu.

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#157]
Currently SELECT+START opens the MAME menu

I propose SELECT+START should open the MAME4iOS menu, and then the user can select MAME menu if they really want that.

This only effects iCade, 8bitDo, and other keyboard based controllers.  MENU+B on a game controller will still summon the MAME menu and just plain MENU will summon the MAME4iOS menu.

**Comment by mrjschulte** [comment]
Agreed, make it so!

**Comment by ToddLa** [comment]
PR #177

**Comment by mrjschulte** [comment]
I'll review and then merge accordingly later tonight.
