### ISSUE TITLE
mame4ios 32bit build fails with linker failure: library not found for -lcrt1.3.1.o

### ISSUE THREAD

**Issue by i-sledge** [yoshisuga/MAME4iOS#16]
I´was struggeling to get mame4ios 32bit running. I got always the failure: library not found for -lcrt1.3.1.o

Problem solved by setting deployment target to 6.0 ! 

![xcodescreenshot](https://user-images.githubusercontent.com/32581648/38151629-55b5ce8a-3464-11e8-8c28-8a3c55613271.png)

Now everything works fine !! 
Thanks for the project !

**Comment by yoshisuga** [comment]
Ah, I think there's an issue of crt1.3.1.o not being present in newer versions of the iOS SDK, and that you can either symlink them or copy it over from a previous xcode install.

Glad you got it to work! :)
