### ISSUE TITLE
Button layouts on iPad vs iPhone

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#160]
Why are the button layouts different?
![image](https://user-images.githubusercontent.com/4494698/78977610-3be57800-7acd-11ea-9625-c80c54f1d3ed.jpeg)

![image](https://user-images.githubusercontent.com/4494698/78977627-456ee000-7acd-11ea-824e-0cd6187e6b99.jpeg)

**Comment by ToddLa** [comment]
Also why are the L R buttons not right below the command button row, ie right below START COIN buttons?

**Comment by mrjschulte** [comment]
No.Idea. I've got nothing.

**Comment by ToddLa** [comment]
Now what layout is the “right” one?

**Comment by mrjschulte** [comment]
I'd lean towards having A + B on the lower row next to one another with X + Y on the above row.

**Comment by ToddLa** [comment]
![](https://media.discordapp.net/attachments/682362941693231135/698609225416310845/image0.jpg)

**Comment by ToddLa** [comment]
so looks like the iPad layouts need changed to match.

**Comment by mrjschulte** [comment]
Yes, let's do it. Apple MFI and 8bit-do also map this way.

**Comment by ToddLa** [comment]
PR #176 us a fix for this, I went through all the devices and made the layouts match a consistent 🅐 🅑 🅧 🅨 layout.
