### ISSUE TITLE
New Button Layout.

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#165]
With the iPhoneSE (SE2, 9, ...) imminent, and rumors of new screen sizes in the fall.  You know what that means, MAME4iOS on screen buttons are gonna break again.

Changing the button layouts is a PITA, you have to update 5 txt files for each device, and test in portrait/landscape full screen/non full screen. Currently the buttons in one of the iPad layout is not aligned, but it is not worth trying to fix it.

What we should do is scrap all the code, and txt file resources and replace it with dynamic layout that will adapt to any screen size or device. 

The code will just simple code that manually lays out the stick and buttons based on the screen size, etc. it will use (gasp) AutoLayout, or a UIStackView.  All it has to do is support a single layout for portrait vs landscape, fullsceen vs no-full screen. With maybe a few tweaks for  extra large (iPad) or extra small (iPhone5ish) devices.

## What we loose doing this

* custom button layouts.  Does anyone really use these, except to fix broken layouts when a new screen size comes out??
* per-device background images. We will need to use a generic black-brushed metal image that looks good when tiled to any size.

## What we gain doing this.

* new screen sizes wont make the developers play roshambo to decide who gets to do a new layout.
* button layout, ABYX, will match between iPhone and iPad. See issue #160
* better to adapt to dynamic screen size, ie maybe split view on iPad, or a Catalyst macOS app.
* ability to easily add/move the *hidden* buttons (A+B, A+X, etc) see #159
* ability to easily add a L1 and R1 to the iPhone layouts.
* general warm and fuzzy feeling being able to delete all that code.
* ability to easily add back in skin support, skins would not be able to change the button locations, but would be able to change the button/stick images and the background tiled image.  We can at least do a light, dark, and retro color scheme.
* consistent placing for SELECT, START, MENU, EXIT. question, do we need a separate EXIT button? Exit is a choice on the menu???

## things to make sure we support
* setting for extra large buttons, again do people use this?
* make sure the hidden buttons are placed correctly. 
* maybe adding L2,R2, L3,R3 buttons on the iPad.

**Comment by rslkr** [comment]
Hello ToddLa, 

> Changing the button layouts is a PITA, you have to update 5 txt files for each device, and test in portrait/landscape full screen/non full screen.

This seems a lot of work.There must be a better solution but there isn't I think.
This problem will repeat itself every year when the new phones release.You're absolutely right.

> ability to easily add/move the hidden buttons (A+B, A+X, etc) see #159

Thank you for considering my request.

> ability to easily add back in skin support, skins would not be able to change the button locations, but would be able to change the button/stick images and the background tiled image. We can at least do a light, dark, and retro color scheme.

I requested something like this before see #80 All I wanna see few more color options for button/j.stick ''White, Green, Blue, Yellow'' and I thought that would be easy to change by slider.
You know this is just for appearances, better looking buttons/j.stick.

> setting for extra large buttons, again do people use this?

I don't use for iPhones but maybe it's good for iPad.Let see other user's thoughts

> make sure the hidden buttons are placed correctly.

Yes please.

> custom button layouts. Does anyone really use these, except to fix broken layouts when a new screen size comes out??

Well If you are planing to remove the ''TOUCH LAYOUT'' option in settings this is not a good news for me.
Please see #159

**Comment by ToddLa** [comment]
YES I am  talking about removing TOUCH LAYOUT!

The new layout would have fixed positions, including insisible A+B buttons.

**Comment by ToddLa** [comment]
Who said MAME UI will be removed?? I don’t see it going away, as long as we need the MAME MENU to do controller mapping and video options, etc. it is staying.

**Comment by rslkr** [comment]
I saw it here #105

**Comment by ToddLa** [comment]
> YES I am  talking about removing TOUCH LAYOUT!
> 
> The new layout would have fixed positions, including insisible A+B buttons. 

TOUCH LAYOUT assumes a bunch of fixed button locations, and it is not per-device or even per-game it is global. And does not scale. If you update to a new phone, all your hard coded button positions move over and look like shit, until you remember you have a custom layout and go into settings and reset it

**Comment by rslkr** [comment]
> TOUCH LAYOUT assumes a bunch of fixed button locations, and it is not per-device or even per-game it is global. And does not scale. If you update to a new phone, all your hard coded button positions move over and look like shit, until you remember you have a custom layout and go into settings and reset it

Yes I remembered that issue  when I got Iphonex

**Comment by ToddLa** [comment]
> I saw it here #105 
> 
> actually you
> 
> 
> 
> > Nothing, just a retro feel.
> 
> So an option is to just take it all out and only cover the GUI UI.
> 
> The Y key on a joystick still brings up a menu where you can add to favorites.ini and delete game files.
> 
> We should turn that off?? Or mention it in the help?
> 
> NOTE I am only talking about the root/main MAME UI, it does nothing we don’t do.
> 
> BUT the MAME config menu can do tons of stuff, like key remapping etc

There are two things, the MAMEUI, and the MAME MENU.  We really don’t need the MAMEUI, our GUI menu does everything it does and more. We are talking about removing parts of the help file that talk about the MAMEUI and remove/rewrite it to talk about the native iOS UI only (or at least first)

The MAME MENU, aka MAME CONFIG MENU is critical and is here to stay.

**Comment by rslkr** [comment]
Yes I totally agree with you.I am really happy with new GUI. Again thank you for new GUI this is good on touch screen. 👍

**Comment by rslkr** [comment]
> ability to easily add a L1 and R1 to the iPhone layouts.

Are you going to add these **L1** and **R1** into the Settings>Input Option>Fullscreen Buttons
Number Of Buttons?
Could you please can you make **R1** 5 Buttons and **L1** 6 Buttons(or All Buttons)
Probably I'm gonna stick with 5 Buttons. I can't use **L1** because of the new layout position 
its top of the joystick. It's better for me to turn it off.
Currently We can select ''Auto, 0, 1, 2, 3, 4 and All Buttons''

**Comment by ToddLa** [comment]
Yes L1 and R1 would be buttons 5 and 6. 

Not sure where L1 should go on iPhone, why do you hate it above the dpad so much? Currently on iPad they are next to ABYX

**Comment by rslkr** [comment]
Sorry I guess I'm so old school. I grew up with these arcade machine.
Right hand for j.stick left hand for buttons.
I had dpad before Maybe its time I should buy another one see how it goes.
I got these now https://newwavetoys.com/products/street-fighter-ii-mini-fight-stick](url)
Please don't laugh and don't say ''hey its for ants'' :)
Unfortunately no BT. Im still trying to figure out how can I add BT inside.Maybe I should buy impulse for this.

**Comment by ToddLa** [comment]
![image](https://user-images.githubusercontent.com/4494698/79341070-134fea80-7ee0-11ea-8bee-4c90a9e54a86.jpeg)

Thinking layout like this, except maybe no EXIT button

**Comment by rslkr** [comment]
Oh ok this is portrait mode Ipad?
Iphone?

**Comment by ToddLa** [comment]
Another option, if we must keep custom layout, is totally Change the data, don’t store full rects in pixels/points. Store the center position in device independent coordinates (0..1)

By storing only the center point, and not a rect, the button won’t scale strangely

**Comment by ToddLa** [comment]
![Uploading 79351056...]()

**Comment by rslkr** [comment]
Remember this:

> new screen sizes wont make the developers play roshambo to decide who gets to do a new layout.

And **please** don't do it just for me, whatever is your plan to solve this dilemma, it should make everyone happy.
PS: All of my request not really necessary nor urgent.

**Comment by ToddLa** [comment]
iPhoneSE announced today, screen sizes same as 6,7,8.

**Comment by ToddLa** [comment]
because iPhoneSE does not have a new screen size, this issue won't come up (critical) til the fall (and maybe not even then, but most people expect a new screen size....)

we still should change the iPad layout files to match the ABYX layout of the iPhone.

**Comment by rslkr** [comment]
Not bad for lower end iPhone.I want full screen(notchless) but I know that's not gonna happen.
And maybe your first plan is the good idea.
I don't hate dpad All I meant  how you guys can use **L1** b'coz I can't on landscape mode

**Comment by mrjschulte** [comment]
Lets unify the layout first, mapping iPad back to iPhone and then take it from there.

**Comment by rslkr** [comment]
@ToddLa 
> consistent placing for SELECT, START, MENU, EXIT. question, do we need a separate EXIT button? Exit is a choice on the menu???

You might wanna keep the ''COIN(SELECT) and the START Buttons''
They both activate the ''Player2, Player3 and Player4'' by using the joystick.
The EXIT button used to cancel Save/Load State as well but
Thanks to @Tomasz-Kluczkowski and his request 
Now pop-up menu does all jobs.

**Comment by ToddLa** [comment]
Of course we need to keep SELECT and COIN!

EXIT could be removed because an exit option is in the in-game menu. 

but we would only remove EXIT in cases where we are right on space, ie a iPhone5 size display in portrait.

**Comment by rslkr** [comment]
I'm sorry for keep writing here but I think I have to mention this.
> EXIT could be removed because an exit option is in the in-game menu.

Now Pop-up Menu is more functional no doubt about it.
But the EXIT button still good for MAME MENU(Config) I mean it is more quick and practical to exit (<BACK)
These 4 buttons don't bother me at all.The decision up to Developers (you sir).
'Settings' looks better with Dark Mode, nice and neat.Also good for previous iOS version.
I realize that every time you update the App. it comes with bugs fixed.This is one of them:
Before When I held on the any game on the screen, the pop-up wasn't fitting on the screen.
Now it fits properly.No matter where you hold on screen. 👍 
A lot good stuff and useful feature on this App. now. Thank you all.

**Comment by ToddLa** [comment]
Yes EXIT is very useful for that!! I have been playing around in MAME MENU a lot lately. 

FYI don’t re-map exit, or out app totally breaks! A good use for the new reset option in settings.

**Comment by ToddLa** [comment]
I am looking at making 🅑 also work as exit when in menu too.

**Comment by rslkr** [comment]
> I am looking at making 🅑 also work as exit when in menu too.

How will this work while we playing the game? Can you elaborate please?
🅑 ?

**Comment by ToddLa** [comment]
MAME does not like 🅑 being mapped to UI_CANCEL so never mind...

**Comment by ToddLa** [comment]
I made  🅑 exit the mame menu, it feels nice not to scroll and choose Exit. Or touch the screen!!

**Comment by mrjschulte** [comment]
This works and has gone in.
