### ISSUE TITLE
Mame4ios HMDI out

### ISSUE THREAD

**Issue by HowieT23** [yoshisuga/MAME4iOS#167]
Hello I’m using the Mame4ios app on my iPad Pro and have it hooked up to my monitor using a usb hub with hdmi out the first few times I didn’t have an issue but every time I hook it up a message appears I’ve tried each resolution and the picture is off center for all of them once I select it anybody else come across this?
![image](https://user-images.githubusercontent.com/63940786/79678714-4b02af00-81cc-11ea-9e29-cf47d5938a28.jpg)

**Comment by ToddLa** [comment]
Define off-center, let’s see a picture of that, best choice is native res, 1080p I am guessing

**Comment by HowieT23** [comment]
This is what it looks like the bottom selection is 1920x1080 that’s 1080p right?
![BD5C1829-C379-4A9B-ADA2-19538A52AC43](https://user-images.githubusercontent.com/63940786/79693677-13cae700-823a-11ea-8a3f-2f1ef5272f23.jpeg)
![A7EF24DA-33FF-4D3F-A902-36EFD4230CA9](https://user-images.githubusercontent.com/63940786/79693678-16c5d780-823a-11ea-921f-2f91d0165603.jpeg)

**Comment by ToddLa** [comment]
What MAME4iOS version?

**Comment by ToddLa** [comment]
This looks like an old version, you should not see the DOS MAME UI anymore (unless you specifily asked for it)

**Comment by HowieT23** [comment]
It’s version 1.6 and I hooked it up to my 55 in Sony tv and the last setting worked but on my monitor I can’t find one of these to fit properly on the screen

**Comment by ToddLa** [comment]
The latest version is 2020.5, and this is all fixed.

**Comment by mrjschulte** [comment]
@HowieT23 , have you been able to grab the latest version? @ToddLa was able to put some fixes in for external displays a while ago.

**Comment by HowieT23** [comment]
Hey I just downloaded it on my iPhone I’m gonna do the same on my iPad I hope I can transfer all of my roms and save states easily 😬 Thanks for the response

**Comment by HowieT23** [comment]
Ok I finally have the new app downloaded with the roms I moved them to the new app version where do I find my save states and button config files?

**Comment by HowieT23** [comment]
I figured out where the files where and copied and pasted them using Filza 
I should be good to go one last question the controller seems accelerated in the main menu the games play as they should but the main menu moves really fast

**Comment by mrjschulte** [comment]
I don't think we're seeing this here, can you share a quick movie showing the issue? Or better yet, open up a new issue for easier tracking and so we can close this one out?

**Comment by HowieT23** [comment]
You can close this out I’ll make a new one
Thanks

**Comment by mrjschulte** [comment]
closing
