### ISSUE TITLE
drag and drop roms?

### ISSUE THREAD

**Issue by fancyham** [yoshisuga/MAME4iOS#17]
It would be wonderful if dragging a ROM onto the app would import it! (same with CHDs, if those work)

Likewise, an action sheet import option would be nice, too.  Perhaps easier than drag and drop.

A super-stretch would be to expose the documents folder to the Files app as a document provider, allowing manual management of files in that app.

**Comment by yoshisuga** [comment]
I exposed the documents folder to the Files app (commit  9a99449), as it's a lot easier to do :)

**Comment by fancyham** [comment]
Yesssss
