### ISSUE TITLE
iCade controller w/ tvOS

### ISSUE THREAD

**Issue by Jbossalini** [yoshisuga/MAME4iOS#170]
Should an iCade Core controller work out of the box with the latest tvOS `master` branch?  I see there are no `external controller` options exposed for that target, but when I run with a breakpoint on `switch (key)` in `iCadeView.m` it is seeing keyboard inputs when I use the controller with my Apple TV, though it is not triggering any actions in the UI.  I'm compiling myself from `master` as of 4/18.  Thanks!

**Comment by ToddLa** [comment]
the tvOS code has the iCade code in it, but the Settings UI does not have a way to enable it!

Settings > Input Options > External Controller is how you get to it in the iOS app.

tvOS will work out of the box with a USB/Bluetooth keyboard.

an iCade device needs to be specifically enabled because it sends separate/weird key up/down events.

**Comment by ToddLa** [comment]
if you want to do a build that will default to iCade on tvOS...

change this line, in EmulatorController.m.....

    g_pref_ext_control_type = [op controltype];


with this....
```
    g_pref_ext_control_type = [op controltype];
#if TARGET_OS_TV
    g_pref_ext_control_type = EXT_CONTROL_ICADE; // **HACK** default to iCade on tvOS
#endif
```

**Comment by ToddLa** [comment]
Turns out that hack, WONT work dont even try it. tvOS is not handling the keyboard same as iOS.

...but I did a fix Pull Request #174 gives iCade support and UI to tvOS.....

**Comment by Jbossalini** [comment]
Thanks!  I will give that a try tonight and report back.

**Comment by Jbossalini** [comment]
@ToddLa works great!  Thanks a bunch for the quick turnaround on this one!

**Comment by ToddLa** [comment]
Close!
