### ISSUE TITLE
Hide Notch

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#172]
Sorry for asking weird request. I'm not a big fan of notch.
This should've been done by now (Apple) and it seems they will not add this option in settings.

Google has this and I saw a Jailbreak iOS tweak.
They won't remove this notch until this under display camera/sensors gets worked successfully!!!

I play the games fullscreen (landscape mode) with ''Keep Aspect Ratio'' off
I know its sound funny way to play game :)
And the notch covers some part of the game.
All I wanna see to keep the whole game in the rectangle screen.Like notchless iPhone.

Can you add an option in settings please.If its possible and easy.If not we can close this issue.
I know you all busy these days. This is not a urgent request.
Thanks.

**Comment by ToddLa** [comment]
Buy an iPhoneSE, it does not have a notch.

**Comment by ToddLa** [comment]
This sounds like a bug where we dont honor the safe area in landscape fullsceen.

**Comment by rslkr** [comment]
Thank you so much @ToddLa you are such a generous, helpful person.
You could've ignore this, but you didn't. You fixed it straightaway.
The whole day I feel regretted and stressed. **Why I did ask!!!**
Now I'm so happy.
Unbelievable this little code  #175 solved this issue!!!
Now I can wait for iPhone12  :)
Why the bloody Apple not doing this!!!
Another tick on my wishlist. Done. 👍 

![1f266817-ddc7-40cc-8f8a-6c26c30bc311](https://user-images.githubusercontent.com/46307397/79964120-99b29080-84cd-11ea-80ed-03eba1dd5fc9.jpg)

**Comment by rslkr** [comment]
Thank you.
