### ISSUE TITLE
Enabling MAME artwork appears to break double-buffering

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#179]
Enabling MAME artwork appears to be breaking double-buffer support in the MAME4iOS. Needs some investigation.

**Comment by ToddLa** [comment]
By *break* to you mean total visual fail? Skipping every other frame? Or it “feels slow”?

i.e. is it immediately apparent it is broken, or you gotta “look close”

**Comment by mrjschulte** [comment]
You may have to look close, and at the highest rendering resolution (currently) of 1024x768. 
Side scrolling shooters are a good "tell".

**Comment by ToddLa** [comment]
The dbl buffering code is currently doing a memcpy every other frame, or something, so I dont think they know what dbl buffering means.  Should be easy to remove memcpy with pointer swaps. 

At low res the memcpy wont be noticeable, but maybe at 1080p or higher it is a problem.

Again investigate.....

**Comment by mrjschulte** [comment]
The tearing when the "Double buffering" strategy fails is pretty visible at a resolution of 1024x768. Just take a game that does a lot of "flashy" things such as the attract mode on Marvel Superheroes vs Streetfighter and see the tearing.

**Comment by mrjschulte** [comment]
New PR addresses this. closed.
