### ISSUE TITLE
Add a means to delete the artwork separately from other items

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#180]
In some cases you will want to delete the artwork.zip for a game without deleting the entire title. 

Currently this can not be done as "Delete Settings" does not delete the related artwork.zip, and it really shouldn't. 

We need a new delete option added to remove the associated artwork.zip for a title, if present.

**Comment by ToddLa** [comment]
We should only have two options Delete all Settings, and delete every thing. If we go down the let’s delete this, let’s delete that, it won’t stop. 

You can always go in via WebSrver or Files.app and micromanage all you want.....

**Comment by ToddLa** [comment]
![image](https://user-images.githubusercontent.com/4494698/80294871-5866ee80-8722-11ea-99a6-8894a2ee2a52.jpeg)

**Comment by ToddLa** [comment]
Modeling after iPhone Reset...

We can just delete artwork when deleting settings

**Comment by ToddLa** [comment]
There are two delete options....
1. Delete Everything
2. Delete Everything, except ROMSET

What we call them can change, but currently
1. Delete Settings
2. Delete Everything

**Comment by mrjschulte** [comment]
merged.
