### ISSUE TITLE
Support MAME Artwork natively???

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#184]
Look into support the MAME Artwork concept natively in a future rendering stack update. 

This would need to include for reading MAME .lay files and replicate the various use cases. 
What else?

**Comment by ToddLa** [comment]
No this sounds crazy, and would make updating to a new MAME core harder. 

Should just attempt to detect bezel and adapt our effects.

**Comment by ToddLa** [comment]
It looks real easy to detect the game/screen rect from the LAY file so we can adapt our overlay effects.

**Comment by ToddLa** [comment]
Also need to investigate widescreen artwork

**Comment by mrjschulte** [comment]
Do we know of any games that use this?

**Comment by ToddLa** [comment]
Yes! I found a bunch [here](https://mrdo.mameworld.info/widescreen.php) I am using Asteroids and Defender as test cases....

**Comment by ToddLa** [comment]
Most Cocktail LAYouts and some games have multiple screens, need to at least be aware of this (and not crash or get confused)

**Comment by ToddLa** [comment]
All fixed in PR #204, Artwork looks awesome, does the right thing (effect wise) for cocktail and multi screen layouts, and by default shows artwork in hires.

**Comment by mrjschulte** [comment]
closing!
