### ISSUE TITLE
Remove cheats.zip from being included by default and save 20MB?

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#189]
Currently we include cheats.zip in our default .ipa thereby bloating the file size by 20MB. 

With the newly added support for adding in external history.dat and mameinfo.dat files as zips, we now have a workflow paradigm that will allow users to add in external files such as those, including cheats.zip saving us from having to have it added in as a default for everyone from the get-go.

Do we want to go and remove cheats.zip and reclaim that 20MB?

**Comment by ToddLa** [comment]
CHEAT.ZIP is 25MB!
New HISTORY.DAT is 3MB
So we are net down 22MB

**Comment by ToddLa** [comment]
The compressed version of CHEAT.zip is only 1MB

So we should do one of two things
* remove CHEAT.ZIP altogether and update help file to explain how to download from [here](http://cheat.retrogames.com/download/cheat0139.zip)
* replace the 25MB version in our bundle with the 1MB version and expand on first launch.

**Comment by ToddLa** [comment]
PR #190 does this.

.app size is now 64MB

**Comment by mrjschulte** [comment]
Sounds like a plan!

**Comment by mrjschulte** [comment]
@yoshisuga or anyone else with comments?

**Comment by rslkr** [comment]
> replace the 25MB version in our bundle with the 1MB version and expand on first launch.

This one is working great. 👍 

The latest cheat file is 1.78MB b'coz of ''7z compression'' 

I know the goal here to reduce App. size but sooner or later @yoshisuga is going to upgrade the MAME version and App. size will increase again!
BTW 2020 is the best time to upgrade for 10 years anniversary.

**Comment by mrjschulte** [comment]
Done and merged!

**Comment by ToddLa** [comment]
> The latest cheat file is 1.78MB b'coz of ''7z compression'' 

standard deflate compresses it just as good, no 7z required.  

MAME (at least 139u1) needs the 25MB version at run time for random access to all the xml files. 

We just did not need to include the decompressed version in our resource bundle.
