### ISSUE TITLE
iPad 3 IPA 32 bits need

### ISSUE THREAD

**Issue by Caesaro72** [yoshisuga/MAME4iOS#19]
I just install in my iPad Air, and it´s amazing.Thank you. I NEED the IPA for the 32bits version for my iPad 3. It is possible to get?  Where can i get? Waiting for your reply.than you so much.

**Comment by yoshisuga** [comment]
I haven't built for 32-bit lately unfortunately and I'm not sure I'll get around to it. I'm more focused on getting MAME running on the latest iOS devices.
