### ISSUE TITLE
First launch on tvOS stalls on black frame....

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#192]
After doing a clean build and install of MAME for tvOS from scratch, on first launch you are presented with the "Allow Bluetooth" dialog. Upon selecting Ok the screen goes black and nothing else shows up. The Webserver does appear to be running in the background though. Only way to resume is to kill the MAME app on tvOS and relaunch.

Repo'd on current Git rev (421b973).

**Comment by ToddLa** [comment]
verified not a problem in iOS first launch, only tvOS.

**Comment by ToddLa** [comment]
PR #193 has a "fix" for this, disable SteamControllers (for now?) on tvOS.

**Comment by ToddLa** [comment]
PR #195 has the real fix.

**Comment by mrjschulte** [comment]
Works and closed!
