### ISSUE TITLE
Remove “Force Pixel Aspect”?

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#199]
![image](https://user-images.githubusercontent.com/4494698/81564636-e7901b00-934c-11ea-8763-9d11829c08c8.jpeg)

What are people’s thoughts on removing this option from Settings? It is a very strange option.

...and the user can always enable it, on a per-game basis, from the MAME menu > Video Options.

![image](https://user-images.githubusercontent.com/4494698/81564960-6b4a0780-934d-11ea-9b07-56af78f2c7fb.jpeg)

If we don’t remove it, we should at least move it, currently it is right next to “Integer Scale Only” and you can easily hit it by mistake....

**Comment by ToddLa** [comment]
If you have “Force Pixel Aspect” enabled in M4i options choosing “Standard” vs “Pixel Aspect (X:Y)” in the MAME > Video menu has no effect, they are the same.

**Comment by rslkr** [comment]
> If you have “Force Pixel Aspect” enabled in M4i options choosing “Standard” vs “Pixel Aspect (X:Y)” in the MAME > Video menu has no effect, they are the same.

Yes They are the same!
But somehow If you have “Keep Aspect Ratio” enabled in M4i options PORTRAIT and LANDSCAPE
They are working.

As long as ''Keep Aspect Ratio'' stay for both PORTRAIT and LANDSCAPE mode in M4i options.
I'm ok with whatever you decide for the ''Force Pixel Aspect.''

**Comment by ToddLa** [comment]
Yes having `Keep Aspect Ratio` is here to stay. 

But having both `Force Pixel Aspect` and `Keep Aspect Ratio` is confusing (at least it was for me)

`Pixel Aspect` and `Integer Scaling` is the only way to get zero pixel scaling, so it is useful. 

My whole point is that is because`Pixel Aspect` is available in the MAME Video Options menu, do we need/want it in our settings UI?

**Comment by ToddLa** [comment]
I moved around `Force Pixel Aspect` option, and named the option the same on tvOS in PR #204
