### ISSUE TITLE
Settings screen lockup and status bar visible while playing games

### ISSUE THREAD

**Issue by OutRunner** [yoshisuga/MAME4iOS#2]
Hello,

Great work getting this into an easily build-able state! I've noticed the status bar (time, battery, bluetooth, etc) is visible over the top of the game selection screen and in-game, if you add "View controller-based status bar appearance" to the MAME4iOS-Info.plist file and set it to Boolean NO the code in Bootstrapper.m to hide the status bar will start working again.

Also, on the iPad I've noticed the app locks up trying to display the Settings screen due to it trying to present the settings view controller while the UIActionSheet is still being presented. If you change 

`[self presentViewController:navController animated:YES completion:nil];`

to 

`dispatch_async(dispatch_get_main_queue(), ^ {`
`            [self presentViewController:navController animated:YES completion:nil];`
`        });`

the settings screen will start working.

Cheers!

**Comment by yoshisuga** [comment]
Thanks for the suggested fixes! I've applied them and tested on an old iPad 2:
https://github.com/yoshisuga/MAME4iOS/commit/b9c06e4fa4794bd0c8121fef902d9f55d9d6d483

Feel free to make a pull request for anything else! :)
