### ISSUE TITLE
Mega.nz prevents iOS downloads

### ISSUE THREAD

**Issue by ocwa1** [yoshisuga/MAME4iOS#20]
Mega.nz doesn't allow iOS downloads for install via iFile for jailbroken devices.

**Comment by ocwa1** [comment]
(Referring to the mega.nz download for the ipa in the readme.md)

**Comment by yoshisuga** [comment]
Hmm not sure what I need to do there. If you can download the IPA on a
computer and transfer it, that should work as an alternative.

**Comment by yoshisuga** [comment]
Closing, not focusing on jailbreak, sounds like an issue external to the application.
