### ISSUE TITLE
Hidden Combo Buttons Turn On/Off

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#202]
Hi @ToddLa,
If this one easy to make it, If not we can close this issue. Once again this isn't urgent request.
When you have time.

Hidden Combo Buttons are very useful on screen controller for some games.
But NOT every game requires combo buttons for special moves!!!
Sometimes you could tap on them by mistake, since the combos and main buttons are next to each other.

We can turn them on/off individually in the settings>game input>buttons.
Similar to Turbo Mode Toggle.
Or all of them by one switch.

**Comment by ToddLa** [comment]
Groan, I hate these buttons!

**Comment by ToddLa** [comment]
Sounds like there is no one button combo system that will work on all games!! So.....

**Comment by rslkr** [comment]
> Groan, I hate these buttons!

Perhaps, this is a really good reason to make it.
If user doesn't want them to be active on screen controller
We can turn them off in settings.
Or better yet, the combos are on the OFF/Disable mode (default) when the App. first installed,
We can turn them on when we need it.

> Sounds like there is no one button combo system that will work on all games!! So.....

I have an idea but probably you hate that too.

**Comment by ToddLa** [comment]
You can turn them on/off by editing the Button Layout in PR #242

is this good enough @rslkr?

Should we make the default state of all the combos be off, and make it so you have to edit a layout to get any at all?

**Comment by rslkr** [comment]
You did very good job on the **''Touch Layout''** Option. Its more useful now. Thank you so much.

While I move any button, my finger touches on the **''Touch Here to Finish''** and after that the pop-up shows **YES** and **NO**
If you could add a **''Cancel''** on the pop-up as well, to continue for adjustment that would be more helpful.

> Should we make the default state of all the combos be off, and make it so you have to edit a layout to get any at all?


Well it could better if **all of them off** when MFi first install.
But, I'm still thinking the same thing, turn them **on/ off** by one switch in settings, would be more easy and quick.

Now one more extra button (A+B) This isn't any problem at all on the **Game Mode** 'coz they are hidden.
But on the **''Touch Layout''** Option, little bit difficult to adjust  they got crowded!!!
**Maybe this is the reason you hate them?**
That switch also makes them **''Combos''** invisible on the **''Touch Layout''** Option. And gain more space for the rest of the buttons.

**Comment by rslkr** [comment]
This is enough, ToddLa.
Close this issue.
Thank you so much.
