### ISSUE TITLE
Add L1 and R1 in Fullscreen Buttons

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#203]
Can we add L1 and R1 in the Settings>Game Input>Fullscreen Buttons>Number Of Buttons

Currently We can select ''Auto, 0, 1, 2, 3, 4 and All Buttons''

Can we make the R1 5 Buttons and L1 6 Buttons.

I kinda found the codes in ''InputOptionController.m'' and ''EmulatorController.m''

I was only enable them in settings, edited the line 71 in InputOptionController.m

And in EmulatorController.m line 1600 

I added this codes but didn't work out!

`if(i==BTN_R1 && (g_pref_full_num_buttons < 5 && myosd_inGame))continue;`

`if(i==BTN_L1 && (g_pref_full_num_buttons < 6 && myosd_inGame))continue;`

**Comment by ToddLa** [comment]
If you want L1 and R1 you select “All Buttons”

Are you saying you want to show L1 and *not* R1?

**Comment by ToddLa** [comment]
Yea just checked, if you select `All Buttons` L1,R1 are shown full screen

**Comment by rslkr** [comment]
> Are you saying you want to show L1 and not R1?

I want to show R1 5 Buttons
 and then when we need all we can select All Buttons are shown all including L1
Right now we can select Auto 0 1 2 3 4 and All Buttons.

**Comment by ToddLa** [comment]
Why is R1 the 5th button? Not L1?

**Comment by rslkr** [comment]
OK I'll explain best I can. 
This is the layout M4i first installed:
https://user-images.githubusercontent.com/46307397/79296249-3ac5a800-7f1e-11ea-97ef-93ac5e8878d6.JPG
I can't use L button for this game. So I adjust L Btn in Touch Layout Option
Last time you mentioned to loose it custom button layouts: #165 
I prefer not to but who knows some day in the future one of you developers may decide to remove it!
If I can't use L button I'd like to turn it off.  
I hope you understand me. Everyone's own preference.
As always if it's easy to add it.
Thank you.

**Comment by ToddLa** [comment]
Just make a custom layout and move the L1 button off “the screen”

**Comment by rslkr** [comment]
Oh I just noticed it. You added them in the settings.Thank you.
Unfortunately, that's the wrong button!!!
I want the L1 button for number 5

I hope that no one removes the custom layout option.
Thanks.

**Comment by ToddLa** [comment]
I checked: MAME considers L1 button5 and R1 button6. 

So I went with the MAME convention!

5 buttons mean 🅐 🅑 🅧 🅨 and L1

**Comment by rslkr** [comment]
> MAME considers L1 button5 and R1 button6.

I assume that it means you can't change them only for me!!!

So I close this issue then.
