### ISSUE TITLE
Display title artwork for 2 screen games 

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#208]
Currently, 2020.8, title artwork for games using 2 screens is being "squished" into a 4:3 tile. This is fine for now but adding this issue in for future tracking.

**Comment by ToddLa** [comment]
Besides X-Men what are other examples?

**Comment by ToddLa** [comment]
A quick scan of all the titles, and I only see the one X-Men game that has a 8:3 title screen...

**Comment by mrjschulte** [comment]
Not important then, closing.
