### ISSUE TITLE
Building with Xcode 10 / iOS 12

### ISSUE THREAD

**Issue by calburitel** [yoshisuga/MAME4iOS#21]
Apologies as I know this is too general of an error to help diagnose. I've installed MAME4iOS 64 successfully in the past on multiple iOS 11 devices. I have been unable to do so with Xcode 10 and iOS 12. While I lack any profound code skills, for the most part, I've usually been able to diagnose and fix my own issues, but this one has me scratching my head. I checked out the latest 'master' which should have added support for Xcode 10 and iOS 12 with libc++. I tried building in two different machines and iOS devices and I get the same error below. In one of the builds it reads "fix references to old stdlib functions. Is that where my issues? I copied the libmamearm64.a file to root as in previous 64 builds. Any clues? Once again, sorry for not having more vocabulary to accurately describe potential issues.

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yoshisuga** [comment]
Hi! No problem at all!

Looks like the issue is that you needed to rebuild the MAME library using `make` again - the libmamearm64.a file you had was built with libstdc++ so it'd be incompatible with the updated Xcode 10 codebase.

I uploaded the precompiled libmamearm64.a again and updated the link in the README - here it is for your convenience:
https://mega.nz/#!7BAzDKiZ!n36DKsGeiw6vzvi6hcuWcAVSiLSd4UKSMfbnWFIhdZI

You should be able to build successfully with this new .a file.

**Comment by yoshisuga** [comment]
Ah, I forgot to check in a file that I was still working on. I added that
file so try pulling again and rebuilding.

**Comment by calburitel** [comment]
@yoshisuga you are awesome. thank you so much for doing that. The build worked flawlessly and I have it running on my iPhone X. Sorry I didn't know enough to rebuild and replace those files. I truly appreciate you helping a nerd with no coding skills. I'll install it on my iPad Pro tonight. You area champ my friend. Closing the issue.

**Comment by yoshisuga** [comment]
No problem, glad I can help you get it working!

**Comment by r0b3** [comment]
Greetings @yoshisuga, I have same problem building for OSTV whit this message "ignoring file /Users/xxx/Downloads/MAME4iOS-master/xcode/MAME4iOS/libmamearm64-tvos.a, file was built for archive which is not the architecture being linked (x86_64): /Users/xxx/Downloads/MAME4iOS-master/xcode/MAME4iOS/libmamearm64-tvos.a", thanks.

**Comment by dramagods** [comment]
Hello @yoshisuga,

I just had the same issue as @r0b3 when building MAME4iOS for TVOS:
```ld: warning: ignoring file /Users/alfonso/repositories/MAME4iOS/libmamearm64-tvos.a, building for tvOS Simulator-x86_64 but attempting to link with file built for tvOS-arm64
.....
      -[EmulatorController updateOptions] in EmulatorController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:```

I tried to figure it out how to get those undefined symbols for x86_64 but I had no luck so far.
I would be great if you could help us out. 
Many thanks.
