### ISSUE TITLE
Remove Options for Landscape/Portrait

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#211]
M4i has separate options for Portrait mode and Landscape mode.

It also have video related options in two other places (main page and Defaults) that is four places for video related options.

The only option that I see makes sense to be specific to Landscape is `Full Screen` so I propose merging all the Portrait and Landscape options, and make a single new option `Default to Fullscreen in Landscape` or something.

Thoughts?

![image](https://user-images.githubusercontent.com/4494698/83896493-1fe70700-a709-11ea-8329-c3b1dfccb7b8.jpeg)

**Comment by ToddLa** [comment]
I have made this change in PR#213 there is only a single "Video Options" and a new "Fullscreen" options.

<img width="399" alt="Screen Shot 2020-06-09 at 8 44 24 AM" src="https://user-images.githubusercontent.com/4494698/84169594-a06d7680-aa2d-11ea-98a2-c1b4a698b15f.png">

<img width="395" alt="Screen Shot 2020-06-09 at 8 44 40 AM" src="https://user-images.githubusercontent.com/4494698/84169602-a400fd80-aa2d-11ea-84e0-e77334a8272e.png">

**Comment by rslkr** [comment]
Hi @ToddLa 
First, Thanks for your hard work. I guess you swear to make this App. unbeatable. It will be if you keep adding this kinda features (HUD).  👍

I'd like to report couple of issues:
-Fullscreen (Controller) switch in settings doesn't function anymore (above picture).
-On Fullscreen Portrait Mode: Newer IPhones 11 shows only 4 buttons, but on the older IPhones it shows  6 buttons!!!

Also I'd like to give my feedback about the HUD
There is a icon to collapse the option (HUD) which is good option, but it's still on the screen. So I go back in the settings to turn it off the HUD. Instead of doing this; can we use the ''EXIT'' buttons for it. First tap exit for the HUD and again second tap for the game.
One more thing (this is important)
While I'm using the screen controllers (on Fullscreen) the HUD pop-up instantly because of the Two-Finger-Tap gesture. Can we replace with the Two-Finger-Swipe Down gesture, like @yoshisuga suggested, please.
Thank you.

**Comment by ToddLa** [comment]
Yes we should get rid of the two finger tap, I was afraid of a conflict. 

Then the HUD will only be on screen if you turn it on in settings.

**Comment by ToddLa** [comment]
“I'd like to report couple of issues:
-Fullscreen (Controller) switch in settings doesn't function anymore (above picture).”

`Fullscreen Controller`  means default to Fullscreen if you are using a game controller like a MFi, or iCade.

**Comment by ToddLa** [comment]
“-On Fullscreen Portrait Mode: Newer IPhones 11 shows only 4 buttons, but on the older IPhones it shows 6 buttons!!!”

I will take a look, but i don’t think things are different. 

What exact devices, and are you talking fullscreen? I assume so

**Comment by rslkr** [comment]
> Fullscreen Controller means default to Fullscreen if you are using a game controller like a MFi, or iCade.

Yep, That makes sense.
I just remembered it was working on the iphone before and when you want to connect to the TV with cable or wireless. And don't want to see the controllers on the TV, that switch helps.
Anyway this is not a real issue.All good.

> What exact devices, and are you talking fullscreen? I assume so

Iphone 11
![37c8106c-92b7-4256-831e-60ccdc0ef186](https://user-images.githubusercontent.com/46307397/84561828-08f08680-ad93-11ea-8a0e-cfe2f91726cc.jpg)

Iphone 7
![f738b7a9-5bda-4119-be40-98aa5101b49f](https://user-images.githubusercontent.com/46307397/84561989-38ec5980-ad94-11ea-9d3d-9cf09f9ae580.jpg)

I don't use the Portrait mode more often, mostly Landscape mode so this isn't a real issue either.

**Comment by rslkr** [comment]
You might wanna considering the **EXIT** button for the HUD
This will be usefull.

**Comment by ToddLa** [comment]
Two finger tap is gone in PR #214

**Comment by ToddLa** [comment]
As for the L R buttons on iPhone 7 
This is correct SF2 uses all the buttons, so we show them all. The layout for iPhone 11 must not have L R in portrait and the 7 does!

**Comment by ToddLa** [comment]
Yup the iPhone7 layout has LR buttons in fullscreen-portrait mode, the iPhone11 layout does not. This is nothing new.

**Comment by rslkr** [comment]
That's OK. A game requires 6 buttons to play on the Portrait Mode not ideal way to play...

Your idea was good. Activating the HUD on the screen.
Can we add the HUD into the **OPTION** button for easy access? Please.
It can work exactly like MAME Menu
Having one more section on the pop-up MENU won't bother anyone I think.
Especially this one HUD.
I know last time you said ''save space in the menu''
But there is still room on Portrait mode, plus we already scrolling it down/up on the Landscape mode.
Thanks.

**Comment by ToddLa** [comment]
I am gonna close this issue, and we should make a new one about HUD in In game menu
