### ISSUE TITLE
Can’t `EXIT`with Show Info/Warnings

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#219]
Turn on `Show Info/Warnings`
Run game
Hit `EXIT`
Game will just re-display message, not exit
You need to wiggle stick, then `EXIT`

**Comment by rslkr** [comment]
Yes, Show Info/Warnings was on.
Sorry, I didn't know that. Everything's back to normal now
Thanks.

**Comment by rslkr** [comment]
This ''**Show Info/Warnings**'' meant to be work this way....
Is this normal? Can we fix this?

**Comment by ToddLa** [comment]
I think it has been like this forever

**Comment by rslkr** [comment]
That's ok. I always leave it off then.
Thanks.
