### ISSUE TITLE
iCade controllers stop working when external screen connected

### ISSUE THREAD

**Issue by ck16** [yoshisuga/MAME4iOS#22]
Hi @yoshisuga,

I've noticed that when an external screen is connected both via AirPlay to an Apple TV or through the lighting HDMI cable, my iCade controller no longer works on my iPhone XS Max.

When the screen is disconnected, the controller works again.  This issue doesn't happen with MFI controllers.

I'm currently using a Steel Series Nimbus MFI controller and a ThinkGeek 8 bitty iCade Controller.

Please let me know if you need any more info!

Cheers
ck16

**Comment by yoshisuga** [comment]
I put in a fix for this: d68fc9dc1d425abc0627f01c79c967ade79769d9

I'm not able to test this at the moment so I'm not 100% sure if it works, but try it out :)

**Comment by ck16** [comment]
Hi @yoshisuga,

I just compiled the latest commit and can confirm that iCade controllers no longer stop functioning when an external screen is connected.

Thanks heaps for thew quick turnaround!  This issue can be closed.


Cheers,
ck16
