### ISSUE TITLE
Stuttering audio (all games) on iPad Pro 2020 (A2228)

### ISSUE THREAD

**Issue by Chochopocho** [yoshisuga/MAME4iOS#223]
Hi!
Sorry if I’m pointing something that has already known, but I can’t find the solution or the issue here.
All the games I proved (circa 40) are suffering audio stuttering, cracklings, etc. No matter what I change in settings menu, it continues with the problem. It sounds like a distortion, cuts, and maybe audio repeating, but is hard to guess a concrete problem, as all the artifacts make hard to understand whats going on...
And then, suddenly, the app has no more stuttering. 
Sometimes I open the app and there is no stuttering, and suddenly, after opening some games, it has.
I switched off Low Latency Audio and Throttle, but nothing appears to solve the issue.
I tested version 2020.11 on my iPad Pro 2020 wifi and on iPhone X (A1901), and on iPhone there is no stuttering (with the same games).
I guess is a matter of device, but if someone with the same problem could help, I will really appreciate it.
Thanks a lot.
I think it is a great port, and a great update work. I thought the project was abandoned, and then found this, I’m really glad that you continue this great project. And sorry for my english!

**Comment by ToddLa** [comment]
Fixed in PR #225

**Comment by Chohopocho** [comment]
Thanks a lot! 👏👏👏
