### ISSUE TITLE
Return of the Audio Garble?

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#226]
There is still a very subtle audio garble when using Metal. This is not present when using the non-metal rendering framework. @ToddLa suspects there are still some subtle timing issues to resolve with the Metal renderer and has some ideas.

**Comment by ToddLa** [comment]
PR #227 should make audio happy.
auto-frame-skip makes MAME happy.

**Comment by mrjschulte** [comment]
Works much better, closing.
