### ISSUE TITLE
Adjust HUD size

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#228]
Sorry, ToddLa, Dynamic type didn't change the size!

It does effect on Settings and the other pop-ups.

Size of the HUD isn't too small on iPhone11, but size of the HUD on iPhone7 much better and just for the record I don't have huge finger tips.

Dynamic type max. on iPhone11 and **if this is the way it works I'll close this issue**.Thank you.
Running on iOS 13.4.1
![5ce85ec2-fdc9-46bb-a68b-516022f6e475](https://user-images.githubusercontent.com/46307397/86113886-28b2d900-bb0d-11ea-8e2e-ed83586d508c.jpg)

![18ef6076-fbef-4674-a01a-2a75ebba581a](https://user-images.githubusercontent.com/46307397/86114071-67e12a00-bb0d-11ea-8a45-eed650e6e3c6.jpg)

**Comment by ToddLa** [comment]
in #227 the HUD will respect DynamicType

**Comment by ToddLa** [comment]
DynamicType might not be a perfect solution, might just add a pinch gesture to let you re-size the `HUD` to anywise...

**Comment by ToddLa** [comment]
I went ahead and added PINCH and ZOOM to the HUD in #227. You can make the HUD any size you want and it will remember. The base/default 1.0 size is based on DynamicType. So it is a hybrid solution.

**Comment by mrjschulte** [comment]
@rslkr the new PR @ToddLa mentioned has now been merged into Mainline, please give it a try and let us know what you think.

**Comment by rslkr** [comment]
Wow, Honestly I wasn't expecting this! I wanted HUD little bit larger but This is perfect and great idea ''PINCH and ZOOM''
Thank you so much.
I don't know what I did wrong, while I was testing the HUD. Everything scaling ''bigger and smaller'' normally, menu/buttons.
When I tapped on the ''Filter, Border and Shader'' the list and the text got way bigger!! **But this only happened once.**
And Dynamic Type was on the middle.

**Comment by ToddLa** [comment]
I don’t need to make the icons bigger, or smaller. You can just pinch and zoom and make them any size you want!!!

**Comment by ToddLa** [comment]
The popups from the filter, border, and shader buttons are not scaled to the HUD size, they are the normal system DynamicType size. 

I wonder if we should even keep these buttons. Filter and border are not very useful, and selecting the Shader from the HUD while good for debuging new shaders is not generally useful. 

Maybe move the filter, border, shader buttons back to the shader config page...

**Comment by rslkr** [comment]
Now everything is perfect on the HUD with latest update.
Also I meant the icons on the new UI mode next to the MAME Logo but doesn't matter they are not too small.

**Comment by ToddLa** [comment]
The icons “next to the mame” logo, you mean the ones in the Navigation Bar when choosing a game?

We can’t (easily) make the NavBar any taller. 

We could make the buttons wider (ie non-square)

**Comment by rslkr** [comment]
Yes top of the search bar.

They are look good size on the iPhone7 you can't make better then that I think,
But on iPhone11 bigger screen they look too small

**Comment by rslkr** [comment]
ToddLa, Please forgive me if I'm asking too much.
Do you have any experience in the Start Server (Upload Files/roms) option? on the web browser.

**Comment by ToddLa** [comment]
Yea I guess so, but it is better to use AirDrop or Import ROMs

**Comment by rslkr** [comment]
First, its working perfectly fine and whoever add that feature, I really appreciated him.

While Its uploading the roms, the web browser on my computer, phone gets sleep and after that, the one(roms) didn't upload 
b'coz of lost connection shows ''Failed'' This is normal.

All I want to know is there any way to add ''re-upload'' button on the web browser for the **error** ones
This is just the improvement the Start Server option.


![Capture12](https://user-images.githubusercontent.com/46307397/86484207-0f25c180-bd99-11ea-95a8-1ad080af13f2.PNG)

**Comment by ToddLa** [comment]
We have no plans to touch that WebServer code. Use iOS File import or AirDrop when you can. tvOS can only do the Web, so we will keep it working, just barley.

**Comment by rslkr** [comment]
OK Thank you ToddLa, I just wanted to know. Now I know, no touch the WebServer code.
Good thing, I didn't open an issue, always ask first.
