### ISSUE TITLE
Deprications

### ISSUE THREAD

**Issue by gajahduduk** [yoshisuga/MAME4iOS#23]
Building on XCode 10.0 (MacOS 10.13.6), with commit as of Oct 8 (sorry not sure how to best identify), I initially got 150+ warnings, mostly to do with deprications. As I recall, having to do with fonts.  Now that I have successfully built, I don't see those warnings anymore.  Not familiar with XCode enough to show them again.  Just FYI.  _domo arigatoo gozaimasu_.

**Comment by yoshisuga** [comment]
Your welcome! - there are warnings from building on the latest SDK as there's a lot of old code there. I'v e updated some of them for the tvOS port but there's still some work to do there.
