### ISSUE TITLE
Make app resizable and clean up artwork.

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#232]
Make the app more adaptive to the size of the window/screen, this is needed for....
* a new iPhone or iPad screen device in the fall.
* working in iPad `SlideOver` or `SplitScreen` mode.
* running as a `Catalyst` app.

the code is pretty easy, just some math to scale the hardcoded rects from the (best) config file to the actual screen/window size. but what we do need it some artwork tweaks.....

**Comment by ToddLa** [comment]
back_landscape_iPhone
back_landscape_iPhone_6
back_landscape_iPhone_5
back_landscape_iPad
* The image behind the joystick should be removed, and restored to just "brushed metal"
* The black area should be removed, and just "brushed metal"
* Maybe the vertical "notches" should be removed, because they don't always line up with the `SCREEN`
   
back_portrait_iPhone
back_portrait_iPad
* The image behind the joystick should be removed, and restored to just "brushed metal"
* The word "menu" should be removed, and replaced with horizontal line.

I would like the background images of the joystick to be moved to a separate file (square, with alpha).  I am thinking we just need the one from the current portrait images, but if you think we need a different one for landscape make that too.

**Comment by ToddLa** [comment]
FYI app currently looks terrible in landscape non-fullscreen on modern devices, so this artwork tweak will help that too.

**Comment by mrjschulte** [comment]
@daedalia , did you have time to look at this?

**Comment by daedalia** [comment]
Done some initial work to get Todd going

**Comment by ToddLa** [comment]
#242 covers all this
