### ISSUE TITLE
better iCade button defaults?

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#238]
Dusted off my ION iCade (w some Sanwa after-market upgrades of course) and it still plays great. Only wish that the default button layout was better suited and used the right most "column" of buttons for Coin + Start as opposed to the first "column" .

**Comment by mrjschulte** [comment]
Looks like we also can't actually type anything in the "search" bar when using the iCade (configured on iOS as a keyboard). Could  we disable the iCade Keyboard control and revert back to the iOS keyboard when we invoke the "Import Roms" workflow?

**Comment by ToddLa** [comment]
That sounds like a big, the keyboard issues, I will have to look. The search bar in the ChooseGame UI has same issue??

**Comment by ToddLa** [comment]
That key layout is old as dirt. Come up with a better one, and I will do it. 

Change the bitmap in help.images

**Comment by ToddLa** [comment]
https://github.com/yoshisuga/MAME4iOS/blob/master/xcode/MAME4iOS/iCadeControls.png

**Comment by ToddLa** [comment]
I assume you mean a on-screen-keyboard does not show up when a text field has focus, with a iCade....

**Comment by ToddLa** [comment]
The on screen keyboard not showing is an iOS issue we can't do anything about
