### ISSUE TITLE
Metal Shader defaults....

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#239]
I am a big fan of a good OBE, and currently M4i defaults to no filtering and no effect shader...

I think we should default to:
* Linear Filtering
* simpleTron screen shader. 
* lineFade line shader. 

Thoughts?

**Comment by mrjschulte** [comment]
Fine by me. That should cover all of the hero use cases. Including a better “vertical” game experience by adding in linear filtering as a default.

**Comment by ToddLa** [comment]
People can always turn the effects off, having a wow OOBE is more important. 

And our shaders barley tax the GPU anyway.

**Comment by ToddLa** [comment]
PR #241 has the defaults set to simpleTron and lineTron
