### ISSUE TITLE
Custom Button Layout

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#241]
# Custom Button Layout changes

I am making a few changes to the custom button layouts. To simplify the code and options so a true skin system can be done. To that end I am removing a few features and want comments. 

## Fullscreen vs NonFullscreen
Currently we have 8 config layout options `(portrait, landscape) x (iPad, iPhone) x (fullscreen, non-fullscreen)`
I propose we nuke the fullscreen customization all together, and have only 4 configs `(portrait, landscape) x (iPad, iPhone)`.

all of the pre-canned configs have the buttons and stick in the exact same position in fullscreen, non-fullscreen.

the *only* things that are in different positions are the command buttons (`SELECT`, `START`, `EXIT`, `OPTION`) and then *only* in portrait mode.  (this can just be handled in code....)

## Bitmap rect and Touch rect
The pre-canned layout files contain a Bitmap rect **and** a touch rect. I propose we just ignore the touch rects and set them to 80% of the image rects. (that is basically what *most* of the layout files do, except for the ones that are broken!)

## DPAD rects
The DPAD rects in the layout files are currently ignored already, I merged the DPAD into the AnalogStick a while ago.

## Combo buttons
the current Combo buttons (`A+Y`, `X+A`,`B+X`, `Y+B`) can be custom positioned. I want to do one of the following.
1. remove these combo buttons, they don't apply to every game.
2. don't let them be customized, just compute their position from the location of 🅐🅑🅧🅨  
3. let them be customized, and even add different combos, and a UI switch to turn them off.

I am leaning toward #2, change my mind.

## backward compatible
Should we just not support any previous customized layouts, and make them create a new one. Or should we do a best effort to convert/support old layouts?

The current layouts are in device points, so if you run on a different device screen size, all your buttons are junk. 

So far I don't see a problem to keep loading the old layouts.

**Comment by ToddLa** [comment]
Wrt Backward compatible, if you run at least once on the same device the layout will get converted to a scalable one. So that was easy.

**Comment by ToddLa** [comment]
PR #242 implements this.
* we are not backward compatible, and custom layout needs to be re-done.
* kept the combo buttons
* you can dbl-tab a button in the layout edit screen to hide/show
* you can pinch/zoom in layout edit screen to scale.

**Comment by rslkr** [comment]
Hi ToddLa, Thank you for keeping the combos.
My feedback for latest update:

> you can dbl-tab a button in the layout edit screen to hide/show
you can pinch/zoom in layout edit screen to scale.

I like these features and the new button layout.
And I realized **dbl-tab on a combo button**  makes it disable. That's good. 👍 

Another tiny issue: When I move any button (custom layout) the button gets little bit bigger than the rest of buttons on the Landscape Mode!

**Comment by ToddLa** [comment]
> Another tiny issue: When I move any button (custom layout) the button gets little bit bigger than the rest of buttons on the Landscape Mode!

Yea I think that is related to a rounding error, there is a `TODO` in the code to check it out...

**Comment by ToddLa** [comment]
PR #243 has a tweak to not change the button size if you only move it...
