### ISSUE TITLE
Hud icon position is not remembered when changing screen orientation

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [yoshisuga/MAME4iOS#247]
Hi,

Just a tiny bug - when playing on my iPhone in landscape mode I like to keep the hud icon outside of the game view so that it does not cover the action. 

Bug: after switching to portrait mode and back to landscape the position of the hud is somewhere in the middle of the screen.

![3301FBCC-5090-4685-B940-9237B243EC83](https://user-images.githubusercontent.com/26039401/93054304-071fb300-f661-11ea-9949-8e35cc622486.png)
![9C71405F-3B5E-4465-A848-85E992FCA8CA](https://user-images.githubusercontent.com/26039401/93054319-0c7cfd80-f661-11ea-9dc3-c4595811d768.png)
![9CD931CF-76BE-4895-AE1C-3024197221CD](https://user-images.githubusercontent.com/26039401/93054322-0dae2a80-f661-11ea-876c-da99058e182a.png)

**Comment by ToddLa** [comment]
Yup when you rotate the position of the HUD might get clamped to the SafeArea.

**Comment by ToddLa** [comment]
One fix would be to store position relative to the game screen, and in uniform (non-points) coordinates.
