### ISSUE TITLE
Latest commit, controller and buttons off

### ISSUE THREAD

**Issue by Cepheidsong** [yoshisuga/MAME4iOS#25]
Hello, this may be an update maybe for latest iphone, I am still on iphone 7 on ios 11, but all the buttons and the red knob of the joystick are about 1/2 inch above where they are normally positioned.  Everything else still runs ok!

If you need a screenshot I can take from phone and show you in discord.

(built with xcode)

**Comment by yoshisuga** [comment]
Yes, unfortunately I haven’t gone thru and adjusted the positions of the controls for each device. You can adjust them manually in the meantime. Sorry about that!

**Comment by ck16** [comment]
Hi @yoshisuga,

I've noticed that when running MAME4iOS on an iPhone XS in portrait mode, not only is the joystick in an elevated position as reported in this issue, but there is also a secondary (inactive) controller at the bottom of the screen (see attached screenshot).

Thanks heaps for all your hard work!


Regards,
ck

![img_5838](https://user-images.githubusercontent.com/8214329/51437579-524eba80-1cf4-11e9-9263-68447704a3ec.png)

**Comment by yoshisuga** [comment]
Your welcome! :) Yes what you see at the bottom is just the background image - the stick control should normally sit on top of that. I'll eventually get around to supporting the positions of those but it's just...boring time consuming work :)

**Comment by mrjschulte** [comment]
Fixed in the latest build.
