### ISSUE TITLE
Installation on iPad 4 fails with kAMDPackageInspectionFailedError

### ISSUE THREAD

**Issue by derekadk** [yoshisuga/MAME4iOS#250]
I have an older iPad 4 running iOS 10.3.3 and I'm loading the ipa through iMazing.  It fails with this error.

kAMDPackageInspectionFailedError

It's a shame that my old version of Gridlee isn't working as I cannot access the Documents folder since iOS 8.3.

Any advice?  Or an older version of MAME4iOS that supports iPad 4 and iOS 10.3.3?

**Comment by ToddLa** [comment]
current M4i is arm64 only, and has a minimum os required of iOS 12.
the iPad (gen-4) is not a 64bit device, so you are gonna need to run an older (I dont know what version) of M4i, or run Gridlee

**Comment by mrjschulte** [comment]
Yeah, unlikely that this is going to work. You can try the releases that are out on this Git site but there are no guarantees this will work. 

With iOS 14 out we may just have to follow suit and only offer up official support for a minimum of iOS 12 (like we currently do unofficially).

**Comment by rslkr** [comment]
Hi, @derekadk 

Have you tried one of these?

https://github.com/jiaxianhua/Mame4iOS

https://github.com/FlexingTiger/MAME4iOS
