### ISSUE TITLE
Starting server does nothing

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [yoshisuga/MAME4iOS#253]
Hi,

I have recently updated my ios to 14.0, then when clicking on mame4ios icon it would show "this application is no longer available" so I deleted it, pulled the newest master and installed from it.

Now the mame4ios has no roms so I press "Start server" but nothing happens - no errors, no dialog... sure I can get roms in in other waysbut I preferred this one - it is a good feature to have :).

Any ideas?

Tom

**Comment by ToddLa** [comment]
This needs investigated, iOS 14 now requires user to give permission for app to act as a server, but If you say yes, all is ok. 

Check `Settings` > `Privacy` > `Local Network` And make sure `MAME4iOS` has permission. I hope that is all this is.....

We should test when permission is denied and give a sane error. 

Also these system permission alerts cause us some problems on tvOS OBBE (like Bluetooth did....) we should dbl check tvOS too.

**Comment by ToddLa** [comment]
Yup fresh run on iOS 14 and the Server fails.

Actually the server is running just fine, BUT what does not happen is we can't get the Bonjour name, and we dont show any UI saying the server is running, or a way to stop it.

something got borked with Bonjour on GM iOS 14.

**Comment by ToddLa** [comment]
The fix is to just show the Server UI with the raw IP address, not the friendly Bonjour Name....

**Comment by ToddLa** [comment]
My guess is that low level Bonjour CF apis are failing without asking for permissions, who knows we might need a entitlement.

BUT my fix in #255 is to give Bonjour 2sec to come back with a name, and if not just show the Server Alert with a raw IP address.

**Comment by ToddLa** [comment]
I know the server worked in the iOS 14 Betas, but something must have changed. I alway restore my ROMs with a ZIP import, so did not notice when the server code fell down.....

**Comment by Tomasz-Kluczkowski** [comment]
Hi,

I have checked Settings > Privacy > Local Network on my iphone and mame4ios is not present there at all...

I do not remember it requesting a permission though so maybe that is why?

Tom

On 12 Oct 2020, at 01:22, Todd Laney <notifications@github.com> wrote:

﻿

This needs investigated, iOS 14 now requires user to give permission for app to act as a server, but If you say yes, all is ok.

Check Settings > Privacy > Local Network And make sure MAME4iOS has permission. I hope that is all this is.....

We should test when permission is denied and give a sane error.

Also these system permission alerts cause us some problems on tvOS OBBE (like Bluetooth did....) we should dbl check tvOS too.

**Comment by mrjschulte** [comment]
New Pr has been merged that should fix this. Can you try again and let us know?

**Comment by Tomasz-Kluczkowski** [comment]
Thx starting the server works fine!
