### ISSUE TITLE
Best way to save app and individual games config, high scores etc

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [yoshisuga/MAME4iOS#257]
Hi,

This is more of a question/feature request for full backup of the mame4ios.

Basically whenever I update the phone or mame4ios itself, often it starts empty.

I have exported the roms so that is easy to get back everything else needs configuring again...which is a pita...

Could we make a case for one export button which exports also configs, including the app's config etc and then import would bring it all back where it belongs?

If not, how do you deal with this problem your selves?

Tom

**Comment by ToddLa** [comment]
When you do a `Export` the following data get ZIPed up and exported....
* ROMs
* Artwork
* Titles
* Samples
* CFGs
* INIs
* STA (Saved Games)
* HI (High Scores)
* Skins

what does not get exported
* CHDs (these are too big)
* MAME4iOS Settings (Screen Shader, Current Skin, Show FPS, etc....)

**Comment by ToddLa** [comment]
We have considered saving the Settings, but as far as we got was to add a TODO
```
// ZIP up all the important files in our documents directory
// this is more than just "ROMs" it saves *all* important files, kind of like an archive or backup.
// TODO: maybe we should also export the settings.bin or the UserDefaults plist
// NOTE we specificaly *dont* export CHDs because they are too big, we support importing CHDs just not exporting
```

**Comment by ToddLa** [comment]
There are plans afoot (Issue #249) for iCloud Export and Import. but I would expect it would save/restore exactly what the current `saveROMs` does.

so the real question is, should `Export to ZIP` and `Export to iCloud` export the MAME4iOS Settings??

**Comment by ToddLa** [comment]
@Tomasz-Kluczkowski current export should get all the MAME Setting for a particular game (ie the CFG and INI file) are you not seeing that?

**Comment by ToddLa** [comment]
I added our setting file to the export list (in next PR). So if you restore from a zip export (or from iCloud) your settings come along with that.

**Comment by Tomasz-Kluczkowski** [comment]
Amazing thx.

On 20 Oct 2020, at 04:16, Todd Laney <notifications@github.com> wrote:

﻿

I added our setting file to the export list (in next PR). So if you restore from a zip export (or from iCloud) your settings come along with that.

**Comment by ToddLa** [comment]
PR #263
