### ISSUE TITLE
Some games not showing scanlines.

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#258]
Games such as Rampage do not appear to be showing the scanlines in the Tron Metal shaders.

**Comment by ToddLa** [comment]
I just verified we think RAMPAGE is a vector game.
Investigating.....

**Comment by ToddLa** [comment]
![image](https://user-images.githubusercontent.com/4494698/96376451-cc171080-1133-11eb-80f1-6a144646377c.jpeg)

If you do a screen shot and zoom in you can see the tiny scanlines

**Comment by ToddLa** [comment]
One way to "fix" this is to have the shader detect when scanlines are just "too small" and *do something*

One thing it could do is treat 2 source scanlines as one, that would make the scanline effect more prominent.

Our MAME renderer could even *lie* to the shader and tell it that the source texture is 2x lower res when we detect cases like this, but I would rather leave it to the shader to decide.

**Comment by ToddLa** [comment]
I take it all back, again, something weird is going on with RAMPAGE....

(Not that the small scanline issue, is not a thing it will be for hires games, but RAMPAGE is not high-res enough for this....)

INVESTIGATING....

**Comment by ToddLa** [comment]
If you choose `megaTron` or the DEBUG `Test (scanline)` you get a more apparent scanline effect.

**Comment by ToddLa** [comment]
Or we can render to an offscreen texture that is the nearest integer multiple of the MAME screen vs. the DEVICE render target, then scale down for final display.

Offscreen "chain" rendering may be needed for other future effects, but it is not something we have now.  It is not hard, just non-trivial.
