### ISSUE TITLE
Drawing MAME UI over Screen shader?

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#259]
IS it desirable to have Game UI drawn on top of the Screen Shader like what is happening with the Gear Shift icon in Outrun?

**Comment by ToddLa** [comment]
Screenshot??

**Comment by ToddLa** [comment]
If you are talking about Artwork overlays and bezels, yes those get draw with no shader, only a MAME SCREEN is drawn with a shader effect.

**Comment by ToddLa** [comment]
Yup the gear shift is not a SCREEN, it is a ARGB overlay.
Working as expected.
