### ISSUE TITLE
tvOS: Selected game is not highlighted

### ISSUE THREAD

**Issue by jpbedoya** [yoshisuga/MAME4iOS#260]
When moving around the "game grid" some games don't get highlighted even though they are selected. Seems to happen mostly for games on rows 2 and higher and sometimes all the time. 

Commit used for build: https://github.com/yoshisuga/MAME4iOS/commit/937304fd84a9c93b81bab573804c002496bbbf16

**Comment by ToddLa** [comment]
Yup saw that too, something changed in latest tvOS and the *hack* we were using to get the system parallax effect is not working any more.

This is fixed in a private branch of mine (soon to be a PR...)

**Comment by jpbedoya** [comment]
It's fixed for me. Thanks.
