### ISSUE TITLE
tvOS: TopShelf shows latest games but blank artwork

### ISSUE THREAD

**Issue by jpbedoya** [yoshisuga/MAME4iOS#261]
TopShelf shows blank cards

![IMG_4982](https://user-images.githubusercontent.com/6699756/96375130-07154600-112c-11eb-8777-a362c7098ff7.jpg)

**Comment by ToddLa** [comment]
That is odd, you see the title images in the game ui, I assume.

**Comment by ToddLa** [comment]
@jpbedoya you had no issues building with entitlements?

**Comment by jpbedoya** [comment]
I do see the images in the game UI and didn't have issues building with entitlements. 
If I click on the game in Topshelf it does open correctly in MAME.

**Comment by ToddLa** [comment]
The TopShelf lives in its own sandbox and needs to re-download them (independently of the app) so if you don't have a internet connection you would see what you are seeing.

**Comment by jpbedoya** [comment]
It's fixed with latest 2020.13 release tag
