### ISSUE TITLE
Investigate creating a native Apple Silicon libmame build

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#268]
With the M1 era and apple silicon upon us lets look at making a native Apple Silicon libmame build.

**Comment by ToddLa** [comment]
This is what happens currently!

`make-mac.sh` and `make-sim.sh` when run on a M1 Mac will build a arm64 library. So the final macApp is all native arm64.

**Comment by ToddLa** [comment]
....or do you mean we should build a universal `x64 + arm64` app??

**Comment by ToddLa** [comment]
@mrjschulte latest build will build a universal arm64/x64 binary for the Mac app....

**Comment by mrjschulte** [comment]
This is done.
