### ISSUE TITLE
Add transparency slider for onscreen controls in fullscreen

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#27]
Hi Yoshisuga, happy new year. There's only one issue that I found in the repo when build with xcode that 'skin' option is missing. Everything's ok in IPA. Anyway, I want to add some features to Mame source and rebuild/compile the Mame library, but I couldn't get the 'libmamearm64.a' file I have no idea how to do that! The feature I want to add that starts in the Mame 0171, there is a code in 'src/emu/ui/menu.cpp' for "On/Off" color (on=green, off=red) it looks pretty good with 'Cheats and Dipsw'. I tried compile mame 0139 source in Windows/Macos with new uimenu.c to make sure its working but all failed! I only success compiled mame0128 mame0197 and mame0202. If you don't mind could you tell me are you using this repo(Mame4ios) to rebuild Mame library (libmamearm64.a) If so how? I add the code in Mame 0139 'src/emu/uimenu.c' in case you wanna try.
[uimenu.zip](https://github.com/yoshisuga/MAME4iOS/files/2719936/uimenu.zip)
I really love this app. I'm not a developer, all I want make this app. more better. Like 'turbo mode toggle for buttons' You added that's exactly I need. I play other emulator called Happychick has an option adjustable transparent for buttons is it possible you could add similar option for Mame4ios?
Thank you.
Edit: I build it by Terminal sorry I should've read properly.

**Comment by yoshisuga** [comment]
Hi thanks for your interest! Yep, the complete source for MAME 0.139 is included in this repo, and if you wanted to make changes to the main mame source, you'd need to make your changes and rebuild the libmamearm64.a file using `make`.

I'll consider adding a transparency slider for the full screen controls in settings - that wouldn't be too hard to do I think. Thanks!

**Comment by yoshisuga** [comment]
Added an opacity slider - its in the 2nd option in Settings -> Game Input.

**Comment by rslkr** [comment]
Hi Yoshisuga Thanks for the opacity slider I tested it's working great. May I suggest something about opacity slider.
Can you enlarge the ''Opacity (Full Screen)'' section and put the slider below of it (Portrait mode 'iphone7' slider covers part of the written). Or when you select the section it can open next page to slider. Also slider looks tiny Its a bit difficult to adjust. Can you make the slider longer than this one? e.g. Full size slider on a portrait mode should be enough.
There are some problems in this repo:
1- Skin section in Settings is still missing! ( Maybe you removed it for a reason...)
2- There were supposed to be ''Soft Reset'' and ''Service'' on the Mame Config Menu list. I was using your previous repo and They were on the Mame Config list before. (Maybe one year ago) Those are very useful options, some games need Soft Reset, by Service easy access to game's setting.
By the way I finished the On/Off color its working I uploaded uimenu.c 
Please don't get me wrong or made at me. Because of this magnificent Mame4ios I registered to the Github. 
Thank you.
