### ISSUE TITLE
library not found for -lmamearm64

### ISSUE THREAD

**Issue by ugomor1970** [yoshisuga/MAME4iOS#271]
I have this issue when i trying to build 

could someone help me ?  

XCODE VERSION 12.3

**Comment by ugomor1970** [comment]
Showing All Messages
Ld /Users/ugomorini/Library/Developer/Xcode/DerivedData/MAME4iOS-gifjhtsrgmrcgjhfdkzypvaawrbq/Build/Products/Release-iphoneos/MAME4iOS.app/MAME4iOS normal (in target 'MAME4iOS' from project 'MAME4iOS')
    cd /Users/ugomorini/Downloads/MAME4iOS-2020.13/xcode/MAME4iOS
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios12.4 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk -L/Users/ugomorini/Library/Developer/Xcode/DerivedData/MAME4iOS-gifjhtsrgmrcgjhfdkzypvaawrbq/Build/Products/Release-iphoneos -L/Users/ugomorini/Downloads/MAME4iOS-2020.13/xcode/MAME4iOS/../.. -L/Users/ugomorini/Downloads/MAME4iOS-2020.13/xcode/MAME4iOS/MAME4iOS -L/Users/ugomorini/Downloads/MAME4iOS-2020.13/xcode/MAME4iOS -F/Users/ugomorini/Library/Developer/Xcode/DerivedData/MAME4iOS-gifjhtsrgmrcgjhfdkzypvaawrbq/Build/Products/Release-iphoneos -filelist /Users/ugomorini/Library/Developer/Xcode/DerivedData/MAME4iOS-gifjhtsrgmrcgjhfdkzypvaawrbq/Build/Intermediates.noindex/MAME4iOS.build/Release-iphoneos/MAME4iOS.build/Objects-normal/arm64/MAME4iOS.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/ugomorini/Library/Developer/Xcode/DerivedData/MAME4iOS-gifjhtsrgmrcgjhfdkzypvaawrbq/Build/Intermediates.noindex/MAME4iOS.build/Release-iphoneos/MAME4iOS.build/Objects-normal/arm64/MAME4iOS_lto.o -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/ugomorini/Library/Developer/Xcode/DerivedData/MAME4iOS-gifjhtsrgmrcgjhfdkzypvaawrbq/Build/Intermediates.noindex/MAME4iOS.build/Release-iphoneos/MAME4iOS.build/Objects-normal/arm64/MAME4iOS.swiftmodule -framework MultipeerConnectivity -lcompression -framework Metal -framework CoreServices -framework IntentsUI -framework CFNetwork -lc++ -framework Intents -framework GameController -framework CoreBluetooth -framework CoreFoundation -framework AudioToolbox -framework QuartzCore -framework WebKit -framework AVFoundation -framework UIKit -framework Foundation -framework MetalPerformanceShaders -framework CoreGraphics -framework CloudKit -framework GameKit -lmamearm64 -lz -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/ugomorini/Library/Developer/Xcode/DerivedData/MAME4iOS-gifjhtsrgmrcgjhfdkzypvaawrbq/Build/Intermediates.noindex/MAME4iOS.build/Release-iphoneos/MAME4iOS.build/Objects-normal/arm64/MAME4iOS_dependency_info.dat -o /Users/ugomorini/Library/Developer/Xcode/DerivedData/MAME4iOS-gifjhtsrgmrcgjhfdkzypvaawrbq/Build/Products/Release-iphoneos/MAME4iOS.app/MAME4iOS

ld: library not found for -lmamearm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mrjschulte** [comment]
Hi, did you run the relevant "_make_" script in a terminal shell in the root directory of the project  before attempting to build the app?

**Comment by ugomor1970** [comment]
yes but I have this error :
MacBook-Pro-3:MAME4iOS-2020.13 ugomorini$ ./make-ios.sh
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
MacBook-Pro-3:MAME4iOS-2020.13 ugomorini$ 

After have that message : 

“MAME4iOS” is a project downloaded from the Internet. Are you sure you want to open it?

Trust and open , I open it !!

**Comment by mrjschulte** [comment]
Are the xcode command line tools
Installed?

**Comment by ugomor1970** [comment]
I just installed the Xcode command line tools : i re-try to build but always the same error : 

ld: library not found for -lmamearm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fmarquez** [comment]
I had the same issue. Just clean the build (shift + cmd + K) in Xcode and then re-run the relevant make script in terminal. The library will be created in the root directory

**Comment by ugomor1970** [comment]
Nothing to do 

I tried to clean but nothing .  !! The same error : 

ld: library not found for -lmamearm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fmarquez** [comment]
It sounds then like an issue with the command line tools. Even if the tools were installed, if there were previous versions and/or home-brew installations it could be that is pointing to the wrong ones. Resinstalling the command line, and ensuring that the right version is being used will help here. In my case:

sudo xcode-select -switch /Applications/Xcode.app

You can verify in Xcode what command line version and path is being used. You can find details in this thread:

https://apple.stackexchange.com/questions/321858/xcrun-missing-installing-xcode-command-line-tools-not-fixing-issue

**Comment by ugomor1970** [comment]
Nothing to do , i Re-install Xcode. command line , but nothing : 

Always the same error

ld: library not found for -lmamearm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ugomor1970** [comment]
i have xcode Version 12.3 (12C33)

COMMAND LINE TOOLS XCODE 12.3 (12C33)

**Comment by ugomor1970** [comment]
Finally I have installed the mame4ios on my iPhone :  but , it doesn't work , it closes immediately !!!

**Comment by fmarquez** [comment]
Great, I think this issue can be closed then. I can confirm that it works on IOS and Mac with no issues. I suggest that you look at this closed issue about the particular problem you are facing, regarding the crashes on IOS when starting up: https://github.com/yoshisuga/MAME4iOS/issues/270
