### ISSUE TITLE
change root MAME4mac root directory

### ISSUE THREAD

**Issue by chinarut** [yoshisuga/MAME4iOS#273]
I got access to a more modern mac and just tried MAME4mac for the first time today and kudos!  I can really appreciate how much Catalyst preserves the iOS UI I’ve known and loved for the l last few months on my iPad Pro.

I do notice MAME4mac treated the ~/Documents folder at its root directory which created quite a bit of clutter.

Is the root directory user configurable?  I didn’t see anything rummaging around Settings.

At the very least, I would prefer if the app used ~/Documents/MAME4mac by default next to existing RetroArch, Zoom, and other app folders.

Ideally, I’d like to relocate the root folder outside ~/Documents as I need to preserve limited iCloud space for personal documents.

**Comment by ToddLa** [comment]
This was fixed in PR #269. Are you building yourself or grabbing a release?

**Comment by chinarut** [comment]
I grabbed the 2020.13 release.

I will build from scratch & reopen this issue if needed and assume I won't have any issues.  thank you @ToddLa!

**Comment by chinarut** [comment]
looks like I might have to wait for the official build for 2020.14 to be published as a binary.

A personal development team (I assume the Apple sanctioned name for a free developer acct) does not support Push Notification and iCloud capabilities so the build won't begin in Xcode:

`Personal development teams, including "<name>", do not support the iCloud and Push Notifications capabilities.`

I'm also not clear if the command line build in part I completed - it created libmamearm64-mac.a and I have these what I think are warnings from ranlib?

```
Archiving libmamearm64-mac.a...
/Volumes/Apps/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmamearm64-mac.a(sh2drc.o) has no symbols
/Volumes/Apps/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmamearm64-mac.a(rsp.o) has no symbols
/Volumes/Apps/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmamearm64-mac.a(emucore.o) has no symbols
```

**Comment by chinarut** [comment]
good news - I was able to build the executable by deleting the 2 capabilities (I later found the extra MAME4mac.sandbox.entitlement file) and now find my root directory here:

`$HOME/Library/Containers/$ORG_IDENTIFIER.mame4ios/Data/Documents
`
thanks 💯
