### ISSUE TITLE
need edge protection in case touch mistake

### ISSUE THREAD

**Issue by fastfading** [yoshisuga/MAME4iOS#275]
when swipe up from bottom ,  ios will quit current game.
this will cause touch mistake ,  when you control the dpad.

Below Reference would help on this
https://stackoverflow.com/questions/46988469/how-to-enable-edge-protect-in-iphone-x
https://github.com/native-toolkit/sdl/blob/08a0279ee403b1c3c5b76f34682a389beaa73331/src/video/uikit/SDL_uikitviewcontroller.m#L222-L238

```
// setNeedsUpdateOfScreenEdgesDeferringSystemGestures
// preferredScreenEdgesDeferringSystemGestures
-(UIRectEdge)preferredScreenEdgesDeferringSystemGestures
{
    return UIRectEdgeAll;
}

```

**Comment by ToddLa** [comment]
This is what the code does now..

```
- (UIRectEdge)preferredScreenEdgesDeferringSystemGestures
{
    return UIRectEdgeBottom;
}
- (BOOL)prefersStatusBarHidden
{
    return YES;
}
-(BOOL)prefersHomeIndicatorAutoHidden
{
    return g_device_is_fullscreen;
}
```

**Comment by ToddLa** [comment]
We allow a swipe from the bottom so user can swipe to go back to the Home Screen, we also hide the indicator when fullscreen. 

I am assuming the dpad is far enough away from the home indicator to have a conflict.
