### ISSUE TITLE
disable  dlopen

### ISSUE THREAD

**Issue by fastfading** [yoshisuga/MAME4iOS#278]
how to disable 
dlopen(), dlsym()
which is used in the source code

I see, define 
STEAMCONTROLLER_NO_PRIVATE_API

**Comment by fastfading** [comment]
and openURL   api

seems this all related to the webserver feature.

can we build a branch to remove this webserver .   
upload roms  other way

**Comment by fastfading** [comment]
seems related to 
  void * IOKit = dlopen("/System/Library/Frameworks/IOKit.framework/IOKit", RTLD_NOLOAD);

can we import IOKit in project

**Comment by ToddLa** [comment]
This app will be rejected by the AppStore because it is an emulator. 

I added that `#define` to the `SteamController` code, so in a normal build of `MAME4iOS` we don't use dlopen, and we also dont Swizzle.
