### ISSUE TITLE
MAME4tvOS menu behaves unexpectedly

### ISSUE THREAD

**Issue by Motko222** [yoshisuga/MAME4iOS#279]
Hi guys,
I am experiencing strange behaviour of MAME4tvOS menu.

On Siri remote, MENU button should show MAME4tvOS menu - this is not happening for me
On Magic Keyboard, most of the buttons will open MAME4tvOS menu before the action is passed through.
"P" (pause) and TAB (MAME menu) works as expected.
On 8bitdo controller, all buttons will open MAME4tvOS menu (keyboard or iCade mode)

Any advise please? Thanks a lot.

**Comment by ToddLa** [comment]
Custom build, or release version?

What tvOS version?

I saw some weird Siri remote stuff in 13.4, bit nothing as strange as what you describe.

**Comment by ToddLa** [comment]
You have all those devices (keyboard, 8bitdo, etc) connected at the same time? What happens if you only have the Siri remote??

**Comment by ToddLa** [comment]
Please let me know any details, this is weird. I will build and deploy the latest and see if i see any weirdness

**Comment by Motko222** [comment]
Release 2020.13
tvOS 14.3 on AppleTV 4th gen
Apple Wireless Keyboard A1314 4th gen
8bitdo SFC30 fw 3.0
Tried and the problem is present when I connect external devices separately (keyboard or gamepad). 
Siri menu problem is always present.

Thanks a lot for your help!

**Comment by ToddLa** [comment]
How do you sideload?

**Comment by Motko222** [comment]
Using Apple Configurator 2.

More info:
Tried Provenance and looks like iCade controller is working fine there.
Here goes more weirdness - loaded release 2020.12 and I got one more shot on what was going on. iCade controller was working fine, but with weird mapping - start was on B, A was on L. However, only till I summoned Mame4tvos menu (B+Y). Then the controller went mad and now every button opens menu.

**Comment by ToddLa** [comment]
Ok I will try out latest versions, and try a Bluetooth keyboard.....

**Comment by ToddLa** [comment]
Ok so minimal repro is
TV with 2020.12
Bluetooth keyboard, and Siri remote
...and things go wonky?
Does just the setup with only a Siri remote fail?

**Comment by ToddLa** [comment]
NOTE you can't use both a keyboard and a iCade device at the same time. `Settings` > `External Controler` applies to all keyboard devices. 

BUT in any case this should not cause any problems with the Siri Remote.

**Comment by ToddLa** [comment]
I just ran M4i on latest tvOS 14.3, and I am seeing a few weird things right away.
1. the Siri Remote is getting enumerated TWICE, so we think there are two game controllers.
2. the buttonMenu on the GCGameController object is not working, so you can summon the M4i menu, and are stuck.

this is not just a M4i issue, a standalone [GameController test app](https://github.com/ToddLa/controllers-for-tvOS) is seeing this too.

**Comment by ToddLa** [comment]
I think I figured this out, tvOS 14.3 broke a few things

1. No more access to the Xbox GUIDE (aka home) button, the system now reserves that to bring up control center always. 
2. HOME button on Siri Remote does not generate a GameContoller event anymore, you need to use pausedHandler or GestureReconizer??? So you could not get the menu with Siri Remote. 
3. On an iCade or Keyboard if you hit SELECT and COIN at same time that will bring up the M4i menu, but in some cases the keys can get "stuck down" causing the menu to popup again and again and again. 

I will do a PR, and have MrJs test on a tvOS 13 device.

**Comment by ToddLa** [comment]
@Motko222 do you want a IPA to test this? Or can you build a PR?

**Comment by Motko222** [comment]
Thanks Todd, just wanted to send you update. It is indeed like COIN+START gets stuck. I have managed to undo it couple of times, but could not reproduce it. Only way helps I know of is force-close.
Keyboard is working fine when used alone, it is the iCade controller causing this.

**Comment by ToddLa** [comment]
Yup my PR will prevent the COIN+START getting stuck, and fix the Siri Remote MENU.

**Comment by Motko222** [comment]
> @Motko222 do you want a IPA to test this? Or can you build a PR?

IPA please

**Comment by ToddLa** [comment]
@Motko222 try this (I hope I exported it right....)
https://1drv.ms/u/s!Ak3z6hQL-6nv4lotKfR0svVLjnRU?e=bvuY88

**Comment by Motko222** [comment]
Hi @ToddLa, works okay:
Siri remote - M4i menu opens as expected
8bitdo gamepad - M4i menu does no get stuck. However, all buttons on controller are mixed up. Needed to re-map them all.
Thanks a lot for your support!

**Comment by ToddLa** [comment]
The 8bitdo can run in a few modes, choose iCade compatible, and select `iCade or compatible` in M4i settings.

**Comment by Motko222** [comment]
I thought I did that - "iCade mode" on controller and "iCade or compatible" in M4i settings.

**Comment by ToddLa** [comment]
@Motko222 I am curious, did the entitlements survive your side load?

* Is there a TopShelf interface?

* are there options to Import and Export from iCloud in `Settings`?

**Comment by ToddLa** [comment]
> I thought I did that - "iCade mode" on controller and "iCade or compatible" in M4i settings.

The key mappings in M4i are old and designed for the original ThinkGeek iCade. I assume the dpad works fine, and you just need to remap the buttons?

**Comment by Motko222** [comment]
> The key mappings in M4i are old and designed for the original ThinkGeek iCade. I assume the dpad works fine, and you just need to remap the buttons?

Correct.

**Comment by Motko222** [comment]
> > I thought I did that - "iCade mode" on controller and "iCade or compatible" in M4i settings.
> 
> The key mappings in M4i are old and designed for the original ThinkGeek iCade. I assume the dpad works fine, and you just need to remap the buttons?
> 
> The best way to use a 8bitdo is in Xinput mode, and connect it to you iOS/tvOS device in the `Assesibility > Switch Controls`

I was not able to make this work with my 8bitdo model. It does not appear to have "Xinput mode" with neither legacy or new firmware.

**Comment by Motko222** [comment]
> * Is there a TopShelf interface?
> * are there options to Import and Export from iCloud in `Settings`?

Nope, MAME logo on the topshelp.
And nope, no iCloud export/import.

**Comment by ToddLa** [comment]
...too bad Apple Configuator sideload must mess up entitlements.

**Comment by ToddLa** [comment]
@Motko222 please verify this is all fixed and good, and close

**Comment by Motko222** [comment]
All good here, thanks!
