### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by mikesalz** [yoshisuga/MAME4iOS#283]
Hello!  This is probably just something dumb that I am doing.  But I cannot build for tvOS.  No matter what I do, it stops at this screen.  Is there something I am doing wrong?  Thanks in advance!

![image](https://user-images.githubusercontent.com/46855061/106407129-403aa300-6409-11eb-9380-0b54b89094ef.png)

**Comment by mikesalz** [comment]
A little more info, which may be helpful.  I removed the iCloud and Push capabilities because I was receiving this error:

Personal development teams, including "XXXXXXXX", do not support the iCloud and Push Notifications capabilities.

So maybe the removal of those capabilities is what caused this error?  But how can I get past the initial issue of not supporting iCloud and Push?  Can this app only be used if you have a paid developer's account?

**Comment by ToddLa** [comment]
You must set the ORG_IDENTIFIER to some thing like XXX.YYYY (ie com.example, or app.foobar, etc.....)

**Comment by ToddLa** [comment]
PR #284 should clean this up.
