### ISSUE TITLE
Game Controller Cleanup

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#285]
The game controller code needs some cleanup, this issue attempts the following....
* re-factor the `GameControllerSetup` code so it is not a big hairy single function.
* directly poll game controllers from the MAME thread, this way a button press should have less latency.
* support the iOS 14 (and maybe tvOS 14) support of controllers with three command buttons, OPTIONS, HOME, MENU.
* Handle the original Nimbus controller better.  all the buttons on the Nimbus are analog, and confuse the hell out of the current code to handle menu modifiers.
* change the MENU modifier buttons for Save/Load state so you don't have to bring up the M4i in-game menu causing a PAUSE and game play disruption.
* make the Siri Remote buttons be 🅐 and 🅑 (not 🅐 and 🅧) MAME considers 🅑 `BUTTON_2`
* MENU combo button "quick help"

## New MENU combo buttons

| | |  
-|-
MENU           |Open MAME4iOS MENU   
MENU+L1     |Player 1 Coin                 
MENU+R1     |Player 1 Start               
MENU+L2     |Player 2 Coin                
MENU+R2     |Player 2 Start               
MENU+X       |Exit Game                 
MENU+Y       |Open MAME menu   
MENU+UP        |Load State ①                
MENU+DOWN  |Save State ①               
MENU+LEFT     |Load State ②                
MENU+RIGHT  |Save State ②      

## MENU combo button, quick help
If you hold down `MENU` for a fixed amount (ie like 1sec) a "help screen" will popup on the screen (iOS and tvOS) showing the user what combo buttons are available. This is very similar to what [happens on an iPad](https://support.apple.com/en-us/HT211096) if you hold down ⌘.  Unlike the in-game menu, this quick help does not pause the game and goes away instantly when `MENU` is released.

![IMG_C71D7E522832-1](https://user-images.githubusercontent.com/4494698/108009033-9afdfe00-6fb6-11eb-91f7-f16032f12df7.jpeg)

**Comment by Alexck002** [comment]
That’s a nice improvement  on MAME4IOS UI keep it up

**Comment by jpbedoya** [comment]
What if the Helper screen is part of the menu screen? I feel like most people will not discover it otherwise - press and hold of Menu is not a common behavior. There's plenty of real estate available on the TV and iPad to add it below the menu options.

**Comment by ToddLa** [comment]
All these options are already in the M4i menu, this quick help is just a reminder of what the controller button mappings are.

**Comment by ToddLa** [comment]
![image](https://user-images.githubusercontent.com/4494698/107718340-9077f780-6c8a-11eb-9937-0d3b6ca4994c.jpeg)

**Comment by ToddLa** [comment]
The quick help menu is just an optional "niceity" the help file already has a list of the mappings. Just a UI extra I am playing with.

**Comment by jpbedoya** [comment]
This is what I was thinking (it's ugly) - you can also see it when you press and hold if you want, but it's an extra Information section in the Menu

![image](https://user-images.githubusercontent.com/6699756/107719423-1137f300-6c8d-11eb-9a33-f6d4a7befa82.png)

**Comment by ToddLa** [comment]
Where would that go on an iPhone screen? Need to only display on tvOS or on iPad (non windowed)

And also, that is not really an option, the in-game menu is just a system Alert, we can't (easily) display anything next to or on top of it....

**Comment by ToddLa** [comment]
Now that I used the dpad for Load/Save state we have 🅐 and 🅑 free for two new combo options....

# Ideas?

* MAME Pause
* MAME Reset

**Comment by jpbedoya** [comment]
My proposal was for iPad and tv only - no iphone.  Didn't realize it was using the native alert system, then it's not worth the extra effort to build a new screen for this at this point. 

re: Combos A and B, Pause and Reset are good with a confirmation after Reset like Exit :)

I can't think of other options that would be used somewhat frequently

**Comment by ToddLa** [comment]
hey @jpbedoya how does this look.....
![Simulator Screen Shot - Apple TV 4K - 2021-02-15 at 14 17 27](https://user-images.githubusercontent.com/4494698/107997830-a5110400-6f98-11eb-8bff-820d394319f1.png)

**Comment by jpbedoya** [comment]
I like it - I would suggest adding a title above (like your previous mock) to help give context on what those text labels mean. Here's an idea: "Button + Menu Shortcuts"

**Comment by ToddLa** [comment]
Yea I had a title and instruction text, BUTTTTTT, the in-game menu can get larger (for example 4 player games....) so I needed to keep it small (yea I could put two HUDs on the left and the right, but that is getting a little complex, for a quick hack)

also I found it confusing to display *all* possible menu combos, but they don't work in the current context (the alert menu uses dpad and A,B....)

so what I did *instead* is show a subset of the combos, the ones that can work **right now** while the in-game menu is up

![Simulator Screen Shot - Apple TV 4K - 2021-02-15 at 17 42 37](https://user-images.githubusercontent.com/4494698/108008490-52921080-6fb5-11eb-912a-40a2d1047cb9.png)

**Comment by ToddLa** [comment]
PR #286 has this operational if you want to grab it and check it out!
