### ISSUE TITLE
Games in mirror view

### ISSUE THREAD

**Issue by mooznet** [yoshisuga/MAME4iOS#294]
There is some issue on games with lightguns.
When the "Use Metal" in settings is enable.
Games like Space Gun and Terminator 2 looks like a mirror...

Thanks
![IMG_0879](https://user-images.githubusercontent.com/79001455/110216654-f2f29b00-7eb8-11eb-9bb0-a4931bad2759.PNG)

**Comment by ToddLa** [comment]
This has been [fixed](https://github.com/yoshisuga/MAME4iOS/commit/dd97343161d95c182a6652e69430ff0951ab9fbd)

But I don't think it is in a release yet.

**Comment by ToddLa** [comment]
fixed in the 2021.5 release
https://github.com/yoshisuga/MAME4iOS/releases/tag/2021.5
