### ISSUE TITLE
Use InfoHUD for in-game menu

### ISSUE THREAD

**Issue by ToddLa** [yoshisuga/MAME4iOS#296]
## UIAlertController based in-game menu.

Currently `MAME4iOS` uses a standard `UIAlertController` for the in-game menu.

![image](https://user-images.githubusercontent.com/4494698/110743181-7d563a00-81ec-11eb-9020-1c5d1a8ebe4f.jpeg)

This has a few disadvantages
* takes over the whole screen on tvOS
* limited number of items, because it is only a single column it can only hold a few items before it is taller than the screen (especially on tvOS)

## InfoHUD based in-game menu.

I propose we use the InfoHUD code to make a in-game menu like this...

![image](https://user-images.githubusercontent.com/4494698/110742981-2a7c8280-81ec-11eb-9159-c5eecdba9283.jpeg)

It can hold many more items, and show/remind player about the menu combo buttons.

The items with button backgrounds are normal buttons, the player can navigate to one of them with the `dpad` and press 🅐 to select. 🅑 or `menu` will dismiss the menu.

Items without buttons backgrounds, are also buttons, but you can also perform the action just by pressing the associated controller key. Or you can do these actions without the menu at all by hitting `menu`+`button` (or `button` + `menu`). The menu is a kind of "quick help" to remind that you can do those actions without the in-game menu. 

NOTE The `dpad` items (Load, Save, ...) must be selected and 🅐 because the `dpad` is used to navigate the menu. 

## Only for a game controller?

My thinking is that this in-game menu will only appear when using a game controller (or Siri Remote). It will replace the current "quick help HUD" (see #285) becoming both a "quick help" HUD *and* a in-game menu.

We can also use a version of this HUD for the in-game menu when tapping/clicking on the `MENU` on-screen button.  We would need to remove the Game Controller specific items, and make them normal buttons.

## To PAUSE or not to PAUSE?

Currently with the `UIAlertController` in-game menu we hard-pause/suspend the `MAME` thread while it is active. Should we still do this for the menu HUD? Or just leave the game running?

**Comment by mrjschulte** [comment]
Pause MAME when the menu initially comes up, but allow for an option to Un-Pause MAME whilst doing Shader Editing :)

**Comment by yoshisuga** [comment]
This looks great! I think you should use the in-game menu even when a controller is not connected. We can get rid of the alert controller - the infohud looks so much better!

**Comment by ToddLa** [comment]
I need to wrap InfoHUD in a UIViewController to use it as general menu, but that is not hard. And it makes InfoHUD even more versatile.

**Comment by ToddLa** [comment]
https://media.discordapp.net/attachments/684051607310172167/820275986951962684/image0.jpg

**Comment by mrjschulte** [comment]
This has all been merged, can we close this? @ToddLa ?

**Comment by ToddLa** [comment]
Leave them open until a release
