### ISSUE TITLE
crash on tvos13 with mfi controller

### ISSUE THREAD

**Issue by spacex15** [yoshisuga/MAME4iOS#299]
HI

i experienced a crash under tvOS13 with my controller

the check availability for ios 14 0 only should be changed to the following inn EmulatorController.m
if (@available(iOS 14.0, tvOS 14.0,*)) 
instead of only checking iOS 14

Thanks

**Comment by mrjschulte** [comment]
Hi,

What version of Mame4ios are you using and did you compile it recently from source?

**Comment by spacex15** [comment]
2021.5
and yes then i recompiled from source to find the problem

**Comment by ToddLa** [comment]
I will look at this @mrjschulte you run on tvOS 13 weird you did not see this crash. 

I will audit all the availability checks to make sure right thing is happening

**Comment by ToddLa** [comment]
Yea the SDK does not have some APIs marked right, else we would get a build error!

**Comment by ToddLa** [comment]
@spacex15 I assume your crash was in installMenuHandler trying to set preferredSystemGestureState? If so I added fix to PR #300

**Comment by spacex15** [comment]
exactly

thanks

**Comment by mrjschulte** [comment]
Merged and case closed.
