### ISSUE TITLE
MFI Controller improvements

### ISSUE THREAD

**Issue by DarrenBranford** [yoshisuga/MAME4iOS#3]
Hi. I also grabbed the source from Les Bird and made my own optimisations, including a complete reworking of the MFI controller code. I was going to make my own repo when I came across yours so, if you don't mind, I would like to drop my MFI controller implementation in to your project.

Some of the main things that I implemented was real twin thumbstick support and proper connect/disconnect handling.

There is a strange naming convention due to how mame handles the input "devices":

MFI controller 1 will have joy 1 X/Y and joy 2 X/Y while MFI controller 2 will have joy 3 X/Y and joy 4 X/Y and so on.

Also, now that you have load/save states from a menu, you might want to remove the hotkeys for those (coin + a and start + a)

**Comment by yoshisuga** [comment]
Hi Darren! I did implement twin stick support, but feel free to make a pull request. I'm totally fine with replacing my implementation with yours if it's better. And I'm curious to see another implementation and welcome it :)

I didn't know there are hotkeys for load/save states - i've maybe only accidentally run across them during gameplay. Feel free to make a PR to remove them :)

Thanks for the feedback!

**Comment by DarrenBranford** [comment]
Closed as PR is merged. #4
