### ISSUE TITLE
Shader Slider Ux Tweaks

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#302]
In working with #301 and testing the new HUD functionality on tvOS it would be great If the following could be considered :

General Ux for selecting and interacting with Sliders on tvOS:

1. Use Up+Down to Focus/Skip through the various Shader parameters
2. Use a "Click" to Select/Anchor onto the the Shader parameter slider you want to change
3. Once Selected/Anchored, you can use the L/R swipe gestures to affect the actual slider values
4. Once happy with the change you can use a "Click" to confirm the new values for the parameter and exit back to the 1. state.

Also, currently a single L/R swipe action that travels across the entire Magic Remote navigation area currently only does single slider increments, it would be great if the left+right swiping was a smoother slider "scrolling" feedback experience. It's a little hard to "tweak" the look of the shader as it stands currently but once the above Ux is implemented this will be easier. Right now I tend to navigate off/away from the slider I am trying to tweak to easily with the L+R swipe gestures.

- If making value tweaks on a shader those settings should be saved as the new values for the shader upon exiting the game. This would be for a global shader setting save, we are not looking at saving a per game set of shader parameter values.
- Add an option to easily "Reset" the shader values to their respective defaults.
- Add in a visual "Tick" mark to the Shader slider to show the default value for a slider in as defined by the Shader author.

**Comment by mrjschulte** [comment]
It would be great if when we are in the Shader editor it would allow us to Select/Focus and the Click on the current Shader name that's being edited and that action would take us to the Shader Selection Settings menu to change the Shader being edited.

**Comment by mrjschulte** [comment]
- Allow for a means to select the Shader Pre-sets in the HUD when editing Shader Slider Parameters.

**Comment by ToddLa** [comment]
> It would be great if when we are in the Shader editor it would allow us to Select/Focus and the Click on the current Shader name that's being edited and that action would take us to the Shader Selection Settings menu to change the Shader being edited.

There is a [gear] icon at top of HUD (literally right above the Shader name) that will take you to Settings, then it is one more click to choose a Shader.

**Comment by ToddLa** [comment]
PR #301 has done (most) of these...

* you can show/hide the `HUD` on tvOS via `Settings`, or with `MENU+A` on a controller.
* MAME will not see input from Siri Remote when `HUD` is up.
* you can use the Siri Remote to navigate the `HUD` and change Shader parameters.
    - tap to move UP/DOWN/LEFT/RIGHT
    - swipe to move UP/DOWN or fine control of a parameter
* Shader parameters are saved globally in `iOS/ShaderOptions.json`
* `[Reset Defaults]` button in the Shader `HUD`.

what this does not do
* no tick mark for default value, `UISlider` does not have anything like that....
* no way in the `HUD` to select a different Shader or a Shader pre-set, you gotta go into `Settings` for that.
