### ISSUE TITLE
tvOS Ui / Menu tweaks

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#309]
Some suggested tweaks for the experience on tvOS:
- Remove System and Year from "small" layout view.
- Limit game titles to 3 lines on "small" layout view. 
- Reduce Font size used.
`#define CELL_TITLE_FONT         [UIFont boldSystemFontOfSize:24.0] `
to 
`#define CELL_TITLE_FONT         [UIFont boldSystemFontOfSize:20.0]`
- Add SuperSampling to Game Tiles to smooth out the "crunchy look" of them.

**Comment by ToddLa** [comment]
Font size and text info changes easy, super sample might be a bit non-trivial, I will take a look

**Comment by ToddLa** [comment]
The only tweak to #311 to consider might be to show “Manufacter and Year” but also limit to 3 lines. This way games with short descriptions will get “all info” and only the multi-line long descriptions will get cut off.

**Comment by ToddLa** [comment]
Also the line spaceing eight want to be increased, the Manufacturer and Year added a little buffer, looks a tad tight on iPhone or iPad.

**Comment by ToddLa** [comment]
As for the scaling/crunchy issue There are two code paths..
One when the title image is letterboxed or pillarboxed, and one not.

**Comment by mrjschulte** [comment]
Great Pr @ToddLa ! 
The extra filtering on the tiles really helps clean up the appearance of the Tiles when shifting focus on tvOS. 
Let's work on setting the `#define SECTION_LINE_SPACING    48.0 ` for tvOS as well.
