### ISSUE TITLE
Touch Stick Ways ''Auto'' Issue

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#320]
Hi ToddLa,
Before OSD changed, touch stick in the Settings/Game Input/ STICK & DPAD Ways ''Auto'' was working for all types of games properly.(iOS)
Now, when I select ''Auto'' for 8-Ways games only work for 4-Ways!!!
Auto for 2-Way and 4-Way Games, They seem OK.

**Comment by ToddLa** [comment]
@rslkr please give me a specific 8way game that is failing, and I will check it out!
yea I touched the input auto detect stuff, I can see 8way breaking.

**Comment by rslkr** [comment]
Thanks for reply ToddLa,
We all want the latest MAME so I was expecting this kinda things.

It appears all fighting games MK series, SF2 series, Dino, Final Fight, 3 Wonders, Street Hoop

**Comment by ToddLa** [comment]
I got SF2 in my default set, will check right now....

**Comment by ToddLa** [comment]
fixed in PR #324

**Comment by rslkr** [comment]
All good.Thank you.
