### ISSUE TITLE
Mark ''Favorite Games''

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#321]
There was a feature in old mameui, When I add a game to ''Favorite'' Game's name turn blue.
Now with this ''new frontend ui'' can we have this option?
Change the Game's name color instead of white or better yet, add a red little heart on the Game's Title/Image.
This is improvement and that would be useful.

**Comment by ToddLa** [comment]
@rslkr are you talking about the "DOS" MAME UI, or the native iOS UI?

all your fav games show up in a Section at the top called "Favorite Games" but adding a badge or changing the text color is possible too.

**Comment by rslkr** [comment]
On the native iOS UI , adding to "Favorite" and "Unfavorite " And also ''Remove from Recently Played'' these are super useful.Thanks.

> adding a badge or changing the text color is possible too.
Yes please If it is possible, so I would know that when I scroll down or up the screen I already added that game.

**Comment by rslkr** [comment]
I just made this with paint.
![Untitled](https://user-images.githubusercontent.com/46307397/117997539-64057180-b386-11eb-9976-8092f71cf6cc.jpg)

 Nah This Doesn't look good!!!
Changing the text color would be better solution, red or yellow.But there are two type of names. Rom name and  actual game name.

**Comment by ToddLa** [comment]
What about a badge on game when it is new?

**Comment by ToddLa** [comment]
iOS uses a subtle "blue dot" when a app get an update, maybe the same thing would work for new and favorite in M4i?

Having a big badge on the title image, might not look so nice in all cases???

![image](https://user-images.githubusercontent.com/4494698/118003335-5657d980-b2fd-11eb-8318-9e3e1f17145d.jpeg)

**Comment by rslkr** [comment]
Yes something like that would work.
The point is here, identified the "Favorite Games" without disturb the users.

**Comment by ToddLa** [comment]
What about using a star vs a heart?

And is a game considered "new" if it was just installed *today*? I don't think I want to keep a database of the last play time of every game!

...or don't bother with "new" badge??

**Comment by rslkr** [comment]
Yes Star use for favorite as well not sure how it looks on the titles?
Is it hard change the text color? Can you add them both?
''New'' mean you also add to favorite that new game?

**Comment by ToddLa** [comment]
This is what I did in PR #325.....

![image](https://user-images.githubusercontent.com/4494698/118045087-57ecc600-b32c-11eb-8d5b-7501f49618fe.jpeg)

Look good?

**Comment by rslkr** [comment]
Heart on the title was a bad idea!!!
This looks nice and neat, way better than I thought.
👍

**Comment by rslkr** [comment]
Sorry I had to test it before it merge.
There is a ''info'' icon on the HUD. It shows game name.
Can you add this ''blue star'' on the HUD next to game name please?

<img width="568" alt="Play Pang" src="https://user-images.githubusercontent.com/46307397/118069808-2e917000-b3e8-11eb-97e7-693db9652aa4.png">

**Comment by ToddLa** [comment]
We don't have the fav list loaded when the HUD asks for the info text, it is possible to do (HUD displays attributedTEXT) but not trivial. And HUD text not clickable either.....

**Comment by rslkr** [comment]
That's Ok. This request is done.
Thank you so much ToddLa.
