### ISSUE TITLE
Support ''Merged ROMS'' with latest MAME

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#328]
Hi, ToddLa
Thanks for updated to the MAME 229.

First this is how I build:
Download from your Fork this:  ios-osd branch.
run at Terminal this: ./make-ios.sh
It took around 2 hours to build ''libmame-ios.a'' file.
I tried to run at Terminal this: ./get-libmame.sh ~/MAME4iOS-master    (my desktop path)
And then Terminal shows this: USAGE: ./get-libmame.sh [ios | tvos | mac | all] [source]
Terminal did not build anything.
I simply copied the ''libmame-ios.a'' file to MAME4iOS-master root folder and run with Xcode 
Build successfully. 👍 

There are 3 type of romset  https://docs.mamedev.org/usingmame/aboutromsets.html (url)
I have Merged Roms (229), which is more benefit to users... all in one, save space etc.
I added my roms to Mame4ios but it only shows the **Parrent** roms!!!
I assume Mame4ios cannot separate that whatever inside the zip file! Especially with new the native iOS UI

Is there any way to fix this issue?

Example Rom: sf2ce.zip size:43 mb including all clones.

**Comment by ToddLa** [comment]
> It took around 2 hours to build 

Yea `MAME` is a beast to build! It takes 3hrs on my MBP! (But only 30min on new M1 MBA).

**Comment by ToddLa** [comment]
> I tried to run at Terminal this: ./get-libmame.sh ~/MAME4iOS-master (my desktop path)

Sorry you must not be familiar with the `~` (it is a old *nix thing).  `~` is short hand for your *user folder* so `~/Desktop` would be your desktop folder. So the right path to use would have been `~/Desktop/MAME4iOS-master`

**Comment by ToddLa** [comment]
> I have Merged Roms (229), which is more benefit to users... all in one, save space etc.

Yea `MAME4iOS` has to do some special stuff for merged roms. I was just looking at this issue wrt software lists.

Does that same merged rom on the command line version of `MAME` show all the clones? (When the Filter is Available?)

I will look into this, it is an issue that needs resolved!

**Comment by rslkr** [comment]
Build time isn't problem for me. But you as a developer have to do this over and over for testing!!!
It must be hard for you...

> Sorry you must not be familiar with the ~ (it is a old *nix thing). ~ is short hand for your user folder so ~/Desktop would be your desktop folder. So the right path to use would have been ~/Desktop/MAME4iOS-master

I tried all of them still Terminal shows this: USAGE: ./get-libmame.sh [ios | tvos | mac | all] [source]
But doesn't matter. If the point is here to get ''libmame-ios.a'' file all I have to do is copy and paste.
I guess I can skip this step?

> Does that same merged rom on the command line version of MAME show all the clones? (When the Filter is Available?)
I will look into this, it is an issue that needs resolved!
MAME has a concept of a "ROM Audit", F1 and SHIFT+F1 in the command line version.

On the desktop MAME, I can find the any rom and clones, using the search section or select the Clones on the side bar
without doing the "ROM Audit"
And also using the Mame4ios Dos UI: It shows all rom/clones I can select any rom but it is very difficult to find without mouse and keyboard! I know you do have a plan to add ''Keyboard''

**Comment by rslkr** [comment]
Here's another example rom: strhoop.zip
This is a ''NEO-GEO'' game, it cannot run without the ''neogeo.zip'' bios file.
(And thanks for the adding the ''Hide BIOS'' switch 'cuz This is not a game!)
But its on desktop version, first it shows Bios selection screen (Europe, Japan, US....) select and then start.

This is what I do for Non-Arcade games on the desktop:
a5200.zip Atari 5200
I add the unzip game(s) into to the 'a5200.zip'' file 
For example game: River Raid (1983) (Activision).a52
I click on the a5200 and it shows game list, I select game ''River Raid'' and after it shows ''Bios Selection'' screen and start.
But this process doesn't work for ''a2600''

This is how I run ''a5200'' on the the Mame4ios:
in the config Menu, I select ''File Manager/cartridge/roms/a5200/River Raid
Also I realized This game can run without ''hash/a5200.xml'' file

**Comment by ToddLa** [comment]
> On the desktop MAME, I can find the any rom and clones, using the search section or select the Clones on the side bar

*but* what happens if you set the filter to `Available` in the left side-bar?

Do you see Clones.

**Comment by rslkr** [comment]
I just check it on the desktop version YES

**Comment by ToddLa** [comment]
> Also I realized This game can run without ''hash/a5200.xml'' file

*YES* you must import the software list file into M4i for software based machines.

*NOTE* `MAME` comes with all the `hash` files, but that is 100MB, but `MAME4iOS` requires you to import only the files you plan to use.  I was clear about this in the README.  And I dont see this changing, we cant add 100MB to M4i, and most people only use a handfull of software based machines.

**Comment by ToddLa** [comment]
> On the desktop MAME, I can find the any rom and clones, using the search section or select the Clones on the side bar

`MAME4iOS` only shows you the games you have installed and can run, so it (should be) the same as the `Available` filter in the command line `MAME`.

If you want to see and search all 38,000+ machines, you need to run the `MAME UI`.

**Comment by ToddLa** [comment]
>  first it shows Bios selection screen (Europe, Japan, US....) select and then start.

Yea we need a way to select different `BIOS` and also `NTSC` vs `PAL` but that is another issue! Lets stay on `MERGED ROMs` in this issue.

**Comment by rslkr** [comment]
> If you want to see and search all 38,000+ machines, you need to run the MAME UI.

Of course not!!!
Only Available. Whatever I add to the MAME4iOS.

> Yea we need a way to select different BIOS and also NTSC vs PAL but that is another issue! Lets stay on MERGED ROMs in this issue.

Sure, you're right.

**Comment by ToddLa** [comment]
> I just check it on the desktop version YES

Good that means MAME is doing some sort of mini-audit for Clones, I will go find out.

Are you sure you did not do an Audit? Does a file named `mame_avail.ini` exist?

**Comment by rslkr** [comment]
> Are you sure you did not do an Audit? Does a file named mame_avail.ini exist?

When I first install MAME and run I played some clone.
But when you mentioned the Audit I did once for test later

**Comment by rslkr** [comment]
Sorry When I first install MAME I select Clones. That's how I played clones.
Available only shows parrents!!!

**Comment by ToddLa** [comment]
> Sorry When I first install MAME I select Clones. That's how I played clones.
Available only shows parrents

**GOOD** my understanding of how `MAME` works (as small as it is) is correct in this case.  I was worried I had to solve a mystery!

**BUT** that does not mean `MAME4iOS` can't be smarter than `MAME` when it comes to merged-roms. We can do *some magic* at `ROM` import time with merged-roms. I have already been thinking of this in the shower, I will have something for you to try "soon" (maybe a new branch)

**Comment by rslkr** [comment]
This is just sake of conversation about the Native iOS UI you made.
Long time ago I thought you find the way to get title/image from the roms.
Only way to do that using tile manager/ripper for rom (Long way) or get the snapshot from rom by running a game (easiest way).
But it turned out someone already did that and loaded his website and you added that website to MAME4iOS, pretty smart.

Here's my concern: Nothing lasts forever!!! That website may shutdown in the future or any time soon.
And probably that website does not have the entire MAME games titles. (for latest MAME)
I'd like ask to add a snapshot button on the HUD, but this snapshot button should be available and visible on the HUD when user need it. Activate in Settings to turn it on/off. Otherwise the HUD will get crowded again.
Snapshot text matches with game and add to titles folder by Mame4ios.
But as always If you don't like it ignore this please.

**Comment by ToddLa** [comment]
> I'd like ask to add a snapshot button on the HUD

I agree! But please open a new issue, we should try to keep an issue thread focused on a single issue.

**Comment by ToddLa** [comment]
@rslkr can you delete the above comment?

**Comment by ToddLa** [comment]
Hey @rslkr try my current `modern-MAME` branch. 

When you import a merged ROM it will "do stuff" so all the clones get seen as Available...

**Comment by rslkr** [comment]
Ok I will
modern -mame from MAME4ios?

**Comment by ToddLa** [comment]
Yes

**Comment by ToddLa** [comment]
PR #327 or modern-mame from my M4i fork

**Comment by rslkr** [comment]
Didn't work.
First I deleted MAME4Ios  and fresh install with xcode.
imported my 229 merged roms but doesn't show any clones!
Hide clones switch was off

**Comment by ToddLa** [comment]
Explain exactly how you "imported my 229 merged roms"

**Comment by rslkr** [comment]
From my desktop MAME 229 merged roms using the web server

**Comment by ToddLa** [comment]
For example I imported the puckman merged romset, and got like 50 clones, it was crazy!

**Comment by rslkr** [comment]
Yes I have that puckman merged romset and yes all clones in the zip file
Anyway I'll try one more time clean install

**Comment by ToddLa** [comment]
Did you directly import sf2se.zip or something else?

**Comment by rslkr** [comment]
Same problem, only shows parent roms!

> Did you directly import sf2se.zip or something else?

Imported from desktop via web server, they are working (clones) on the desktop MAME.

**Comment by ToddLa** [comment]
Point me to the romset

**Comment by rslkr** [comment]
https://archive.org/download/mame.0229
I will delete this.

**Comment by ToddLa** [comment]
Yup that is the one I am using....

Explain exactly what you do to import. 
Why do you use start server and not just `Import...`?
When you do Start Server, you just drop the file in the root? Not Copy to `roms`?

**Comment by rslkr** [comment]
> Why do you use start server and not just Import...?
Why do you use start server and not just Import...?

I just download rom from my iphone and use the import nothing changed!

> When you do Start Server, you just drop the file in the root? Not Copy to roms?

Yes I drop the file on the browser.

I think something wrong what I do for build or install!
If your ones working and not mines...

**Comment by rslkr** [comment]
I don't know what I'm doing wrong I download this build successfully and install with xcode
I checked my roms on my iphone Roms are OK
Even I transfer back  to my desktop they are still working.I mean nothing wrong with roms.

![Capture](https://user-images.githubusercontent.com/46307397/118755704-b37afe80-b8ac-11eb-9780-062271b1c3e4.PNG)

**Comment by ToddLa** [comment]
I will investigate more

**Comment by rslkr** [comment]
Sorry you are right When I do '' import'' M4i make them all clones zip files from the parent rom in the roms folder
But not showing all clones on the Native iOS UI
sf2ce.zip have 50 clones and all are in the roms folder, but only shows 18 clones!!!
The ones clone not showing on the Native iOS UI 
I thought cuz there is no title/image for that clone, so I rename another .png title file and put it back to titles folder but it didn't work.

What I did before, drop the rom into the roms folder by using the web server, browser. Thats why M4i didn't make any clones zips.
Another mistake I made, I download rom from safari copy/paste to the roms folder.I didn't  tap on the import!! sorry.
So overall I should've use Import...Web server doesn't make any clones.

**Comment by ToddLa** [comment]
> What I did before, drop the rom into the roms folder by using the web server, browser. Thats why M4i didn't make any clones zips.

You should always drop files into the root, or use the Import Share Sheet.

M4i is not gonna scan the `roms` folder every boot and look for merged-roms, Import is the place to do it. Maybe we need LARGE TEXT at the top of the WebServer page saying that.

If you modify the `ROMs` folder manually you are signing up to do things manually.

**Comment by ToddLa** [comment]
In 139 I see 18 clones, and in 230 I see all of them!

**Comment by ToddLa** [comment]
> So overall I should've use Import...Web server doesn't make any clones.

Wrong `WebServer` is exactly the same as `Import...` if you put files in the root. 

Only if you manually modify `roms` will you bypass the importer. And this is a good thing, gives user manual control over `roms`, if they want it.

**Comment by ToddLa** [comment]
PR #327 will detect merged-romsets and make sure all the Clones are Available to run.

**Comment by rslkr** [comment]
> In 139 I see 18 clones, and in 230 I see all of them!
139 must only have 18 clones in the database!

Sorry, I count them wrong, there are 21 games.
Could you tell me please, when you open the DOS UI what's the MAME version you see 139 or 230?
My one is 139.

**Comment by ToddLa** [comment]
MAME 139 should be what you see, unless you did a special build, and 139 does not support all the clones that newer MAMEs do, so what you are seeing is correct.

**Comment by rslkr** [comment]
May I ask what is the concept of mixing both version  (139 and 230)
Are we gonna have a **separated** fully working M4i 230 branch or its gonna stay like this mixed?
The first one I tried from your fork  ''https://github.com/ToddLa/mame/tree/ios-osd'' This is the real 230 right?
'Cuz, What saw that Config Menu was same like Desktop 230 and DOS UI was showing 230 on the M4i

**Comment by rslkr** [comment]
> unless you did a special build

OK Done, problem solved.  MAME 231
Sorry for inconvenient.

**Comment by ToddLa** [comment]
The idea is to be able to build a version of M4i tha is either 2xx based or 139 based.

Current mainline has a few bugs where the MAME UI might show up (by mistake) but those should be all fixed in #327

On May 23, 2021, at 1:37 AM, rslkr ***@***.***> wrote:

﻿

unless you did a special build

OK Done, problem solved. MAME 231
Sorry for inconvenient.

**Comment by ToddLa** [comment]
Also the concept of merged-roms applies to 139 and 2xx

**Comment by ToddLa** [comment]
FYI *smart* import of merged roms only works with `zip` files not `7z`.

**Comment by ToddLa** [comment]
Added merged romset support (for zip and 7z) in PR #327

**Comment by rslkr** [comment]
All good. Thank you so much ToddLa.

**Comment by osiristech** [comment]
Can someone help me get the latest version of mame in MAME4iOS??
