### ISSUE TITLE
Add "Snapshot Button" for Game's Titles

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#330]
There is no guarantee that the website/server using for ''Game's Titles'' on the Native iOS UI will lasts forever!!!
Please let the users to get the titles for it by MAME4iOS.
So we can use a button on the HUD, this button should be available and visible on the HUD when user need it. Activate in Settings to turn it on/off. Otherwise the HUD will get crowded again.
Snapshot text matches with game name and add to titles folder by Mame4ios.

**Comment by ToddLa** [comment]
https://cdn.discordapp.com/attachments/676233245972496387/820064806349438976/image0.jpg

**Comment by ToddLa** [comment]
The question is what item should fill the slot next to Snapshot (where record is in screen shot.....)

**Comment by rslkr** [comment]
> Also should snapshot be in the HUD, the MENU, or both?

It could be on both.
But main question is how often do you use Snapshot and Record?
I don't mind if they stay on HUD and MENU, but other users maybe don't like it....Too many stuff  on them...
How about make them visible when we need it?

> The question is what item should fill the slot next to Snapshot (where record is in screen shot.....)

I don't know.

**Comment by ToddLa** [comment]
What does "when we need it" mean???

**Comment by rslkr** [comment]
I mean when we need to take a Snapshot for the game's titles.At least, That's when I'm gonna use or need it.

**Comment by ToddLa** [comment]
And how does M4i when you "need it"?

I think it needs to be in the HUD all the time, in case you need it!

**Comment by ToddLa** [comment]
@rslkr My `modern-mame` branch has support for Snapshots, give it a try and see if it works like you expect.

**Comment by rslkr** [comment]
I will try 
Thank you ToddLa.

**Comment by ToddLa** [comment]
That is just a warning, not causing crash. 

Try a build and run again, 1:10 times Xcode will crash on run for me too, not the app problem but Xcode. 

I will fix that warning

**Comment by rslkr** [comment]
> Try a build and run again, 1:10 times Xcode will crash on run for me too, not the app problem but Xcode.

I did this many many times same thing happened every time.

I just downloaded the PR #327 again and build with Terminal libmame-ios.a file  now it is running good.
No more crashes.
Maybe Terminal did not build properly ''libmame-ios.a'' file before? Or something else...

> PR #327 has support for Snapshots, give it a try and see if it works like you expect.

It exactly works like I expect. 👍 
Thank you so much ToddLa

**Comment by ToddLa** [comment]
Added in PR #327

**Comment by rslkr** [comment]
Works like a charm, except one tiny bug, but this is not an important thing at all.

On the Native iOS UI, If I select ''Manufacturer'' all titles show on the ''Favorite Games'' section, there is no ''Snapshot'' section!
Similar problem for ''Year, Genre and Driver'' They all are on the ''Unknown'' section.

**Comment by ToddLa** [comment]
> On the Native iOS UI, If I select ''Manufacturer'' all titles show on the ''Favorite Games'' section, there is no ''Snapshot'' section!

Similar problem for ''Year, Genre and Driver'' They all are on the ''Unknown'' section.

????

On Jun 12, 2021, at 6:21 AM, rslkr ***@***.***> wrote:


On the Native iOS UI, If I select ''Manufacturer'' all titles show on the ''Favorite Games'' section, there is no ''Snapshot'' section!
Similar problem for ''Year, Genre and Driver'' They all are on the ''Unknown'' section.

**Comment by ToddLa** [comment]
Yea snapshots don’t have a year or driver so always Unknown, minor issue.

On Jun 12, 2021, at 6:21 AM, rslkr ***@***.***> wrote:

﻿

Works like a charm, except one tiny bug, but this is not an important thing at all.

On the Native iOS UI, If I select ''Manufacturer'' all titles show on the ''Favorite Games'' section, there is no ''Snapshot'' section!
Similar problem for ''Year, Genre and Driver'' They all are on the ''Unknown'' section.
