### ISSUE TITLE
Steam Controller Support

### ISSUE THREAD

**Issue by sevdestruct** [yoshisuga/MAME4iOS#35]
Steam Controller support via [SteamController.framework](https://github.com/zydeco/SteamController). C'mon, you know you want to, @yoshisuga.

**Comment by yoshisuga** [comment]
😂I'll take a look. I wish I had one lying around to test it!

**Comment by ToddLa** [comment]
Your framework looks solid and easy to integrate. I would fork a version and remove the swizzling tho.

**Comment by ToddLa** [comment]
Steam controllers are working good in PR #177

**Comment by mrjschulte** [comment]
Merged and closing out.
