### ISSUE TITLE
[Feature Request] When exit the game, jump to the last open location.

### ISSUE THREAD

**Issue by fatalite** [yoshisuga/MAME4iOS#351]

**Comment by ToddLa** [comment]
@fatalite please explain, what "last location" are you talking about?

**Comment by babi-jkr** [comment]
You'll excuse me from the side.
I have the same request, for example, for the purpose of verifying games of a specific manufacturer one by one, I sometimes look at each title as if zapping in alphabetical order.
In such cases, the position on the list of the title I was running right now is important, so it's painful to be forced back to the top each time.

On the contrary, if you want to return to the top, you can return by tapping the top edge of the screen with the standard operation of iOS, so it should not be a pain.

Or for those who like the same as before, it would be even better if one switch could be provided on the setting screen to switch.

I'm sorry if it's hard to read in immature English.
I'd appreciate it if you could consider the above.
Best regards.

**Comment by eduo** [comment]
> Hmmm problem with that is if someone did want quick access to `Recently Played` they would be scrolled way off the top...

Top of the list has a shortcut in iOS/iPadOS: Tap top of the screen scrolls straight to the top of the visible list.

The "recently played" is great at the top. When you open the app that's what you want to be greeted with. 

When you select from the list and afterwards exit the game the natural behaviour is to be in the same location.

When you select from the recently played, going back to the last location in reality takes you the the recently played section, so all is OK. Long press in the recently played icon could show a "show item in main list" if you want to cover all bases, as an additional convenience that closes all loops)

**Comment by fatalite** [comment]
> How does this sound, go to the four game you want, long-press (aka right click) on each and add as a favorite so they will be *pinned* at the top.
> 
> 

This is too complicated for me, would you please add the settings to allow the user to choose which way they wants.

**Comment by ToddLa** [comment]
the latest version 2022.1 tries to save/restore the previous selected item in the ChooseGame UX.  check it out.

**Comment by fatalite** [comment]
> the latest version 2022.1 tries to save/restore the previous selected item in the ChooseGame UX. check it out.

Thanks a lot! Really appreciate.
