### ISSUE TITLE
No sound system is working for any game on mame

### ISSUE THREAD

**Issue by Galorlx** [yoshisuga/MAME4iOS#355]
I get this problem if you look below sound there’s nothing any help? This happens every time for every game started @
![BF9E9085-38E5-48D1-B187-150792189805](https://user-images.githubusercontent.com/68242406/141208481-67a9b6b2-f6b6-4c11-a4bc-5c83edfed650.jpeg)

**Comment by ToddLa** [comment]
I don't see what is wrong? What version of MAME4iOS is this?

**Comment by Galorlx** [comment]
Newest version, version  2021.7 like no sound comes out for any of my games so I don’t know the problem

**Comment by Galorlx** [comment]
> I don't see what is wrong? What version of MAME4iOS is this?

2021.7

**Comment by ToddLa** [comment]
Please check your `Sound Settings` and if they are correct, so a `Reset Settings`
