### ISSUE TITLE
InfoHUD Menu Items Select

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#358]
Above items on the InfoHUD are ''1P Start and 2P Start'' and below one is ''Cancel''
We can select the items by using external controller joystick/dpad up, down, left and right.
It could be useful, if it functions like MAME config Menu. Looping
Can we make this InfoHUD Menu in a loop by using external controller?

**Comment by ToddLa** [comment]
I don't understand, what is "in a loop"?, and Cancel is not button on the HUD, at least not right below 1P Start

**Comment by rslkr** [comment]
I think this is what they called 'looping' or cycle, rotate in MAME config Menu.

https://user-images.githubusercontent.com/46307397/141871764-349879ec-5207-4f3b-8624-4b62029516d8.MP4


But, InfoHUD doesn't work like that.
https://user-images.githubusercontent.com/46307397/141871144-1e7140b7-bf28-44bc-a775-751a5ffaae15.MP4

**Comment by ToddLa** [comment]
Looping, I understand

**Comment by rslkr** [comment]
Thank you so much ToddLa, it is working good. 👍

**Comment by ToddLa** [comment]
our code to handle controller input for UX does not support repeat, if it ever gets re-worked that should happen.
...but we need to make sure analog input does not repeat super-fast

**Comment by rslkr** [comment]
Sorry for the late reply, I had an xcode building issue! Since this 'on screen keyboard' added to the project, xcode showed around 19 errors about the keyboard NOT support by xcode, **my specs were above the minimum version for M4ios...**
I should've take a screenshot! Anyway, problem solved I updated xcode.

> I am updating to new Alert code (same as I did for PV...) I will make sure it wraps too!

Yep it looks pretty good and wraps too. Thanks.

I can control almost everything (no need to touch the device) 'Settings, HUD, Game chose UI' in app by using an external controller.
What I mean about this request, long press and hold the UP/DOWN button to repeat the selection, like MAME config menu.

> our code to handle controller input for UX does not support repeat

OK I understand.

Can you at least change the selected item's color in the Settings when the external controller in use.
I'm happy with Dark Mode for Settings. But it is hard to see which one is selected... when I use external controller!

**Comment by ToddLa** [comment]
What version of Xcode did you have build problems with? 11?

**Comment by rslkr** [comment]
> What version of Xcode did you have build problems with? 11?

It was 11.7 and it says here for xcode requirement 11.4
https://github.com/yoshisuga/MAME4iOS
Currently I'm using 13.2.1

> The selected color for a UITableViewCell in Dark Mode is just the iOS default. Changing it is kind of a PITA without a custom cell.

That's ok, don't worry about it, this one for me not a MUST HAVE request. Just a minor detail.
Thanks for reply.

**Comment by ToddLa** [comment]
We should work on Xcode 11, I will try it and either fix it or change the min Xcode in the README

**Comment by rslkr** [comment]
I can't test for xcode 11 anymore, maybe its better to open an xcode issue for users... 
so we can report it there for any?
