### ISSUE TITLE
How to remove onscreen controls on Mac?

### ISSUE THREAD

**Issue by ecstaticax** [yoshisuga/MAME4iOS#361]
I'm trying the catalyst app but I cannot remove joystick and buttons... Thanks!

**Comment by ToddLa** [comment]
You can use CMD+ENTER to toggle full screen, and that will hide the controls by default.

Also the full screen option is in the menu.

When we get input from a controller, or arrow keys, the on-screen controls will fade away, when full screen.

**Comment by ecstaticax** [comment]
Thanks, it works! :-)

**Comment by ToddLa** [comment]
we should have a dedicated button to hide show the controlls avail at all times.
we kind of do this already when we detect the MAME machine wants mouse input.
...but we should do it all the time...
