### ISSUE TITLE
can i add more buttons?

### ISSUE THREAD

**Issue by OhYeahMan786** [yoshisuga/MAME4iOS#369]
I would like to add more buttons because the six it comes with are very few.

**Comment by ToddLa** [comment]
There are 10 buttons, 🅐🅑🅧🅨 L1,L2,L3,R1,R2,R3
(Touch screen is missing L3,R3 so only 8)
Isn't that plenty??

**Comment by stonecold001** [comment]
Hi, I want to play Majhong games, but it needs about  30+ buttons for playing, so how can fix this problem?

**Comment by eduo** [comment]
Mahjong in MAME is meant to be played with a keyboard. Joystick usage is done through popup menus: 

https://mahjonginmame.com/control.htm
https://docs.mamedev.org/usingmame/defaultkeys.html

You could conceivably build your own controller tapping into the keyboard mapping, or just use a keyboard. 

You could also buy a USB keyboard built for mahjong: https://www.amazon.de/-/en/R-STYLE-Controller-Mahjong-Emulators-Hyperspin/dp/B07MXMJSPN

But in general yes, you're asking about keyboard supports, not controller and buttons.

**Comment by ToddLa** [comment]
Also in the next release MAME4iOS will have a on-screen keyboard, that should give you all the keys you want...

**Comment by stonecold001** [comment]
Okay, thank you very much! New version is playing now, perfect!
