### ISSUE TITLE
artworks don't work in iPhone but work in iPad

### ISSUE THREAD

**Issue by monogalactico** [yoshisuga/MAME4iOS#370]
Artworks of game & watch games work perfectly in iPad buy in iPhone doesn't work (all screen is black). I've tested different artworks in different machines but it never works. Where are the differences between iPhone and iPad if I am building the same version? Thanks!!!

**Comment by ToddLa** [comment]
Fixed in PR #372

**Comment by yoshisuga** [comment]
Thanks for fixing this @ToddLa !
