### ISSUE TITLE
TVAlertViewController is sooooooooooo UGLY!

### ISSUE THREAD

**Issue by imatrixme** [yoshisuga/MAME4iOS#376]
The latest version of MAME4iOS imported new alert component named TVAlertViewController, but its' style is so ugly, please change its style or remove it.

**Comment by ToddLa** [comment]
We need a UX dialog that can be driven via a game controller and not take up whole screen on tvOS. 

It is not ugly, the only thing that may be jarring is the blue (aka focus color) border when it has focus. I was not a fan of that either....

**Comment by yoshisuga** [comment]
Please suggest concrete improvements and/or constructive feedback. Closing.
