### ISSUE TITLE
1P Start and 2P Start on the HUD, act weird for controllers!

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#392]
While I play any game and if I tap on the 1P Start or 2P Start on the HUD more than once, 
(it effects on the both controllers touch screen and external) makes the joystick and buttons disabled for a while.
Even more, If I hold the joystick at any direction while I'm tapping, joystick stuck that way for a while!!!

This happens on infoHUD as well but it's hard to detect 'coz it only allows one time tap.

**Comment by ToddLa** [comment]
Yes while we are sending "fake" buttons to MAME we ignore input from game controllers. 

The timing on COIN and START is weird, and we add in some pause time.

**Comment by rslkr** [comment]
Hmm 'pause time' So, I'll take this is necessary then?
Should close this issue?

**Comment by ToddLa** [comment]
Yea you can't just push coin and start quick, the button needs to be held down for a certain amount of time, and a pause needs to be between them. 

With a controller you can always just hit select and start your self, and not use the "auto start buttons"

**Comment by rslkr** [comment]
Ok got it, thank you.
