### ISSUE TITLE
HUD doesn't show 1P,2P,3P,4P Start for some 3 to 4 Player Arcade Games.

### ISSUE THREAD

**Issue by rslkr** [yoshisuga/MAME4iOS#393]
Hi ToddLa,
It's been a while since I play multi player games and I realized that some of them not showing player starts at all!
These are not showing: 
Sunset Riders (ssriders.zip), Vendetta (vendetta.zip)

So far, these are showing:
Captain Commando (captcomm.zip), Dungeons & Dragons (ddsom.zip), X-Men (xmen.zip), Cadillacs and Dinosaurs (dino.zip)

I'll check more...

if anyone interested in 3 to 4 Player games, I found a good video: https://youtu.be/4UdPru-jxX0

In the video description, explain how to enable for multi player if it is not default by game.

**Comment by ToddLa** [comment]
Will need to check out those games, we "sniff" the input profile to determine how many players a game has. If the game does not look for input on player 3 or 4 we assume it is only a single. Or two player. Of course there are turn based machines, but we only show him players based on input profile.

**Comment by ToddLa** [comment]
Yea captain commando should be detected as 4 player, will take. Look

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=captcomm&arcade_only=0&autosearch=1

**Comment by ToddLa** [comment]
![image](https://user-images.githubusercontent.com/4494698/163603427-e5742575-f5ea-4abb-9f40-7efb866c60a0.png)

I see 4P on the 139 version

**Comment by rslkr** [comment]
Yes that is correct, HUD shows the players Start for Captain Commando, but enabling the 4 characters in the game requires a DIPSWITCH setting, which is in the MAME config menu.
For instance, this game also shows 4 players Start on the HUD, Dungeons & Dragons (ddsom.zip)
to enable the players in the game is in the Service (the game's settings)

You may recall, while you were adding 1P and 2P Start to M4i, I asked for 3P and 4P  for these games:
Cadillacs and Dinosaurs (dino.zip), Sunset Riders (ssriders.zip)

dino is still OK it shows 3 players Start, but Sunset Riders (parent rom) doesn't show at all. It was showing before when you added first!
There are 2 and 4 players clones for Sunset Riders. 2 players are OK
This is interesting: these two clones 'ssridersadd and ssridersuda' show 4 players on the HUD 
The rest of them same as parent rom!

I'm using 241, MAME4iOS 2022.1

**Comment by ToddLa** [comment]
Getting into the dipswitches is two complex. 

All we do is count the number of start buttons the machine is looking for in its input profile, and use that as a best guess to how many players supported.

**Comment by rslkr** [comment]
I did check ALL of them one by one in that video
Most of them are OK.
Here's the list of games has no Players Start on the HUD, and some of them shows incorrect!

4 Players:

- Captain America and The Avengers captaven.zip :  1P and 2P Start, Enable: Dipswich
- Crime Fighter (clone) crimfghtu.zip :  None
- Desert Assault (parent: thndzone.zip) clone: dassault.zip :  None, Enable: Dipswich
- Gauntlet gauntlet.zip : None, Enable: Service
- Sunset Riders ssriders.zip : None
- Tank Force (clone) tankfrce4.zip : None 
- Teenage Mutant Ninja Turtles tmnt.zip : None
- Teenage Mutant Ninja Turtles - Turtles in Time tmnt2.zip : None
- Vendetta  vendetta.zip : None

3 Players:

- Hot Rod hotrod.zip : 1P and 2P Start
- Gain Ground gground.zip : 1P and 2P Start
- Nitro Ball nitrobal.zip : 1P and 2P Start
- Pit Fighter pitfight.zip : None
- Rampage rampage.zip : None
- Rampage: World Tour rmpgwt.zip : 1P 2P 3P 4P Start
- Violent Storm viostorm.zip : 1P 2P 3P 4P Start

> All we do is count the number of start buttons the machine is looking for in its input profile, and use that as a best guess to how many players supported.

OK now I understand, according to the 'input profiles' in M4i, **your codes work just fine**.

For example:
Captain America and The Avengers captaven.zip shows 2P  its in input profile have 2 Players Start, but the game 4 players.

Rampage: World Tour rmpgwt.zip shows 4P 'coz its in input profile have 4 Players Start, but the game 3 players.

And some of them has NO Player Start its in input profile...

We can ignore this issue no problem, all these games are playable.
Thank you for the heads-up.
