### ISSUE TITLE
A button doesn't select ROMs in tvOS

### ISSUE THREAD

**Issue by jpbedoya** [yoshisuga/MAME4iOS#40]
Cannot click on ROMS or the other Menu items like Configure General Inputs or Reload ROMs. Trying  pressing A button. The A button works in other parts of the app (like selecting cancel after pressing Y)

Using a Nimbus controller and Apple TV 4th gen

**Comment by jpbedoya** [comment]
Now I'm getting this error when I compile  Commit:
b921624b74e95e345dc5533e46b5a9af74aaeb86 [b921624]

/MAME4iOS/iOS/EmulatorController.m:397:5: 'UIPopoverPresentationController' is unavailable: not available on tvOS

**Comment by yoshisuga** [comment]
That compile error was fixed by PR #45

**Comment by jpbedoya** [comment]
rebuilding and PR 45 fixed the issues
