### ISSUE TITLE
can't exit the game.

### ISSUE THREAD

**Issue by babi-jkr** [yoshisuga/MAME4iOS#404]
I can't exit the game and return to the menu. Whether I select "Yes" from the EXIT button or "Exit Game" from the MENU button, I will be returned to the game just by closing the menu. (It's been the case since the previous version, but I forgot to report it.)

DEVICE : iPad Pro 3G(12.9")
OS : iOS 15.4.1
App : MAME4iOS-2022.2-latest

BR.

**Comment by babi-jkr** [comment]
oh...I didn't think of resetting the settings.
I tried it right away and the problem went away.
I'm sorry to bother you.

**Comment by ToddLa** [comment]
This has been a known issue, and I would like to find some way for MAME4IOS to detect if the ESC key is re-mapped. There are some other keys that can also cause problems if re-mapped

**Comment by ToddLa** [comment]
Yes MAME4iOS treats CMD-. As ESC

But if EXIT has been re-mapped away from ESC in MAME, we will have a problem.
