### ISSUE TITLE
Currently the lowest version of my project is ios11

### ISSUE THREAD

**Issue by LiuSky** [yoshisuga/MAME4iOS#429]
libmame-139u1-ios, Can you change it to support ios11 @ToddLa

**Comment by ToddLa** [comment]
I am confused, do you want a version of MAME4iOS for iOS11?
Or libmame? 

Are you using libmame in another project?

**Comment by LiuSky** [comment]
Yes, I want libmame，thank you @ToddLa

**Comment by LiuSky** [comment]
ank you very much, and I found that you are now migrating the mame4ios project to Swift @ToddLa

**Comment by ToddLa** [comment]
What project are you using libmame?

And are you using 139, 2xx, or both like MAME4iOS does?

**Comment by ToddLa** [comment]
Try this (from terminal)

```
./make-ios.sh clean
./make-ios.sh OSVERSION=11.0

```

**Comment by ToddLa** [comment]
FYI I have a test project for `libmame` that is mostly in Swift [here](https://github.com/ToddLa/iOSMAME)

**Comment by LiuSky** [comment]
> What project are you using libmame?
> 
> And are you using 139, 2xx, or both like MAME4iOS does?

I only use 139

**Comment by LiuSky** [comment]
> Try this (from terminal)
> 
> ```
> ./make-ios.sh clean
> ./make-ios.sh OSVERSION=11.4
> ```



> Try this (from terminal)
> 
> ```
> ./make-ios.sh clean
> ./make-ios.sh OSVERSION=11.4
> ```

I tried and found it was no good

**Comment by LiuSky** [comment]
> FYI I have a test project for `libmame` that is mostly in Swift [here](https://github.com/ToddLa/iOSMAME)

thank you

**Comment by LiuSky** [comment]
> Try this (from terminal)
> 
> ```
> ./make-ios.sh clean
> ./make-ios.sh OSVERSION=11.4
> ```

OK

**Comment by LiuSky** [comment]
> > FYI I have a test project for `libmame` that is mostly in Swift [here](https://github.com/ToddLa/iOSMAME)
> 
> thank you
![截屏2022-12-07 09 51 42](https://user-images.githubusercontent.com/3087745/206068060-03b71be1-268d-41b2-a67e-c7ab2de37abb.png)
failed

**Comment by LiuSky** [comment]
> Try this (from terminal)
> 
> ```
> ./make-ios.sh clean
> ./make-ios.sh OSVERSION=11.4
> ```

![截屏2022-12-07 13 53 08](https://user-images.githubusercontent.com/3087745/206099592-e410778c-4de7-40a7-bc64-1e1e588013fc.png)
11.4 Generation Failure

**Comment by ToddLa** [comment]
I will give it a try, and look at the specific error.

**Comment by LiuSky** [comment]
Yes, I just run it your way, but I can't. Can you send me an 11.0 libmame

**Comment by LiuSky** [comment]
Version 13.4 is OK, anything less than 13.4 is a build failure

**Comment by ToddLa** [comment]
Hmmm what version of Xcode are you using? I was able to build LIBMAME for 11.4 no problem using latest Xcode

**Comment by LiuSky** [comment]
I also use the latest xcode, but there is no specific error. 13.4 can be generated successfully, but the following 13.4 cannot. There is only one specific error 【macosx_arm64_clang】Error 2

**Comment by ToddLa** [comment]
Don't know what to say, try this to maybe see the error

```
make clean
make CDBG=-w OSVERSION=11.4
```

**Comment by LiuSky** [comment]
> Don't know what to say, try this to maybe see the error
> 
> ```
> make clean
> make CDBG=-w OSVERSION=11.4
> ```

Can't find this file?

**Comment by LiuSky** [comment]
> Don't know what to say, try this to maybe see the error
> 
> ```
> make clean
> make CDBG=-w OSVERSION=11.4
> ```

Thank you. Problem solved @ToddLa
