### ISSUE TITLE
netplay

### ISSUE THREAD

**Issue by LiuSky** [yoshisuga/MAME4iOS#432]
0.250 Is there any consideration for writing network battles @ToddLa

**Comment by eduo** [comment]
Netplay was added in 2013 and removed in 2021. Not sure if to be refactored or definitively.

**Comment by LiuSky** [comment]
2013 netplay。Frames are out of sync @eduo

**Comment by ToddLa** [comment]
Yea netplay was removed when we switched to the modern MAME core. It is not supported anymore.

**Comment by LiuSky** [comment]
So there won't be any more support for netplay? @ToddLa

**Comment by ToddLa** [comment]
Nope

**Comment by LiuSky** [comment]
I recently found a such netplay (https://github.com/AlexanderDzhoganov/mame-netplay), you can combine it to https://github.com/ToddLa/mame? thank you @ToddLa

**Comment by ToddLa** [comment]
Considering the last change to that project was 4yrs ago, no.

**Comment by LiuSky** [comment]
I'd like to pay you to help me build a netplay. The amount could be $1,000 or $2,000. I wonder if you could help me @ToddLa

**Comment by LiuSky** [comment]
I tried to send you an email, but you didn't reply. @ToddLa

**Comment by ToddLa** [comment]
NetPlay was removed in MAME4iOS 2021.6

So download 2021.5 (or 2021.4 etc) if you want NetPlay

FYI these versions are only MAME 139
