### ISSUE TITLE
0.252 update

### ISSUE THREAD

**Issue by LiuSky** [yoshisuga/MAME4iOS#433]
Can you update support for 0.252MAME。 @ToddLa

**Comment by ToddLa** [comment]
Yes, I am working on it, a bigger merge than usual

**Comment by LiuSky** [comment]
Cool, that's great @ToddLa 

> Yes, I am working on it, a bigger merge than usual

**Comment by LiuSky** [comment]
<img width="695" alt="截屏2023-03-20 19 54 21" src="https://user-images.githubusercontent.com/3087745/226332281-b67d511a-11f7-4916-b31a-a81af5dd1e62.png">
This code doesn't work in 0.252.  Do you know what the problem is? @ToddLa

**Comment by LiuSky** [comment]
I press A or B in the UI and nothing happens @ToddLa

**Comment by ToddLa** [comment]
I am still looking at the 252 merge, but I doubt that code is your problem

**Comment by LiuSky** [comment]
👌

**Comment by LiuSky** [comment]
How is the progress of 0.252? @ToddLa

**Comment by ToddLa** [comment]
MAME removed the flags for `machine type` (Arcade, Console, Conputer, ....) in 252, so some non-trivial changes needed. 

MAME4iOS treats Arcade and Console different in the UX.

I have a working solution, just gotta test it and push.

**Comment by LiuSky** [comment]
good Hope to merge soon.
