### ISSUE TITLE
中文作弊

### ISSUE THREAD

**Issue by 51517960** [yoshisuga/MAME4iOS#435]
中文设置只能作者更新了,现在可以做到中文cheats和中文故事,下载后解压缩到mame根目录重启mame,选游戏,然后点cheat便是中文了.故事文件需要自己百度搜索添加覆盖即可,

链接: https://pan.baidu.com/s/1kkN5N0biVoKQNOKt1y67CA?pwd=av5a 提取码: av5a 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v8的分享

**Comment by lileeleolee** [comment]
分享已过期
