### ISSUE TITLE
CGBitmapContextCreate error

### ISSUE THREAD

**Issue by LiuSky** [yoshisuga/MAME4iOS#436]
<img width="979" alt="截屏2023-04-13 00 44 19" src="https://user-images.githubusercontent.com/3087745/231526283-1cf62aea-ff5a-4d90-ad61-0eb461e18923.png">
<img width="1104" alt="截屏2023-04-13 00 44 06" src="https://user-images.githubusercontent.com/3087745/231526330-be032154-c793-4262-830b-8e0d70aae26e.png">
![WechatIMG332](https://user-images.githubusercontent.com/3087745/231527289-e3de0c38-2745-4c24-a489-a0243ad876b1.jpeg)
![WechatIMG331](https://user-images.githubusercontent.com/3087745/231527324-cbebe779-5b17-4d95-b10a-44f77624dca2.jpeg)
![WechatIMG333](https://user-images.githubusercontent.com/3087745/231527352-5f04ad37-c611-46c6-85ff-26c62de8ff6b.jpeg)

I want to render with img_buffer, but the result is not correct. I would like to ask you which of my above screenshot code is wrong. Thanks for your advice @ToddLa

**Comment by ToddLa** [comment]
That is old code, current M4i does not render like that, it uses Metal...

**Comment by ToddLa** [comment]
You can get a image via MAME snapshot key....

**Comment by LiuSky** [comment]
It's finally the big boy. I know that currently m4i uses metal render. But I want to try using img_buffer. But it never turned out right. I'd like you to take a look at it. Thank you @ToddLa

**Comment by LiuSky** [comment]
I don't want a screenshot, I want a bitmap of the entire render. @ToddLa

**Comment by ToddLa** [comment]
Why? Rendering via CoreImage is old skool. 

You can grab a snapshot after the `Metal` render?

Do you just need a frame snap, Or are you making a whole new method to draw, ie a new MAME iOS app?

Or maybe you can do what you want with a `Metal` Shader?

**Comment by ToddLa** [comment]
You should roll back (via git) MAME4iOS to a version that supported CoreImage and you will see how it used the software renderer

**Comment by LiuSky** [comment]
> You should roll back (via git) MAME4iOS to a version that supported CoreImage and you will see how it used the software renderer
I just want you to look at how to render a bitmap using renderer_sdl1

**Comment by LiuSky** [comment]
> Why? Rendering via CoreImage is old skool.
> 
> You can grab a snapshot after the `Metal` render?
> 
> Do you just need a frame snap, Or are you making a whole new method to draw, ie a new MAME iOS app?
> 
> Or maybe you can do what you want with a `Metal` Shader?

I just want you to look at how to render a bitmap using renderer_sdl1

**Comment by ToddLa** [comment]
And this is a MAME4iOS issue how?
