### ISSUE TITLE
0.250 packs is too big. How to only compile games for the company we specify.

### ISSUE THREAD

**Issue by LiuSky** [yoshisuga/MAME4iOS#437]
How Version 0.250 only compiles 'neogeo' games.   Nothing else is compiled into libmame.   Because everything is compiled into a big package @ToddLa thank you

**Comment by ToddLa** [comment]
I don't understand, is this an issue with `MAME4iOS` or my MAME fork to build `libmame`

**Comment by LiuSky** [comment]
No, I solved the problem.

**Comment by LiuSky** [comment]
Now I have a question about netplay, I want to consult you. I don't know when you usually go online, but I am available from 8 am to 12 PM Beijing time. @ToddLa

**Comment by LiuSky** [comment]
> Netplay has not been supported for many years.

Yes, I'd like to review how we can support it quickly. I don't know if the workload is big, so I want to consult @ToddLa

**Comment by ToddLa** [comment]
This is a MAME4iOS GitHub issue about 0.250 being too big. Issue #432 is about NetPlay.
