### ISSUE TITLE
build 0.250

### ISSUE THREAD

**Issue by LiuSky** [yoshisuga/MAME4iOS#438]
https://github.com/ToddLa/mame build error
![截屏2023-05-05 16 10 55](https://user-images.githubusercontent.com/3087745/236408291-6a67490e-7dfe-4cea-8873-075377b543c0.png)
@ToddLa

**Comment by ToddLa** [comment]
Yup I already fixed this, will do a push soon

**Comment by LiuSky** [comment]
cool @ToddLa

**Comment by LiuSky** [comment]
Is every time you revise, just push, can you get a https://github.com/ToddLa/mame develop branch, I can be observed in some of your changes at any time @ToddLa

**Comment by ToddLa** [comment]
I like to only push finished code. Expect a push tomorrow

**Comment by LiuSky** [comment]
I'm really looking forward to it. I find you with https://github.com/libretro/mame writer often update at the same time, are you the same person?

**Comment by LiuSky** [comment]
Ha ha, I have been waiting for two days @ToddLa

**Comment by ToddLa** [comment]
I don't work on the libretro MAME core. 

My MAME fork does build now, but I need to do a few things before I release a lib.

**Comment by LiuSky** [comment]
That's great. I'll start working on it today @ToddLa

**Comment by LiuSky** [comment]
Well, as I said last time, pressing the ABXY button doesn't have any effect, and neither does the joystick. input binding error again。Try it out with the MAME4iOS project and you'll see. @ToddLa
