### ISSUE TITLE
ICADE controls not working properly

### ISSUE THREAD

**Issue by vurt72** [yoshisuga/MAME4iOS#439]
I have an icade and it's impossible to get MAME4iOS-2022.5-250 working with it, Down does not work like it should, also Up and Left is weird. Buttons does seem to work. I have it set to Icade in the settings.

**Comment by ToddLa** [comment]
I will have to try my iCade again, maybe something got broke...

**Comment by vurt72** [comment]
I entered the menu and to Input and there i just re-selected every input of the stick and now it works! Maybe that's just how it's supposed to work.
