### ISSUE TITLE
How to build 250 from source?

### ISSUE THREAD

**Issue by ultratiem** [yoshisuga/MAME4iOS#458]
Hello,

I grabbed the source and built 139 just fine but I see no way to set it to 250. How do I build 250 from source, not 139?

**Comment by LiuSky** [comment]
![截屏2024-04-30 08 52 12](https://github.com/yoshisuga/MAME4iOS/assets/3087745/3022e6d4-3ccc-4b27-bb18-9ce43952d609)

**Comment by ultratiem** [comment]
Thanks for the reply. In that config file I see the following:

> // 3. Select the MAME binary to link to.
> //    139u1 or latest MAME version
> 
> // USE THIS LINE for a local build of 139u1 MAME. (via make-ios.sh, make-tvos.sh, or make-mac.sh)
> MAMELIB = libmame-139u1
> // USE THIS LINE for a build of current latest MAME (via get-libmame.sh)
> // MAMELIB = libmame

I've tried libmame-250 and just libmame but neither build 250, just the standard 139.

**Comment by Alexck002** [comment]
delete (-139u1) and type -250 in the next line
