### ISSUE TITLE
Controllers misaligned

### ISSUE THREAD

**Issue by jpbedoya** [yoshisuga/MAME4iOS#61]
Controllers are placed over the game screen (middle of phone) instead on the bottom of the screen. 

iPhone X screenshot
https://share.icloud.com/photos/0ri1_-SmCGhk4uUEHd7DHGixg

**Comment by yoshisuga** [comment]
Yes I need to get around to fixing that - you can change the layout of the controls manually in the mean time in Settings -> Input -> Change Layout

**Comment by jpbedoya** [comment]
didn't realize that. that's helpful for now.
thx

**Comment by ToddLa** [comment]
Layouts should work on all devices now, close?

**Comment by mrjschulte** [comment]
Fixed, and closing.
