### ISSUE TITLE
No sound on iPad Pro

### ISSUE THREAD

**Issue by sakim** [yoshisuga/MAME4iOS#62]
No sound on iPad Pro 10.5 running on iOS 12.1.x. Sounds normally on iPhone X with same version of iOS. Please let me know if you need any further information or testing on some code changes.

commit: 5136b8821ba009274a9ceb0ea6e44c1940945906 (current master)

**Comment by yoshisuga** [comment]
I just tried testing on an iPad Pro 11 and had no issues with sound. What games did you try? I'm not sure what would be causing that.

**Comment by sakim** [comment]
@yoshisuga My iPad is muted. I didn't find this because there's no physical mute button on iPad Pro 10.5 and video apps are still play audio. I wrote this to let you know in case of same inquiries. Sorry to bother you. Thank you 🙏

**Comment by yoshisuga** [comment]
No problem at all, glad that was the issue! 🙂
