### ISSUE TITLE
Change the active touchscreen buttons in the main menu

### ISSUE THREAD

**Issue by illando** [yoshisuga/MAME4iOS#64]
The group of the active touchscreen buttons in the main menu should be changed.
A better solution should be to make a set of 3 buttons active:
- A: Launch rom
- B: Back in the menu (instead of "exit" like it is now)
- Y: Add to favorites ( instead of the actual X)
This will follow the rule used by other emulators... check for example Retropie, and in this way the buttons will fill the corner of the screen leaving space to visualise the menu.

![image](https://user-images.githubusercontent.com/11694410/52382419-7db40200-2a75-11e9-88ba-2ece3b378dfc.png)

**Comment by mrjschulte** [comment]
Needs review @mrjschulte

**Comment by ToddLa** [comment]
This only applies to the MAME menu, and that is (hopefully) in the dustbin now.
