### ISSUE TITLE
Sensitivity slider in analogue settings is no longer needed

### ISSUE THREAD

**Issue by illando** [yoshisuga/MAME4iOS#65]
After some tests, I can say that the sensitivity slider that it's actually listed under the touch analogue preference it's just creating some gap between the finger position and the analogue input of the game, or is not well accepted from the MAME core.
The only way to obtain a nice analogue calibration is:

- Set this slider to 0 (the minimum value of the slider on the left)
- Enter the rom setting MAME menu (pressing COIN + START)
- Go to "analogue controls" menu and start to increase "Dial Sensitivity" till you reach a good setting (it depends from the games, the screen size of the device, and the orientation of the display.

At this point, I think this slider should be set to 0 as default value.

![image](https://user-images.githubusercontent.com/11694410/52383215-bb665a00-2a78-11e9-8231-414f1afe736d.png)
![image](https://user-images.githubusercontent.com/11694410/52383249-d933bf00-2a78-11e9-8c38-c2c2eb41b9ce.png)

**Comment by mrjschulte** [comment]
Needs review @mrjschulte
