### ISSUE TITLE
Visualise the hold status when "Button A as Autofire" is active

### ISSUE THREAD

**Issue by illando** [yoshisuga/MAME4iOS#67]
Button A as Autofire is very useful in some games.
When it's active, the A button became a switch to toggle on/off the Autofire function.

It could be useful if when the Autofire is on the Button A could keep his hold status image, switching back to the default one when you press it again to toggle off the function.

**Comment by ToddLa** [comment]
Button A as AutoFire is implemented way down in the MAME/OSD layer. Turbo Mode is implemented in the app layer.
