### ISSUE TITLE
IPA prebuilds?

### ISSUE THREAD

**Issue by clareewew** [yoshisuga/MAME4iOS#7]
Title says it all. Offering an IPA installer permits people that doesnt have a Mac computer with lastest XCode or a paid Apple Developer Account to sideload the new version of MAME4iOS to the system. It will become easier to install it (even for the people on a Mac) and a possibility to spread this software. 

A very well-known iOS emulator, like Provenance (https://github.com/jasarien/Provenance) since the lastest release already offers this. Avoids a lot of build problems reports too. 

This would require releases, dah, ;=) that ATM are not being published. Would be great that also!

PS: Sorry for my crappy English.

**Comment by clareewew** [comment]
This can be done with Cydia Impactor, for example.

**Comment by just-Addict** [comment]
I would very much like that too, Sadly the link to a prebuild one in the ReadMe is only for 64 bit models and I would love to be able to play it on my old 32bit models too.

**Comment by sevdestruct** [comment]
We [provenance] don’t actually offer this. We set up a limited member web signing server for beta testing and dev team usage. Registration is now closed.

**Comment by daedalia** [comment]
There are a couple of signing services out there that offer signing and installation for around $20 a year. Just Google it. An IPA installer is beyond the scope of this project really and Github.

**Comment by mrjschulte** [comment]
IPA pre-builds for the new 2020.x releases are now on the main GH landing page for the project. Sadly we can't continue to support the 32bit platforms with all of the recent changes that have gone in and the ones coming up....
