### ISSUE TITLE
MFI controller mapping?

### ISSUE THREAD

**Issue by Marcuni** [yoshisuga/MAME4iOS#70]
I've only used the iCade as a controller but now I have a Hori MFi gamepad that is not on the external controller profile list. How do I re-map for it? The general menu for external controllers does not provide custom mapping, only profiles. And to get to the in-game mapping you need to press a combinations of buttons that are not mapped in my controller. I was able to finally map it by turning off the controller in the middle of a game to access the in-game menu, turning the controller back on, then re-map it.

I think there must be an easer way. What am I missing? Is there a file somewhere I could edit?

Thanks

**Comment by yoshisuga** [comment]
Hi! Mfi controllers are automatically detected and there’s no need to do any setup. The external controller profile is only for icade controllers and doesn’t affect mfi controller operation. 

Make sure the controller is paired and maybe try checking to see if the controller responds to input in other games. I don’t have a hori controller myself but it should work.
