### ISSUE TITLE
Suggestion: Add an url scheme

### ISSUE THREAD

**Issue by ptrvg** [yoshisuga/MAME4iOS#71]
Hi,

I would like to able to launch directly into a specific game from another app I just started working on.
[3darcade](
https://youtu.be/fPyNp7LbekU)

I think this could work if MAME4iOS implements an url scheme which accepts a romname and then starts that game.

I do have a bit of experience with iOS development. So I was able to add an url scheme. But I have no clue how to hook it up from there. I only have some experience in swift...so I am a bit lost ;)

Peter

**Comment by ToddLa** [comment]
The latest version (2020.1) does this...

```
mame4ios://game
mame4ios://pacman
```

**Comment by ptrvg** [comment]
Thanks, that is really useful!
