### ISSUE TITLE
iOS 10 support ?

### ISSUE THREAD

**Issue by Wh0ba** [yoshisuga/MAME4iOS#72]
It would be really great to have this emulator on iOS 10 since the only version that runs is very old 
And thanks

**Comment by yoshisuga** [comment]
I changed the deployment target to iOS 9 so should be able to build and run for iOS 10 now.

**Comment by Wh0ba** [comment]
Sorry for if i'm bothering you 
But when will you update the release ipa with the new deployment target 
And thanks 
I don't have a mac to build
