### ISSUE TITLE
Hi-Score Not Supported?

### ISSUE THREAD

**Issue by Marcuni** [yoshisuga/MAME4iOS#73]
Hi. I've noticed hi-score saving is not working. Is that not yet supported?

Thanks.

**Comment by monogalactico** [comment]
I've noticed the same, in fact it seems there was a "save highscore" in the global options but now it is not and "hi" is not working. Have you get anything?

**Comment by monogalactico** [comment]
Resolved! "Save Highscore" is In game options->default !!!

**Comment by mrjschulte** [comment]
Closing.
