### ISSUE TITLE
Why no Siri-remote-as-game-controller support

### ISSUE THREAD

**Issue by jtayler** [yoshisuga/MAME4iOS#74]
Why no Siri-remote support? Seems we have the ability to be a delegate from the view controller and the iCadeView would accept text character controls if nothing else?

**Comment by yoshisuga** [comment]
Because the Siri remote gets detected as an mfi controller, and I'd need to write more code to support it, which I'd like to do at some point in the future.

iCadeView has to do with iCade (keyboard) input only. The siri remote is basically another mfi controller.

**Comment by jtayler** [comment]
I see, iCade is a miniature arcade console and I'd guess that's a common use of the code here. If I can understand how the joystick is handled, or get a sense of the architecture being used here then I could support the regular Siri remote and we could support the watch / Digital Crown as well I'd bet. I'd like to see this fully AppleTV compatible but I suppose true remotes work much better than the SIRI remote for most games anyway.

**Comment by mrjschulte** [comment]
Can you check if this is now working in the latest merge?

**Comment by ToddLa** [comment]
It was not in the merge 3 days ago, but it is in the merge today (2020.1) 
Yes the Siri remote should work, I just played Donkey Kong on my TV.

**Comment by ToddLa** [comment]
This should totally work, please check and close!

**Comment by mrjschulte** [comment]
This works. very basic controls, but it works. 

Closing.
