### ISSUE TITLE
Is Bluetooth keyboard support possible?

### ISSUE THREAD

**Issue by gaussey** [yoshisuga/MAME4iOS#75]
Since the current jailbreak is stable I’ve finally decided to build an arcade controller with two joysticks (for Robotron), nothing is buyable off the shelf and neither is an MFI wireless encoder so I’m planning on gutting an old working Bluetooth ipad keyboard but Mame4iOS isn’t reading my keystrokes in the config menus. 

If this isn’t possible I’m going to have to gut a working MFi wireless controller since I cant depend on NControl (PS4/Xbox One hack) working long term if i need to lose jailbreak. Not a whine just a bit of info on where I’m going.

Any help or suggestions would be gratefully received

**Comment by yoshisuga** [comment]
Hi, go to Options -> Game Input -> External Controller. Enable iCade - this is basically a bluetooth keyboard. There's a key for key up/key down for the controller presses. Look this up as its somewhere on the internet. If you can map your inputs to the iCade key presses you should be able to get your custom controller working

**Comment by yoshisuga** [comment]
The mappings are here:
https://github.com/yoshisuga/MAME4iOS/blob/master/iOS/iCadeView.m

**Comment by gaussey** [comment]
The problem with using iCade is that it requires key up and down codes to be sent separately and that isn’t really possible without some kind of intermediate software or firmware and I don’t really have the technical ability to do that.
