### ISSUE TITLE
Help needed with mame4ios for ios 12.0.1 on the iphone xs max

### ISSUE THREAD

**Issue by longbauw** [yoshisuga/MAME4iOS#78]
Hi guys can some one send me the ipa or deb
files that already compiled to work with iphone xs max on ios 12.0.1 please

I am jailbroken with chimera on ios 12.0.1

I dont have a mac or the knowhow the compile it my self.

I had the mame4ios emulator running since the beginning on ios 6

This is the first time ever that i cant install the emulator on a ios device and it sucks.

So i hope could help me out.

**Comment by mrjschulte** [comment]
IPA's for the latest are now listed on the main GH landing page.
