### ISSUE TITLE
Error building with Xcode 11.2 for tvOS 13.2

### ISSUE THREAD

**Issue by dramagods** [yoshisuga/MAME4iOS#82]
Hello @yoshisuga,

I've got the following error when building MAME4iOS for TVOS using Xcode 11.2 and tvOS 13.2:
ld: warning: ignoring file /Users/xxxxx/repositories/MAME4iOS/libmamearm64-tvos.a, building for tvOS Simulator-x86_64 but attempting to link with file built for tvOS-arm64
Undefined symbols for architecture x86_64:
  "_myosd_array_categories", referenced from:
....
      -[EmulatorController updateOptions] in EmulatorController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:

I tried to figure it out how to get those undefined symbols for x86_64 but I had no luck so far.
I used the mame library for tvos in the instructions and I also build it with the script provided in the repo and I had the same result.
I would be great if you could help it out. 
Many thanks.

**Comment by yoshisuga** [comment]
Ah yeah you're building for the tvOS simulator, not an actual tvOS device. Choose "Generic tvOS device" if you're building an IPA, or choose your actual Apple TV.

If you don't see your Apple TV, you need to pair it in Xcode.

**Comment by dramagods** [comment]
Amazing, well spotted @yoshisuga!
I missed that bit about connecting the Apple TV to xcode. 
It works great now. 
Many thanks.
