### ISSUE TITLE
Building 32-bit, linker failed, libmamearmarmv7.a

### ISSUE THREAD

**Issue by gajahduduk** [yoshisuga/MAME4iOS#84]
Hi. I'm trying to build for an iPhone 5 running iOS 10.3.4.  I still have one of those mini arcade controllers for it. The goal is to use that via bluetooth.

I can't get the 32-bit build to work.  I managed to find libmamearmv7.a in an old MAME4iOSReloaded archive and put it at the root.  However, XCode still failing with:

```
      DSP56K::Mac_3::decode(unsigned short, unsigned short) in libmamearmv7.a(inst.o)
      ...
  "_lightgun_x", referenced from:
      -[EmulatorController handleLightgunTouchesBegan:] in EmulatorController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Do I have the wrong libmamearmv7.a file?  If so where do I get the right one?  If it is the right one, then any ideas?  (I'm no XCode Pro here, but I can wing it a little).

Thanks!

**Comment by yoshisuga** [comment]
Yeah the MAME frontend depends on the lightgun data that was introduced in the MAME binary awhile ago.

The MAME library needs to be recompiled for 32-bit armv7. I haven't done this in awhile, as I've sort of abandoned 32-bit support.

You'd need to recompile the mame library (libmamearmv7.a) - I think there was a way to specify the 32-bit armv7 architecture - try:
```
./make -j 32 CDBG=-w iOSARMV7=1
```

**Comment by gajahduduk** [comment]
Thanks!  I've little idea how that works, but it did.  After cd to the "MAME4iOS-master" directory, I had to use:
`make -j 32 CDBG=-w iOSARMV7=1`
…(withiout the ./) instead. It generated a fuck ton of output, but after several minutes, the mod date for libmamearmv7.a had changed to current time, so it had apparently replaced it.  after that, the build in Xcode succeeded.  Thanks!

**Comment by yoshisuga** [comment]
Glad you got it working! 👍
