### ISSUE TITLE
CYDIA REPO

### ISSUE THREAD

**Issue by watnaice** [yoshisuga/MAME4iOS#85]
Hi!
is posible install this versión with cydia?
how is the cydia's repo?
THANKS!!

**Comment by daedalia** [comment]
I don't think you can, different build process/toolchain etc wtf. I use a service called Signulous that lets me upload an IPA and sign it for my device. I'm sure jailbreaking removes the need for apps to be signed. I'm sure there is something in Cydia that would let you install unsigned IPA's.

**Comment by mrjschulte** [comment]
Sorry, this version is pretty much hard-wired for the Apple iOS and tvOS ecosystem at this point.

**Comment by bouncingbenji** [comment]
What’s the repo
