### ISSUE TITLE
weird button mapping AppleTV 4K + SteelSeries Nimbus

### ISSUE THREAD

**Issue by mgx0** [yoshisuga/MAME4iOS#91]
Hello,

anyone here using Nimbus MFi controller on Apple TV 4K (tvOS 13.3.1)? I'm experiencing weird button behaviour/mapping with this combination, for example:

- Menu button returns tvOS to home screen
- button B returns tvOS to home screen but when re-opened, it's obvious the menu item has been selected (button works but minimizes the whole app)
- coin, start and select buttons do not work, as they require MENU button to press

I have tried to compile and run the same MAME4iOS build on iPhone 8 iOS 13.3.1 + same Nimbus controller and the buttons work just fine, so it seems to happen only on tvOS.

is there anything I can look into to fix the behaviour please?

**Comment by mrjschulte** [comment]
I opened #92 as a follow up to this to make it a general button configuration ask.

**Comment by mgx0** [comment]
Thanks a lot, I'll watch the other issue

**Comment by mrjschulte** [comment]
Great, closing!

**Comment by ToddLa** [comment]
This is not just “it would be nice to remap buttons” issue, it sounds like the nimbus controller is busted. 

I only have an Xbox controller, we need to try latest 2020.2 on an TV with a nimbus.

**Comment by mgx0** [comment]
I can test on Nimbus

**Comment by mrjschulte** [comment]
Tested on Nimbus and Hori MFI controllers on latest Git pull and works as expected. 

Remember to remap the buttons "inside" of the Mame-settings for each game accordingly.

**Comment by mgx0** [comment]
But Nimbus still behaves as described on the beginning of this issue. I’ll throw it away perhaps, it’s not worth the money and time
