### ISSUE TITLE
Add Controller re-mapping inside of the Application.

### ISSUE THREAD

**Issue by mrjschulte** [yoshisuga/MAME4iOS#92]
We need a means to redefine the MFI/PS4/Xbox Controller buttons in some form of UI. This applies both to iOS and tvOS. Currently the various controllers don't map gracefully across the various control options.

**Comment by ToddLa** [comment]
The “DOS MODE” remapping should work, just be careful if you mess up things you will need to delete the cfg file, or the entire ROM

**Comment by mrjschulte** [comment]
Is it possible to ship with "pre-configured" mapping templates?

**Comment by ToddLa** [comment]
So you are suggesting some sort of per-game pre-config? Sounds like a lot of work. 

Better to just let user remap.

....and the current MAMEUI does let you do that, but I expect you are asking for some GUI

**Comment by mgx0** [comment]
@ToddLa you mentioned MAMEUI does let me do that, could you please share where to look at? I know it's a silly question to ask when I have compiled it, but it would make it quicker for me to remap the controller without waiting for this to be added.

**Comment by ToddLa** [comment]
Bring up the mame menu and remap game inputs. I am not an expert in this area....

**Comment by ToddLa** [comment]
Are you having a Nimbus controller issue? If so that is not a re-mapping problem

-Todd

On Apr 2, 2020, at 8:39 PM, mgx0 <notifications@github.com> wrote:

﻿

@ToddLa<https://github.com/ToddLa> you mentioned MAMEUI does let me do that, could you please share where to look at? I know it's a silly question to ask when I have compiled it, but it would make it quicker for me to remap the controller without waiting for this to be added.

**Comment by mgx0** [comment]
Yes, this one: https://github.com/yoshisuga/MAME4iOS/issues/91

Nimbus is pretty much unusable with MAME

**Comment by ToddLa** [comment]
> Nimbus is pretty much unusable with MAME

Ok I will go get a Nimbus and see what is happening. iOS 13.4 did some wonky things with the SiriRemote, maybe MFi is similar.

**Comment by HowieT23** [comment]
> > Nimbus is pretty much unusable with MAME
> 
> Ok I will go get a Nimbus and see what is happening. iOS 13.4 did some wonky things with the SiriRemote, maybe MFi is similar.

I’m using 2 nimbus controllers just fine on my iPad Pro

**Comment by mrjschulte** [comment]
> Just a note, #91 was about MAME for TVOS
> Thanks a lot

Which build does this refer to? You may want to grab the latest and confirm this is still a thing. Will close this issue if we don't hear back and assume things are good!

**Comment by mgx0** [comment]
Soooorry latest build had it fixed, closing
